# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the credential_lifecycle agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.credential_lifecycle.models import CredentialLifecycleState
from shieldops.agents.credential_lifecycle.nodes import (
    assess_posture,
    discover_credentials,
    enforce_rotation,
    generate_report,
    issue_jit_credentials,
    revoke_stale,
)
from shieldops.agents.credential_lifecycle.tools import CredentialLifecycleToolkit
from shieldops.agents.runtime import END, Agent, edge


class CredentialLifecycleAgent(Agent):
    """Declarative spec for ``credential_lifecycle`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "credential_lifecycle"
    state_model = CredentialLifecycleState
    toolkit_factory = CredentialLifecycleToolkit

    nodes = {
        "discover_credentials": discover_credentials,
        "assess_posture": assess_posture,
        "issue_jit_credentials": issue_jit_credentials,
        "enforce_rotation": enforce_rotation,
        "revoke_stale": revoke_stale,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_credentials", "assess_posture"),
        edge("issue_jit_credentials", "enforce_rotation"),
        edge("enforce_rotation", "revoke_stale"),
        edge("revoke_stale", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "assess_posture"
        #   routed by _needs_remediation() — wrap with cond(...)
    ]

    entry = "discover_credentials"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CredentialLifecycleRunner`` keep working via this alias; new code
# should use ``CredentialLifecycleAgent`` directly through AgentRuntime.
CredentialLifecycleRunner = CredentialLifecycleAgent
