# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the gdpr_processor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.gdpr_processor.models import GDPRProcessorState
from shieldops.agents.gdpr_processor.nodes import (
    check_breaches,
    check_consent,
    generate_report,
    intake_requests,
    map_data,
    process_requests,
)
from shieldops.agents.gdpr_processor.tools import GDPRProcessorToolkit
from shieldops.agents.runtime import END, Agent, edge


class GdprProcessorAgent(Agent):
    """Declarative spec for ``gdpr_processor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "gdpr_processor"
    state_model = GDPRProcessorState
    toolkit_factory = GDPRProcessorToolkit

    nodes = {
        "intake": intake_requests,
        "map_data": map_data,
        "check_consent": check_consent,
        "process_requests": process_requests,
        "check_breaches": check_breaches,
        "generate_report": generate_report,
    }

    edges = [
        edge("map_data", "check_consent"),
        edge("check_consent", "process_requests"),
        edge("process_requests", "check_breaches"),
        edge("check_breaches", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "intake"
        #   routed by _route_after_intake() — wrap with cond(...)
    ]

    entry = "intake"
