# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the compliance_reporter agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.compliance_reporter.models import ComplianceReporterState
from shieldops.agents.compliance_reporter.nodes import (
    assess_controls,
    collect_evidence,
    deliver,
    generate_report,
    package_artifacts,
    select_framework,
)
from shieldops.agents.compliance_reporter.tools import ComplianceReporterToolkit
from shieldops.agents.runtime import END, Agent, edge


class ComplianceReporterAgent(Agent):
    """Declarative spec for ``compliance_reporter`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "compliance_reporter"
    state_model = ComplianceReporterState
    toolkit_factory = ComplianceReporterToolkit

    nodes = {
        "select_framework": select_framework,
        "collect_evidence": collect_evidence,
        "assess_controls": assess_controls,
        "generate_report": generate_report,
        "package_artifacts": package_artifacts,
        "deliver": deliver,
    }

    edges = [
        edge("select_framework", "collect_evidence"),
        edge("collect_evidence", "assess_controls"),
        edge("assess_controls", "generate_report"),
        edge("generate_report", "package_artifacts"),
        edge("package_artifacts", "deliver"),
        edge("deliver", END),
    ]

    entry = "select_framework"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ComplianceReporterRunner`` keep working via this alias; new code
# should use ``ComplianceReporterAgent`` directly through AgentRuntime.
ComplianceReporterRunner = ComplianceReporterAgent
