# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the secret_rotation_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.secret_rotation_manager.models import SecretRotationManagerState
from shieldops.agents.secret_rotation_manager.nodes import (
    assess_rotation,
    execute_rotation,
    generate_report,
    inventory_secrets,
    plan_rotation,
    verify_health,
)
from shieldops.agents.secret_rotation_manager.tools import SecretRotationManagerToolkit


class SecretRotationManagerAgent(Agent):
    """Declarative spec for ``secret_rotation_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "secret_rotation_manager"
    state_model = SecretRotationManagerState
    toolkit_factory = SecretRotationManagerToolkit

    nodes = {
        "inventory_secrets": inventory_secrets,
        "assess_rotation": assess_rotation,
        "plan_rotation": plan_rotation,
        "execute_rotation": execute_rotation,
        "verify_health": verify_health,
        "report": generate_report,
    }

    edges = [
        edge("inventory_secrets", "assess_rotation"),
        edge("assess_rotation", "plan_rotation"),
        edge("plan_rotation", "execute_rotation"),
        edge("execute_rotation", "verify_health"),
        edge("verify_health", "report"),
        edge("report", END),
    ]

    entry = "inventory_secrets"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecretRotationManagerRunner`` keep working via this alias; new code
# should use ``SecretRotationManagerAgent`` directly through AgentRuntime.
SecretRotationManagerRunner = SecretRotationManagerAgent
