# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_workflow_builder agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_workflow_builder.models import SecurityWorkflowBuilderState
from shieldops.agents.security_workflow_builder.nodes import (
    build_workflow,
    define_trigger,
    deploy_workflow,
    generate_report,
    test_execution,
    validate_logic,
)
from shieldops.agents.security_workflow_builder.tools import SecurityWorkflowBuilderToolkit


class SecurityWorkflowBuilderAgent(Agent):
    """Declarative spec for ``security_workflow_builder`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_workflow_builder"
    state_model = SecurityWorkflowBuilderState
    toolkit_factory = SecurityWorkflowBuilderToolkit

    nodes = {
        "define_trigger": define_trigger,
        "build_workflow": build_workflow,
        "validate_logic": validate_logic,
        "test_execution": test_execution,
        "deploy_workflow": deploy_workflow,
        "report": generate_report,
    }

    edges = [
        edge("define_trigger", "build_workflow"),
        edge("build_workflow", "validate_logic"),
        edge("validate_logic", "test_execution"),
        edge("test_execution", "deploy_workflow"),
        edge("deploy_workflow", "report"),
        edge("report", END),
    ]

    entry = "define_trigger"
