# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the certificate_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.certificate_manager.models import CertificateManagerState
from shieldops.agents.certificate_manager.nodes import (
    check_expiry,
    discover_certs,
    execute_rotation,
    generate_report,
    plan_rotation,
    validate_chains,
)
from shieldops.agents.certificate_manager.tools import CertificateManagerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CertificateManagerAgent(Agent):
    """Declarative spec for ``certificate_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "certificate_manager"
    state_model = CertificateManagerState
    toolkit_factory = CertificateManagerToolkit

    nodes = {
        "discover_certs": discover_certs,
        "check_expiry": check_expiry,
        "validate_chains": validate_chains,
        "plan_rotation": plan_rotation,
        "execute_rotation": execute_rotation,
        "report": generate_report,
    }

    edges = [
        edge("discover_certs", "check_expiry"),
        edge("check_expiry", "validate_chains"),
        edge("validate_chains", "plan_rotation"),
        edge("plan_rotation", "execute_rotation"),
        edge("execute_rotation", "report"),
        edge("report", END),
    ]

    entry = "discover_certs"
