# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cross_cloud_posture_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cross_cloud_posture_manager.models import CrossCloudPostureManagerState
from shieldops.agents.cross_cloud_posture_manager.nodes import (
    assess_compliance,
    compare_baselines,
    detect_drift,
    generate_report,
    plan_remediation,
    scan_posture,
)
from shieldops.agents.cross_cloud_posture_manager.tools import CrossCloudPostureManagerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CrossCloudPostureManagerAgent(Agent):
    """Declarative spec for ``cross_cloud_posture_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cross_cloud_posture_manager"
    state_model = CrossCloudPostureManagerState
    toolkit_factory = CrossCloudPostureManagerToolkit

    nodes = {
        "scan_posture": scan_posture,
        "compare_baselines": compare_baselines,
        "detect_drift": detect_drift,
        "assess_compliance": assess_compliance,
        "plan_remediation": plan_remediation,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_posture", "compare_baselines"),
        edge("detect_drift", "assess_compliance"),
        edge("plan_remediation", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "compare_baselines" via _should_detect_drift()
        # TODO: cond(...) from "assess_compliance" via _should_plan()
    ]

    entry = "scan_posture"
