# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_brief_generator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_brief_generator.models import ThreatBriefGeneratorState
from shieldops.agents.threat_brief_generator.nodes import (
    analyze_threats,
    assess_relevance,
    collect_intel,
    draft_brief,
    report,
    review,
)
from shieldops.agents.threat_brief_generator.tools import ThreatBriefGeneratorToolkit


class ThreatBriefGeneratorAgent(Agent):
    """Declarative spec for ``threat_brief_generator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_brief_generator"
    state_model = ThreatBriefGeneratorState
    toolkit_factory = ThreatBriefGeneratorToolkit

    nodes = {
        "collect_intel": collect_intel,
        "analyze_threats": analyze_threats,
        "assess_relevance": assess_relevance,
        "draft_brief": draft_brief,
        "review": review,
        "report": report,
    }

    edges = [
        edge("review", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_intel" via _check_error()
        # TODO: cond(...) from "analyze_threats" via _check_error()
        # TODO: cond(...) from "assess_relevance" via _check_error()
        # TODO: cond(...) from "draft_brief" via _check_error()
    ]

    entry = "collect_intel"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ThreatBriefGeneratorRunner`` keep working via this alias; new code
# should use ``ThreatBriefGeneratorAgent`` directly through AgentRuntime.
ThreatBriefGeneratorRunner = ThreatBriefGeneratorAgent
