# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the policy_compliance_enforcer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.policy_compliance_enforcer.models import PolicyComplianceEnforcerState
from shieldops.agents.policy_compliance_enforcer.nodes import (
    audit_log,
    check_compliance,
    enforce_decision,
    evaluate_request,
    generate_report,
    load_policies,
)
from shieldops.agents.policy_compliance_enforcer.tools import PolicyComplianceEnforcerToolkit
from shieldops.agents.runtime import END, Agent, edge


class PolicyComplianceEnforcerAgent(Agent):
    """Declarative spec for ``policy_compliance_enforcer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "policy_compliance_enforcer"
    state_model = PolicyComplianceEnforcerState
    toolkit_factory = PolicyComplianceEnforcerToolkit

    nodes = {
        "load_policies": load_policies,
        "evaluate_request": evaluate_request,
        "check_compliance": check_compliance,
        "enforce_decision": enforce_decision,
        "audit_log": audit_log,
        "generate_report": generate_report,
    }

    edges = [
        edge("load_policies", "evaluate_request"),
        edge("check_compliance", "enforce_decision"),
        edge("enforce_decision", "audit_log"),
        edge("audit_log", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "evaluate_request"
        #   routed by _should_check_compliance() — wrap with cond(...)
    ]

    entry = "load_policies"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``PolicyComplianceEnforcerRunner`` keep working via this alias; new code
# should use ``PolicyComplianceEnforcerAgent`` directly through AgentRuntime.
PolicyComplianceEnforcerRunner = PolicyComplianceEnforcerAgent
