# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the database_security_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.database_security_scanner.models import DatabaseSecurityScannerState
from shieldops.agents.database_security_scanner.nodes import (
    audit_access,
    check_authentication,
    detect_data_exposure,
    discover_databases,
    generate_report,
    scan_configurations,
)
from shieldops.agents.database_security_scanner.tools import DatabaseSecurityScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DatabaseSecurityScannerAgent(Agent):
    """Declarative spec for ``database_security_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "database_security_scanner"
    state_model = DatabaseSecurityScannerState
    toolkit_factory = DatabaseSecurityScannerToolkit

    nodes = {
        "discover_databases": discover_databases,
        "scan_config": scan_configurations,
        "check_auth": check_authentication,
        "audit_access": audit_access,
        "detect_exposure": detect_data_exposure,
        "report": generate_report,
    }

    edges = [
        edge("discover_databases", "scan_config"),
        edge("scan_config", "check_auth"),
        edge("check_auth", "audit_access"),
        edge("audit_access", "detect_exposure"),
        edge("detect_exposure", "report"),
        edge("report", END),
    ]

    entry = "discover_databases"
