# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_landscape_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_landscape_analyzer.models import ThreatLandscapeAnalyzerState
from shieldops.agents.threat_landscape_analyzer.nodes import (
    analyze_trends,
    benchmark_posture,
    collect_intel,
    generate_report,
    generate_threat_brief,
    map_to_industry,
)
from shieldops.agents.threat_landscape_analyzer.tools import ThreatLandscapeAnalyzerToolkit


class ThreatLandscapeAnalyzerAgent(Agent):
    """Declarative spec for ``threat_landscape_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_landscape_analyzer"
    state_model = ThreatLandscapeAnalyzerState
    toolkit_factory = ThreatLandscapeAnalyzerToolkit

    nodes = {
        "collect_intel": collect_intel,
        "analyze_trends": analyze_trends,
        "map_to_industry": map_to_industry,
        "benchmark_posture": benchmark_posture,
        "generate_threat_brief": generate_threat_brief,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_intel", "analyze_trends"),
        edge("analyze_trends", "map_to_industry"),
        edge("map_to_industry", "benchmark_posture"),
        edge("generate_threat_brief", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "benchmark_posture"
        #   routed by _should_brief() — wrap with cond(...)
    ]

    entry = "collect_intel"
