# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_orchestration_mesh agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_orchestration_mesh.models import SecurityOrchestrationMeshState
from shieldops.agents.security_orchestration_mesh.nodes import (
    aggregate_results,
    coordinate_execution,
    discover_regions,
    distribute_tasks,
    generate_report,
    map_capabilities,
)
from shieldops.agents.security_orchestration_mesh.tools import SecurityOrchestrationMeshToolkit


class SecurityOrchestrationMeshAgent(Agent):
    """Declarative spec for ``security_orchestration_mesh`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_orchestration_mesh"
    state_model = SecurityOrchestrationMeshState
    toolkit_factory = SecurityOrchestrationMeshToolkit

    nodes = {
        "discover_regions": discover_regions,
        "map_capabilities": map_capabilities,
        "distribute_tasks": distribute_tasks,
        "coordinate_execution": coordinate_execution,
        "aggregate_results": aggregate_results,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_regions", "map_capabilities"),
        edge("distribute_tasks", "coordinate_execution"),
        edge("aggregate_results", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "map_capabilities" via _should_distribute()
        # TODO: cond(...) from "coordinate_execution" via _should_aggregate()
    ]

    entry = "discover_regions"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityOrchestrationMeshRunner`` keep working via this alias; new code
# should use ``SecurityOrchestrationMeshAgent`` directly through AgentRuntime.
SecurityOrchestrationMeshRunner = SecurityOrchestrationMeshAgent
