# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_network_firewall agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_network_firewall.models import CloudNetworkFirewallState
from shieldops.agents.cloud_network_firewall.nodes import (
    analyze_coverage,
    collect_rules,
    detect_overpermissive,
    find_shadow_rules,
    generate_report,
    optimize_rules,
)
from shieldops.agents.cloud_network_firewall.tools import CloudNetworkFirewallToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudNetworkFirewallAgent(Agent):
    """Declarative spec for ``cloud_network_firewall`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_network_firewall"
    state_model = CloudNetworkFirewallState
    toolkit_factory = CloudNetworkFirewallToolkit

    nodes = {
        "collect_rules": collect_rules,
        "analyze_coverage": analyze_coverage,
        "detect_overpermissive": detect_overpermissive,
        "find_shadow_rules": find_shadow_rules,
        "optimize_rules": optimize_rules,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_rules", "analyze_coverage"),
        edge("analyze_coverage", "detect_overpermissive"),
        edge("detect_overpermissive", "find_shadow_rules"),
        edge("optimize_rules", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "find_shadow_rules"
        #   routed by _has_findings() — wrap with cond(...)
    ]

    entry = "collect_rules"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CloudNetworkFirewallRunner`` keep working via this alias; new code
# should use ``CloudNetworkFirewallAgent`` directly through AgentRuntime.
CloudNetworkFirewallRunner = CloudNetworkFirewallAgent
