# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the mcp_security agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.mcp_security.models import MCPSecurityState
from shieldops.agents.mcp_security.nodes import (
    analyze_permissions,
    detect_god_keys,
    discover_servers,
    generate_policies,
    generate_report,
    map_connections,
    scan_configs,
    scan_supply_chain,
)
from shieldops.agents.mcp_security.tools import MCPSecurityToolkit
from shieldops.agents.runtime import END, Agent, edge


class McpSecurityAgent(Agent):
    """Declarative spec for ``mcp_security`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "mcp_security"
    state_model = MCPSecurityState
    toolkit_factory = MCPSecurityToolkit

    nodes = {
        "discover_servers": discover_servers,
        "map_connections": map_connections,
        "analyze_permissions": analyze_permissions,
        "scan_configs": scan_configs,
        "detect_god_keys": detect_god_keys,
        "scan_supply_chain": scan_supply_chain,
        "generate_policies": generate_policies,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_servers", "map_connections"),
        edge("map_connections", "analyze_permissions"),
        edge("analyze_permissions", "scan_configs"),
        edge("scan_configs", "detect_god_keys"),
        edge("scan_supply_chain", "generate_policies"),
        edge("generate_policies", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_god_keys"
        #   routed by should_deep_scan() — wrap with cond(...)
    ]

    entry = "discover_servers"
