# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the deception_mesh_controller agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.deception_mesh_controller.models import DeceptionMeshControllerState
from shieldops.agents.deception_mesh_controller.nodes import (
    analyze_attacker,
    correlate_intel,
    deploy_decoys,
    generate_report,
    monitor_interactions,
    plan_deployment,
)
from shieldops.agents.deception_mesh_controller.tools import DeceptionMeshControllerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DeceptionMeshControllerAgent(Agent):
    """Declarative spec for ``deception_mesh_controller`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "deception_mesh_controller"
    state_model = DeceptionMeshControllerState
    toolkit_factory = DeceptionMeshControllerToolkit

    nodes = {
        "plan_deployment": plan_deployment,
        "deploy_decoys": deploy_decoys,
        "monitor_interactions": monitor_interactions,
        "analyze_attacker": analyze_attacker,
        "correlate_intel": correlate_intel,
        "generate_report": generate_report,
    }

    edges = [
        edge("plan_deployment", "deploy_decoys"),
        edge("deploy_decoys", "monitor_interactions"),
        edge("correlate_intel", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "monitor_interactions" via _should_analyze()
        # TODO: cond(...) from "analyze_attacker" via _should_correlate()
    ]

    entry = "plan_deployment"
