# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the shadow_ai_discovery agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.shadow_ai_discovery.models import ShadowAIDiscoveryState
from shieldops.agents.shadow_ai_discovery.nodes import (
    analyze_traffic,
    classify_risk,
    generate_report,
    identify_agents,
    recommend_governance,
    scan_network,
)
from shieldops.agents.shadow_ai_discovery.tools import ShadowAIDiscoveryToolkit


class ShadowAiDiscoveryAgent(Agent):
    """Declarative spec for ``shadow_ai_discovery`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "shadow_ai_discovery"
    state_model = ShadowAIDiscoveryState
    toolkit_factory = ShadowAIDiscoveryToolkit

    nodes = {
        "scan_network": scan_network,
        "analyze_traffic": analyze_traffic,
        "identify_agents": identify_agents,
        "classify_risk": classify_risk,
        "recommend_governance": recommend_governance,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_network", "analyze_traffic"),
        edge("analyze_traffic", "identify_agents"),
        edge("identify_agents", "classify_risk"),
        edge("recommend_governance", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "classify_risk"
        #   routed by _needs_governance() — wrap with cond(...)
    ]

    entry = "scan_network"
