# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the infrastructure_drift_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.infrastructure_drift_detector.models import InfrastructureDriftDetectorState
from shieldops.agents.infrastructure_drift_detector.nodes import (
    classify_changes,
    compare_baseline,
    detect_drift,
    remediate_drift,
    report,
    scan_infrastructure,
)
from shieldops.agents.infrastructure_drift_detector.tools import InfrastructureDriftDetectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class InfrastructureDriftDetectorAgent(Agent):
    """Declarative spec for ``infrastructure_drift_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "infrastructure_drift_detector"
    state_model = InfrastructureDriftDetectorState
    toolkit_factory = InfrastructureDriftDetectorToolkit

    nodes = {
        "scan_infrastructure": scan_infrastructure,
        "compare_baseline": compare_baseline,
        "detect_drift": detect_drift,
        "classify_changes": classify_changes,
        "remediate_drift": remediate_drift,
        "report": report,
    }

    edges = [
        edge("remediate_drift", "report"),
        edge("report", END),
        # TODO: cond(...) from "scan_infrastructure" via _check_error()
        # TODO: cond(...) from "compare_baseline" via _check_error()
        # TODO: cond(...) from "detect_drift" via _check_error()
        # TODO: cond(...) from "classify_changes" via _check_error()
    ]

    entry = "scan_infrastructure"
