# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_hunt_orchestrator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_hunt_orchestrator.models import ThreatHuntOrchestratorState
from shieldops.agents.threat_hunt_orchestrator.nodes import (
    analyze_data,
    collect_evidence,
    document_hunt,
    generate_hypothesis,
    generate_report,
    validate_findings,
)
from shieldops.agents.threat_hunt_orchestrator.tools import ThreatHuntOrchestratorToolkit


class ThreatHuntOrchestratorAgent(Agent):
    """Declarative spec for ``threat_hunt_orchestrator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_hunt_orchestrator"
    state_model = ThreatHuntOrchestratorState
    toolkit_factory = ThreatHuntOrchestratorToolkit

    nodes = {
        "generate_hypothesis": generate_hypothesis,
        "collect_evidence": collect_evidence,
        "analyze_data": analyze_data,
        "validate_findings": validate_findings,
        "document_hunt": document_hunt,
        "generate_report": generate_report,
    }

    edges = [
        edge("generate_hypothesis", "collect_evidence"),
        edge("collect_evidence", "analyze_data"),
        edge("analyze_data", "validate_findings"),
        edge("document_hunt", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "validate_findings"
        #   routed by _should_document() — wrap with cond(...)
    ]

    entry = "generate_hypothesis"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ThreatHuntOrchestratorRunner`` keep working via this alias; new code
# should use ``ThreatHuntOrchestratorAgent`` directly through AgentRuntime.
ThreatHuntOrchestratorRunner = ThreatHuntOrchestratorAgent
