# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the environmental_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.environmental_monitor.models import EnvironmentalMonitorState
from shieldops.agents.environmental_monitor.nodes import (
    alert,
    assess_risk,
    check_thresholds,
    collect_readings,
    correlate_events,
    report,
)
from shieldops.agents.environmental_monitor.tools import EnvironmentalMonitorToolkit
from shieldops.agents.runtime import END, Agent, edge


class EnvironmentalMonitorAgent(Agent):
    """Declarative spec for ``environmental_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "environmental_monitor"
    state_model = EnvironmentalMonitorState
    toolkit_factory = EnvironmentalMonitorToolkit

    nodes = {
        "collect_readings": collect_readings,
        "check_thresholds": check_thresholds,
        "correlate_events": correlate_events,
        "assess_risk": assess_risk,
        "alert": alert,
        "report": report,
    }

    edges = [
        edge("alert", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_readings" via _check_error()
        # TODO: cond(...) from "check_thresholds" via _check_error()
        # TODO: cond(...) from "correlate_events" via _check_error()
        # TODO: cond(...) from "assess_risk" via _check_error()
    ]

    entry = "collect_readings"
