# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the phishing_simulator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.phishing_simulator.models import PhishingSimulatorState
from shieldops.agents.phishing_simulator.nodes import (
    analyze_results,
    design_campaign,
    generate_report,
    select_targets,
    send_simulations,
    track_responses,
)
from shieldops.agents.phishing_simulator.tools import PhishingSimulatorToolkit
from shieldops.agents.runtime import END, Agent, edge


class PhishingSimulatorAgent(Agent):
    """Declarative spec for ``phishing_simulator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "phishing_simulator"
    state_model = PhishingSimulatorState
    toolkit_factory = PhishingSimulatorToolkit

    nodes = {
        "design_campaign": design_campaign,
        "select_targets": select_targets,
        "send_simulations": send_simulations,
        "track_responses": track_responses,
        "analyze_results": analyze_results,
        "generate_report": generate_report,
    }

    edges = [
        edge("design_campaign", "select_targets"),
        edge("select_targets", "send_simulations"),
        edge("send_simulations", "track_responses"),
        edge("analyze_results", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "track_responses"
        #   routed by _has_responses() — wrap with cond(...)
    ]

    entry = "design_campaign"
