# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the detection_gap_finder agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.detection_gap_finder.models import DetectionGapFinderState
from shieldops.agents.detection_gap_finder.nodes import (
    generate_report,
    identify_blind_spots,
    monitor_detections,
    prioritize_gaps,
    select_techniques,
    simulate_attacks,
)
from shieldops.agents.detection_gap_finder.tools import DetectionGapFinderToolkit
from shieldops.agents.runtime import END, Agent, edge


class DetectionGapFinderAgent(Agent):
    """Declarative spec for ``detection_gap_finder`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "detection_gap_finder"
    state_model = DetectionGapFinderState
    toolkit_factory = DetectionGapFinderToolkit

    nodes = {
        "select_techniques": select_techniques,
        "simulate_attacks": simulate_attacks,
        "monitor_detections": monitor_detections,
        "identify_blind_spots": identify_blind_spots,
        "prioritize_gaps": prioritize_gaps,
        "generate_report": generate_report,
    }

    edges = [
        edge("simulate_attacks", "monitor_detections"),
        edge("monitor_detections", "identify_blind_spots"),
        edge("identify_blind_spots", "prioritize_gaps"),
        edge("prioritize_gaps", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "select_techniques"
        #   routed by _has_techniques() — wrap with cond(...)
    ]

    entry = "select_techniques"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DetectionGapFinderRunner`` keep working via this alias; new code
# should use ``DetectionGapFinderAgent`` directly through AgentRuntime.
DetectionGapFinderRunner = DetectionGapFinderAgent
