# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the adversary_emulator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.adversary_emulator.models import AdversaryEmulatorState
from shieldops.agents.adversary_emulator.nodes import (
    execute_ttps,
    observe_defenses,
    plan_campaign,
    report,
    score,
    select_adversary,
)
from shieldops.agents.adversary_emulator.tools import AdversaryEmulatorToolkit
from shieldops.agents.runtime import END, Agent, edge


class AdversaryEmulatorAgent(Agent):
    """Declarative spec for ``adversary_emulator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "adversary_emulator"
    state_model = AdversaryEmulatorState
    toolkit_factory = AdversaryEmulatorToolkit

    nodes = {
        "select_adversary": select_adversary,
        "plan_campaign": plan_campaign,
        "execute_ttps": execute_ttps,
        "observe_defenses": observe_defenses,
        "score": score,
        "report": report,
    }

    edges = [
        edge("score", "report"),
        edge("report", END),
        # TODO: cond(...) from "select_adversary" via _check_error()
        # TODO: cond(...) from "plan_campaign" via _check_error()
        # TODO: cond(...) from "execute_ttps" via _check_error()
        # TODO: cond(...) from "observe_defenses" via _check_error()
    ]

    entry = "select_adversary"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AdversaryEmulatorRunner`` keep working via this alias; new code
# should use ``AdversaryEmulatorAgent`` directly through AgentRuntime.
AdversaryEmulatorRunner = AdversaryEmulatorAgent
