# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the dns_firewall_controller agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.dns_firewall_controller.models import DNSFirewallControllerState
from shieldops.agents.dns_firewall_controller.nodes import (
    analyze_domains,
    check_reputation,
    detect_tunneling,
    enforce_policy,
    generate_report,
    ingest_queries,
)
from shieldops.agents.dns_firewall_controller.tools import DNSFirewallControllerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DnsFirewallControllerAgent(Agent):
    """Declarative spec for ``dns_firewall_controller`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "dns_firewall_controller"
    state_model = DNSFirewallControllerState
    toolkit_factory = DNSFirewallControllerToolkit

    nodes = {
        "ingest_queries": ingest_queries,
        "analyze_domains": analyze_domains,
        "check_reputation": check_reputation,
        "detect_tunneling": detect_tunneling,
        "enforce_policy": enforce_policy,
        "report": generate_report,
    }

    edges = [
        edge("ingest_queries", "analyze_domains"),
        edge("analyze_domains", "check_reputation"),
        edge("check_reputation", "detect_tunneling"),
        edge("detect_tunneling", "enforce_policy"),
        edge("enforce_policy", "report"),
        edge("report", END),
    ]

    entry = "ingest_queries"
