"""Codemod: migrate hand-rolled ``runner.py`` + ``graph.py`` + ``set_toolkit``
triples to a declarative ``agent.py`` sitting on top of
:class:`shieldops.agents.runtime.Agent` — RFC #247 PR-3.

For each ``src/shieldops/agents/<name>/`` directory the codemod parses
``runner.py``, ``graph.py``, and ``nodes.py`` with :mod:`ast` and
synthesises a new ``agent.py`` containing an ``Agent`` subclass whose
class attributes declare the graph spec (name, state_model,
toolkit_factory, nodes, edges, entry).

Ports expected on the runtime-side ``Agent`` base class
(:mod:`shieldops.agents.runtime.agent`)::

    class Agent[StateT]:
        name: ClassVar[str]
        state_model: ClassVar[type]
        toolkit_factory: ClassVar[Callable[[], Any]]
        nodes: ClassVar[dict[str, NodeFn]]
        edges: ClassVar[list[Edge | ConditionalEdge]]
        entry: ClassVar[str]

If the base class ever changes its attribute shape the emitted stub
will drift — re-run the codemod.

**Idempotency.** The codemod skips any agent whose directory already
contains an ``agent.py`` OR whose ``agent.py`` carries the marker
``_shieldops_runtime_migrated = True``. Running twice produces zero
diff.

**Dry-run by default.** Without ``--apply`` the codemod only reports a
JSON summary::

    {
      "mode": "dry-run",
      "total_agents": 503,
      "migrated": 312,
      "skipped_already_migrated": 0,
      "skipped_shape": 191,
      "samples": {...},
      "skip_reasons": {"no_runner": 3, "no_graph": 5, ...}
    }

Pass ``--apply`` to write the files.

**Scope matching.** A "canonical" runner is one whose ``runner.py``
contains ``class <Name>Runner`` with an ``async def run`` *or*
``async def execute`` method and whose ``graph.py`` either calls
``graph.add_node(...)`` with string literal names or constructs a
``StateGraph(...)`` at module level. Anything else ends up in the
``skipped_shape`` bucket with a human-readable reason.

Usage::

    python scripts/codemods/agent_runtime.py           # dry-run
    python scripts/codemods/agent_runtime.py --apply    # write
    python scripts/codemods/agent_runtime.py --root <path>  # override
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_AGENTS = ROOT / "src" / "shieldops" / "agents"

MARKER = "_shieldops_runtime_migrated"
HEADER = "# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)\n"


# ---------------------------------------------------------------------------
# Extraction result types
# ---------------------------------------------------------------------------


@dataclass
class GraphSpec:
    """Parsed graph.py spec: node names, edges, entry point."""

    node_names: list[str] = field(default_factory=list)
    node_fn_refs: dict[str, str] = field(default_factory=dict)
    """Map node name → name of the python function it was bound to
    (so the emitter can import it from ``nodes``)."""

    edges: list[tuple[str, str]] = field(default_factory=list)
    conditional_edges: list[tuple[str, str]] = field(default_factory=list)
    """Pairs of (source_node, predicate_fn_name) — the routing map is
    preserved verbatim in the emitted file as a TODO comment because
    the codemod can't safely guess predicate semantics."""

    entry_point: str | None = None
    state_model: str | None = None
    toolkit_class: str | None = None


@dataclass
class RunnerSpec:
    """Parsed runner.py metadata."""

    runner_class: str
    run_method: str  # 'run' or 'execute'
    toolkit_class: str | None = None
    state_model: str | None = None


@dataclass
class AgentExtract:
    """Everything the emitter needs to write agent.py."""

    dir_path: Path
    agent_name: str
    runner: RunnerSpec
    graph: GraphSpec


# ---------------------------------------------------------------------------
# Parsers — pure ast, no string scraping for structure
# ---------------------------------------------------------------------------


def _parse(path: Path) -> ast.Module | None:
    try:
        return ast.parse(path.read_text())
    except (SyntaxError, UnicodeDecodeError, OSError):
        return None


def _find_class(tree: ast.Module, predicate: Any) -> ast.ClassDef | None:
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and predicate(node):
            return node
    return None


def parse_runner(path: Path) -> tuple[RunnerSpec | None, str]:
    """Return (spec, reason). reason is '' on success, else why we skipped."""
    tree = _parse(path)
    if tree is None:
        return None, "runner_parse_error"

    runner_cls = _find_class(tree, lambda c: c.name.endswith("Runner"))
    if runner_cls is None:
        return None, "no_runner_class"

    run_method: str | None = None
    # Prefer 'run' or 'execute' if present; otherwise fall back to the first
    # public async method on the Runner class. Many ShieldOps runners use a
    # domain verb (certify, remediate, investigate, run_campaign) as the sole
    # public async entry — RFC #247 PR-5 batch 2+ treats any such method as
    # the spec's entry method.
    preferred: str | None = None
    fallback: str | None = None
    for item in runner_cls.body:
        if isinstance(item, ast.AsyncFunctionDef):
            if item.name in {"run", "execute"}:
                preferred = item.name
                break
            if fallback is None and not item.name.startswith("_"):
                fallback = item.name
    run_method = preferred or fallback
    if run_method is None:
        return None, "no_async_run_or_execute"

    # Optional — toolkit / state model hints from __init__ attribute binding.
    toolkit_class: str | None = None
    state_model: str | None = None
    for item in runner_cls.body:
        if isinstance(item, ast.FunctionDef) and item.name == "__init__":
            for stmt in ast.walk(item):
                if (
                    isinstance(stmt, ast.Assign)
                    and isinstance(stmt.value, ast.Call)
                    and isinstance(stmt.value.func, ast.Name)
                    and stmt.value.func.id.endswith("Toolkit")
                ):
                    toolkit_class = stmt.value.func.id
                if (
                    isinstance(stmt, ast.Call)
                    and isinstance(stmt.func, ast.Name)
                    and stmt.func.id.endswith("State")
                ):
                    state_model = stmt.func.id

    # Fall-back: scrape imports for the Toolkit + State symbols.
    for top in tree.body:
        if isinstance(top, ast.ImportFrom):
            for alias in top.names:
                if toolkit_class is None and alias.name.endswith("Toolkit"):
                    toolkit_class = alias.name
                if state_model is None and alias.name.endswith("State"):
                    state_model = alias.name

    return (
        RunnerSpec(
            runner_class=runner_cls.name,
            run_method=run_method,
            toolkit_class=toolkit_class,
            state_model=state_model,
        ),
        "",
    )


def parse_graph(path: Path) -> tuple[GraphSpec | None, str]:
    """Extract nodes/edges/entry from graph.py via ast."""
    tree = _parse(path)
    if tree is None:
        return None, "graph_parse_error"

    spec = GraphSpec()

    # Track variables pointing at a StateGraph(...) instance (usually 'graph').
    graph_vars: set[str] = set()

    # Many hand-rolled graph.py files define inner async wrappers inside
    # ``build_graph`` that delegate to an imported node fn, e.g.:
    #     async def _baseline(state):
    #         return await compute_baseline(_to_dict(state), toolkit)
    #     graph.add_node("baseline", _baseline)
    # We want the emitter to import ``compute_baseline`` (the real public
    # function), not ``_baseline`` (a module-private closure). Walk inner
    # function bodies, find the first Await that resolves to a Name, and
    # build a map wrapper_name -> underlying_fn_name.
    inner_fn_map: dict[str, str] = {}
    for inner in ast.walk(tree):
        if isinstance(inner, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for sub in ast.walk(inner):
                if isinstance(sub, ast.Await) and isinstance(sub.value, ast.Call):
                    call = sub.value
                    if isinstance(call.func, ast.Name):
                        inner_fn_map[inner.name] = call.func.id
                        break
                    if isinstance(call.func, ast.Attribute):
                        inner_fn_map[inner.name] = call.func.attr
                        break
                # Plain return of a non-awaited call also counts (sync node fn)
                if isinstance(sub, ast.Return) and isinstance(sub.value, ast.Call):
                    call = sub.value
                    if isinstance(call.func, ast.Name):
                        inner_fn_map.setdefault(inner.name, call.func.id)

    for node in ast.walk(tree):
        # StateGraph(SomeState) — capture state_model
        if (
            isinstance(node, ast.Assign)
            and isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Name)
            and node.value.func.id == "StateGraph"
        ):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name):
                    graph_vars.add(tgt.id)
            if node.value.args and isinstance(node.value.args[0], ast.Name):
                spec.state_model = node.value.args[0].id

        # Method calls on the graph variable.
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            recv = node.func.value
            if not (isinstance(recv, ast.Name) and (recv.id in graph_vars or recv.id == "graph")):
                continue
            method = node.func.attr

            if method == "add_node" and len(node.args) >= 2:
                name_arg = node.args[0]
                fn_arg = node.args[1]
                if isinstance(name_arg, ast.Constant) and isinstance(name_arg.value, str):
                    node_name = name_arg.value
                    spec.node_names.append(node_name)
                    fn_name = _extract_fn_name(fn_arg)
                    if fn_name is not None:
                        spec.node_fn_refs[node_name] = fn_name
            elif method == "set_entry_point" and node.args:
                arg0 = node.args[0]
                if isinstance(arg0, ast.Constant) and isinstance(arg0.value, str):
                    spec.entry_point = arg0.value
            elif method == "add_edge" and len(node.args) >= 2:
                a, b = node.args[0], node.args[1]
                if isinstance(a, ast.Constant) and isinstance(a.value, str):
                    src = a.value
                    if isinstance(b, ast.Constant) and isinstance(b.value, str):
                        spec.edges.append((src, b.value))
                    elif isinstance(b, ast.Name) and b.id == "END":
                        spec.edges.append((src, "__END__"))
            elif method == "add_conditional_edges" and len(node.args) >= 2:
                a, pred = node.args[0], node.args[1]
                if isinstance(a, ast.Constant) and isinstance(a.value, str):
                    pred_name = pred.id if isinstance(pred, ast.Name) else "<callable>"
                    spec.conditional_edges.append((a.value, pred_name))

    # Fallback: recognise ``build_linear_graph(StateModel, [(name, fn), ...],
    # toolkit=...)`` — the helper many agents migrated to in RFC #246.
    # Treat it as a linear chain with entry at the first node.
    if not spec.node_names:
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Name)
                and node.func.id == "build_linear_graph"
                and len(node.args) >= 2
            ):
                state_arg = node.args[0]
                list_arg = node.args[1]
                if isinstance(state_arg, ast.Name) and spec.state_model is None:
                    spec.state_model = state_arg.id
                if isinstance(list_arg, ast.List):
                    for elt in list_arg.elts:
                        if isinstance(elt, ast.Tuple) and len(elt.elts) == 2:
                            nm, fn = elt.elts
                            if isinstance(nm, ast.Constant) and isinstance(nm.value, str):
                                node_name = nm.value
                                spec.node_names.append(node_name)
                                fn_name = _extract_fn_name(fn)
                                if fn_name is not None:
                                    spec.node_fn_refs[node_name] = fn_name
                if spec.node_names:
                    # Build sequential edges end -> next
                    for a, b in zip(spec.node_names, spec.node_names[1:], strict=False):
                        spec.edges.append((a, b))
                    spec.edges.append((spec.node_names[-1], "__END__"))
                    if spec.entry_point is None:
                        spec.entry_point = spec.node_names[0]
                    break

    if not spec.node_names:
        return None, "no_nodes_found_in_graph"
    if spec.entry_point is None:
        return None, "no_entry_point"

    # Collect names imported from .nodes so we can filter out private inner
    # wrappers that aren't exported.
    nodes_imports: set[str] = set()
    for top in tree.body:
        if isinstance(top, ast.ImportFrom) and (top.module or "").endswith("nodes"):
            for alias in top.names:
                nodes_imports.add(alias.asname or alias.name)

    # Resolve inner-wrapper references to their underlying imported function.
    for node_name, fn_ref in list(spec.node_fn_refs.items()):
        if fn_ref in inner_fn_map:
            resolved = inner_fn_map[fn_ref]
            # Only swap if the resolved name is actually imported from nodes
            # (avoids swapping to a helper like ``_to_dict``).
            if not nodes_imports or resolved in nodes_imports:
                spec.node_fn_refs[node_name] = resolved

    return spec, ""


def _extract_fn_name(expr: ast.expr) -> str | None:
    """Extract a reasonable "node function name" from the 2nd arg of
    ``add_node``. Handles plain ``ast.Name`` (``discover_sessions``),
    ``traced_node(...)(fn)`` wrappers, and attribute lookups
    (``mod.fn``)."""
    if isinstance(expr, ast.Name):
        return expr.id
    if isinstance(expr, ast.Attribute):
        return expr.attr
    if isinstance(expr, ast.Call):
        # traced_node("x", "agent")(node_fn)  →  Call(func=Call(...), args=[Name(node_fn)])
        if expr.args:
            return _extract_fn_name(expr.args[-1])
        return _extract_fn_name(expr.func)
    return None


# ---------------------------------------------------------------------------
# Emitter — produces the agent.py text
# ---------------------------------------------------------------------------


def render_agent_py(extract: AgentExtract) -> str:
    """Render the new ``agent.py`` source."""
    agent_name = extract.agent_name
    class_name = _pascal(agent_name) + "Agent"
    graph = extract.graph
    runner = extract.runner

    state_model = graph.state_model or runner.state_model or "object"
    toolkit_class = runner.toolkit_class or f"{_pascal(agent_name)}Toolkit"

    # Deduplicate + order node function imports.
    fn_names: list[str] = []
    seen: set[str] = set()
    for name in graph.node_names:
        fn = graph.node_fn_refs.get(name)
        if fn and fn not in seen:
            seen.add(fn)
            fn_names.append(fn)

    nodes_dict_lines: list[str] = []
    for name in graph.node_names:
        fn = graph.node_fn_refs.get(name)
        if fn is None:
            nodes_dict_lines.append(f'        # TODO: resolve node fn for "{name}"')
        else:
            nodes_dict_lines.append(f'        "{name}": {fn},')
    nodes_block = "\n".join(nodes_dict_lines)

    edges_lines: list[str] = []
    for src, tgt in graph.edges:
        target = "END" if tgt == "__END__" else f'"{tgt}"'
        edges_lines.append(f'        edge("{src}", {target}),')
    for src, pred in graph.conditional_edges:
        # Split the TODO across two lines to stay under the 100-col limit.
        edges_lines.append(f'        # TODO: conditional edge from "{src}"')
        edges_lines.append(f"        #   routed by {pred}() — wrap with cond(...)")
    if not edges_lines:
        edges_lines.append("        # TODO: no edges extracted")
    edges_block = "\n".join(edges_lines)

    fn_import = (
        f"from shieldops.agents.{agent_name}.nodes import (\n"
        + "".join(f"    {n},\n" for n in fn_names)
        + ")\n"
        if fn_names
        else f"from shieldops.agents.{agent_name} import nodes  # noqa: F401\n"
    )

    return (
        HEADER + f'"""Declarative ``Agent`` spec for the {agent_name} agent.\n\n'
        f"Generated by ``scripts/codemods/agent_runtime.py`` from the legacy\n"
        f"``runner.py`` + ``graph.py`` pair. See RFC #247.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "from shieldops.agents.runtime import END, Agent, edge\n"
        f"from shieldops.agents.{agent_name}.models import {state_model}\n"
        f"from shieldops.agents.{agent_name}.tools import {toolkit_class}\n"
        f"{fn_import}"
        "\n\n"
        f"class {class_name}(Agent):\n"
        f'    """Declarative spec for ``{agent_name}`` — mounted by AgentRuntime."""\n\n'
        f"    {MARKER} = True\n\n"
        f'    name = "{agent_name}"\n'
        f"    state_model = {state_model}\n"
        f"    toolkit_factory = {toolkit_class}\n\n"
        "    nodes = {\n"
        f"{nodes_block}\n"
        "    }\n\n"
        "    edges = [\n"
        f"{edges_block}\n"
        "    ]\n\n"
        f'    entry = "{graph.entry_point}"\n'
    )


def _pascal(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_") if part)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def _already_migrated(agent_dir: Path) -> bool:
    agent_py = agent_dir / "agent.py"
    if not agent_py.exists():
        return False
    try:
        return MARKER in agent_py.read_text()
    except OSError:
        return False


def process_agent(agent_dir: Path, apply: bool) -> tuple[str, str]:
    """Return (bucket, detail).

    Buckets: ``migrated``, ``skipped_already_migrated``, ``skipped_shape``.
    """
    if _already_migrated(agent_dir):
        return "skipped_already_migrated", "marker_present"
    if (agent_dir / "agent.py").exists():
        return "skipped_already_migrated", "agent_py_exists"

    runner_path = agent_dir / "runner.py"
    graph_path = agent_dir / "graph.py"
    if not runner_path.exists():
        return "skipped_shape", "no_runner"
    if not graph_path.exists():
        return "skipped_shape", "no_graph"

    runner_spec, rreason = parse_runner(runner_path)
    if runner_spec is None:
        return "skipped_shape", rreason

    graph_spec, greason = parse_graph(graph_path)
    if graph_spec is None:
        return "skipped_shape", greason

    extract = AgentExtract(
        dir_path=agent_dir,
        agent_name=agent_dir.name,
        runner=runner_spec,
        graph=graph_spec,
    )
    rendered = render_agent_py(extract)

    if apply:
        (agent_dir / "agent.py").write_text(rendered)

    return "migrated", "ok"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write agent.py files. Default is dry-run (report only).",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_AGENTS,
        help="Path to the agents/ directory (default: src/shieldops/agents/)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Max number of agents to migrate in this run (for batching).",
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        help="Agent directory names to skip (repeatable).",
    )
    args = parser.parse_args(argv)
    exclude: set[str] = set(args.exclude or [])

    counts = {"migrated": 0, "skipped_already_migrated": 0, "skipped_shape": 0}
    samples: dict[str, list[str]] = {k: [] for k in counts}
    skip_reasons: dict[str, int] = {}

    agent_dirs = sorted(p for p in args.root.iterdir() if p.is_dir() and not p.name.startswith("_"))
    migrated_written = 0
    for agent_dir in agent_dirs:
        # Only process agents that look like individual agents
        # (skip runtime/, tracing/, etc. that are support packages).
        if not ((agent_dir / "runner.py").exists() or (agent_dir / "graph.py").exists()):
            continue
        if agent_dir.name in exclude:
            continue
        # Decide what would happen without writing first.
        limit_hit = args.limit is not None and migrated_written >= args.limit
        should_write = args.apply and not limit_hit
        bucket, detail = process_agent(agent_dir, apply=should_write)
        if bucket == "migrated" and should_write:
            migrated_written += 1
        counts[bucket] += 1
        if bucket == "skipped_shape":
            skip_reasons[detail] = skip_reasons.get(detail, 0) + 1
        if len(samples[bucket]) < 3:
            samples[bucket].append(f"{agent_dir.name} [{detail}]")

    total = sum(counts.values())
    print(
        json.dumps(
            {
                "mode": "apply" if args.apply else "dry-run",
                "total_agents": total,
                **counts,
                "samples": samples,
                "skip_reasons": skip_reasons,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
