"""RFC #241 PR-4 codemod — migrate ``EnginesConfig`` fields to ``FlatSettings``.

This script is the **checked-in** source of truth for the engines-branch
expansion of :class:`shieldops.config.flat.FlatSettings`. RFC #241 PR-4
(GH #252) adds all 1,812 engine fields from
``src/shieldops/config/sub/engines.py`` into the flat BaseSettings class,
replacing the legacy ``_FLAT_TO_NESTED`` routing through the nested
``EnginesConfig``.

Why a codemod instead of hand-editing?
--------------------------------------
``engines.py`` is hand-maintained today — engineers append new fields
when they ship a new engine toggle. A hand-maintained parallel list in
``flat.py`` would drift within a week. This script is the automation
that keeps the two in sync: re-run it after any change to
``sub/engines.py`` and the new fields land in ``flat.py`` automatically.

The script uses :mod:`ast` to parse ``sub/engines.py`` and walks the
``EnginesConfig`` class body for ``AnnAssign`` nodes (``field: type =
default``). It emits:

1. A block of flat field declarations, ready to paste into
   ``FlatSettings``. Each line has a proper type annotation and the
   exact default value from ``engines.py``.
2. A sampled list of ~20 ``(field, override)`` tuples for the parity
   test (``tests/unit/config/test_flat_settings.py::PARITY_FIELDS``).
   Sampling is deterministic (every Nth field) so the output is
   reproducible across runs.

Usage
-----
::

    # Preview the generated blocks without touching any files:
    python3 scripts/codemods/gen_engines_flat_fields.py --dry-run

    # Apply: append the generated field block to FlatSettings and the
    # sampled parity entries to the test PARITY_FIELDS list.
    python3 scripts/codemods/gen_engines_flat_fields.py --apply

The script is idempotent: re-running with ``--apply`` inserts between
well-known ``# --- engines (generated) ---`` / ``# --- end engines
(generated) ---`` marker comments, so a second run replaces the block
rather than duplicating it.

Safety
------
- Does not delete anything from ``sub/engines.py``. PR-5 deletes the
  nested module after all callers are migrated.
- Does not touch the ``settings`` singleton or ``_FLAT_TO_NESTED``.
  The legacy routing continues to work.
- Fields only contain the 5 primitive types present in ``engines.py``
  today: ``bool``, ``float``, ``int``, ``str``, ``list[str]``. Any
  other type annotation trips an assertion and aborts the run — fix
  the script rather than silently generate a broken flat.py.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ENGINES_PATH = REPO_ROOT / "src" / "shieldops" / "config" / "sub" / "engines.py"
FLAT_PATH = REPO_ROOT / "src" / "shieldops" / "config" / "flat.py"
PARITY_TEST_PATH = REPO_ROOT / "tests" / "unit" / "config" / "test_flat_settings.py"

# Marker comments delimit the auto-generated region. The codemod
# replaces everything between them on every `--apply` run, so it stays
# idempotent. Never hand-edit between these markers.
FLAT_BEGIN = "    # --- engines (generated by scripts/codemods/gen_engines_flat_fields.py) ---"
FLAT_END = "    # --- end engines (generated) ---"

PARITY_BEGIN = (
    "    # --- engines sampled (generated by scripts/codemods/gen_engines_flat_fields.py) ---"
)
PARITY_END = "    # --- end engines sampled (generated) ---"

# Number of engines fields to include in the sampled PARITY_FIELDS list.
# The sampler picks every (N/sample_count)-th field deterministically.
SAMPLE_COUNT = 20

# Only these type annotations are understood. Adding a new primitive
# type to engines.py requires extending this set and adding an override
# generator in ``_override_for_type``.
ALLOWED_TYPES = {"bool", "float", "int", "str", "list[str]"}


def _ann_to_source(node: ast.expr) -> str:
    """Serialize an AST annotation back to source (e.g. ``list[str]``)."""
    return ast.unparse(node)


def _default_to_source(node: ast.expr) -> str:
    """Serialize an AST default expression back to source."""
    return ast.unparse(node)


def _extract_fields(engines_source: str) -> list[tuple[str, str, str]]:
    """Return ``[(name, type_str, default_str), ...]`` for every field.

    The input is the full source of ``sub/engines.py``. We walk every
    class body (there is only one, ``EnginesConfig``, but we tolerate
    refactors) and collect ``AnnAssign`` nodes whose target is a plain
    ``Name``.
    """
    tree = ast.parse(engines_source)
    out: list[tuple[str, str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if not isinstance(stmt, ast.AnnAssign):
                continue
            if not isinstance(stmt.target, ast.Name):
                continue
            if stmt.value is None:
                # No default — skip, but all engines fields have defaults.
                continue
            name = stmt.target.id
            type_str = _ann_to_source(stmt.annotation)
            default_str = _default_to_source(stmt.value)
            assert type_str in ALLOWED_TYPES, (
                f"Unknown type on {name}: {type_str!r}. "
                f"Extend ALLOWED_TYPES and _override_for_type in the codemod."
            )
            out.append((name, type_str, default_str))
    return out


def _render_flat_block(fields: list[tuple[str, str, str]]) -> str:
    """Render the flat field declarations between the marker comments."""
    lines = [FLAT_BEGIN]
    for name, type_str, default_str in fields:
        lines.append(f"    {name}: {type_str} = {default_str}")
    lines.append(FLAT_END)
    return "\n".join(lines) + "\n"


def _override_for_type(field: str, type_str: str) -> str:
    """Return a string literal override the parity test uses for this field.

    Every override is stringified (matching existing PARITY_FIELDS
    convention where env vars are strings and ``str(value).lower()`` is
    compared) and chosen to be obviously-different from any plausible
    default, so the env-set test exercises the binding path.
    """
    if type_str == "bool":
        return '"false"'
    if type_str == "int":
        return '"42"'
    if type_str == "float":
        return '"0.42"'
    if type_str == "list[str]":
        return '"override-a,override-b"'
    # str
    return f'"override-{field}"'


def _render_parity_block(fields: list[tuple[str, str, str]]) -> str:
    """Pick ~SAMPLE_COUNT evenly-spaced fields and render PARITY_FIELDS entries.

    We sample deterministically (every ``len/SAMPLE_COUNT``-th field)
    so re-running the codemod yields the same parity entries. Including
    all 1,812 fields in the literal list would balloon the test file
    without meaningfully improving coverage — the same binding
    machinery handles every field, so a sampled sentinel set is
    sufficient.
    """
    if not fields:
        return PARITY_BEGIN + "\n" + PARITY_END + "\n"
    step = max(1, len(fields) // SAMPLE_COUNT)
    picked = fields[::step][:SAMPLE_COUNT]
    lines = [PARITY_BEGIN]
    for name, type_str, _default in picked:
        override = _override_for_type(name, type_str)
        lines.append(f"    ({name!r}, {override}),")
    lines.append(PARITY_END)
    return "\n".join(lines) + "\n"


def _splice(source: str, begin_marker: str, end_marker: str, new_block: str) -> str:
    """Replace or insert ``new_block`` between the two marker lines.

    If the markers are already present, replace the region. If not,
    the caller is responsible for picking an insertion point and
    calling this with a pre-scaffolded source.
    """
    begin_idx = source.find(begin_marker)
    end_idx = source.find(end_marker)
    if begin_idx == -1 or end_idx == -1 or end_idx < begin_idx:
        raise RuntimeError(
            f"Markers not found in target file. Expected:\n  {begin_marker}\n  {end_marker}"
        )
    end_line_end = source.find("\n", end_idx)
    if end_line_end == -1:
        end_line_end = len(source)
    return source[:begin_idx] + new_block.rstrip("\n") + source[end_line_end:]


def _ensure_flat_markers(flat_source: str) -> str:
    """Scaffold the marker region inside FlatSettings on first run.

    We insert the markers just before the closing of the
    ``FlatSettings`` class body, which we detect as the first blank
    line that follows the class's last existing field block. The
    cheap-but-robust heuristic is to find the line
    ``# ---------------------------------------------------------------------------``
    that precedes ``DictSource`` and insert markers just before it.
    """
    if FLAT_BEGIN in flat_source and FLAT_END in flat_source:
        return flat_source
    anchor = "# ---------------------------------------------------------------------------\n# DictSource"
    idx = flat_source.find(anchor)
    if idx == -1:
        raise RuntimeError("Could not find DictSource anchor in flat.py")
    prefix = flat_source[:idx]
    suffix = flat_source[idx:]
    scaffold = f"\n{FLAT_BEGIN}\n{FLAT_END}\n\n\n"
    return prefix + scaffold + suffix


def _ensure_parity_markers(test_source: str) -> str:
    """Scaffold the marker region inside PARITY_FIELDS on first run."""
    if PARITY_BEGIN in test_source and PARITY_END in test_source:
        return test_source
    # Insert the marker region just before the closing ``]`` of the
    # PARITY_FIELDS list literal. We look for the first standalone
    # ``]`` line that follows the ``PARITY_FIELDS: list[...] = [``
    # declaration.
    decl = "PARITY_FIELDS: list[tuple[str, Any]] = ["
    decl_idx = test_source.find(decl)
    if decl_idx == -1:
        raise RuntimeError("Could not find PARITY_FIELDS declaration")
    close_idx = test_source.find("\n]\n", decl_idx)
    if close_idx == -1:
        raise RuntimeError("Could not find PARITY_FIELDS closing ']'")
    # Insert scaffold between the last entry line and the closing ']'.
    insert_at = close_idx + 1  # keep the preceding newline
    scaffold = f"{PARITY_BEGIN}\n{PARITY_END}\n"
    return test_source[:insert_at] + scaffold + test_source[insert_at:]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate FlatSettings engines fields from sub/engines.py (RFC #241 PR-4)."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated blocks to stdout without touching any file.",
    )
    mode.add_argument(
        "--apply",
        action="store_true",
        help="Write generated blocks into flat.py and test_flat_settings.py.",
    )
    args = parser.parse_args()

    engines_source = ENGINES_PATH.read_text()
    fields = _extract_fields(engines_source)
    print(f"[gen_engines_flat_fields] parsed {len(fields)} fields from {ENGINES_PATH.name}")

    flat_block = _render_flat_block(fields)
    parity_block = _render_parity_block(fields)

    if args.dry_run:
        print("\n===== FLAT BLOCK =====\n")
        print(flat_block)
        print("\n===== PARITY BLOCK =====\n")
        print(parity_block)
        return 0

    # --- apply ---
    flat_source = FLAT_PATH.read_text()
    flat_source = _ensure_flat_markers(flat_source)
    flat_source = _splice(flat_source, FLAT_BEGIN, FLAT_END, flat_block)
    FLAT_PATH.write_text(flat_source)
    print(f"[gen_engines_flat_fields] wrote {len(fields)} fields → {FLAT_PATH}")

    test_source = PARITY_TEST_PATH.read_text()
    test_source = _ensure_parity_markers(test_source)
    test_source = _splice(test_source, PARITY_BEGIN, PARITY_END, parity_block)
    PARITY_TEST_PATH.write_text(test_source)
    print(f"[gen_engines_flat_fields] wrote sampled PARITY entries → {PARITY_TEST_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
