# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the otel_tail_sampling agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.otel_tail_sampling.models import OTelTailSamplingState
from shieldops.agents.otel_tail_sampling.nodes import (
    analyze_traces,
    apply_policies,
    design_policies,
    simulate_impact,
)
from shieldops.agents.otel_tail_sampling.tools import OTelTailSamplingToolkit
from shieldops.agents.runtime import END, Agent, edge


class OtelTailSamplingAgent(Agent):
    """Declarative spec for ``otel_tail_sampling`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "otel_tail_sampling"
    state_model = OTelTailSamplingState
    toolkit_factory = OTelTailSamplingToolkit

    nodes = {
        "analyze": analyze_traces,
        "design": design_policies,
        "simulate": simulate_impact,
        "apply": apply_policies,
    }

    edges = [
        edge("analyze", "design"),
        edge("design", "simulate"),
        edge("apply", END),
        # TODO: conditional edge from "simulate"
        #   routed by _should_apply() — wrap with cond(...)
    ]

    entry = "analyze"
