# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the on_call_optimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.on_call_optimizer.models import OnCallOptimizerState
from shieldops.agents.on_call_optimizer.nodes import (
    analyze_schedules,
    detect_burnout,
    evaluate_load,
    optimize_rotation,
    recommend_changes,
    report,
)
from shieldops.agents.on_call_optimizer.tools import OnCallOptimizerToolkit
from shieldops.agents.runtime import END, Agent, edge


class OnCallOptimizerAgent(Agent):
    """Declarative spec for ``on_call_optimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "on_call_optimizer"
    state_model = OnCallOptimizerState
    toolkit_factory = OnCallOptimizerToolkit

    nodes = {
        "analyze_schedules": analyze_schedules,
        "evaluate_load": evaluate_load,
        "detect_burnout": detect_burnout,
        "optimize_rotation": optimize_rotation,
        "recommend_changes": recommend_changes,
        "report": report,
    }

    edges = [
        edge("analyze_schedules", "evaluate_load"),
        edge("evaluate_load", "detect_burnout"),
        edge("detect_burnout", "optimize_rotation"),
        edge("optimize_rotation", "recommend_changes"),
        edge("recommend_changes", "report"),
        edge("report", END),
    ]

    entry = "analyze_schedules"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``OnCallOptimizerRunner`` keep working via this alias; new code
# should use ``OnCallOptimizerAgent`` directly through AgentRuntime.
OnCallOptimizerRunner = OnCallOptimizerAgent
