# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_feed_aggregator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_feed_aggregator.models import ThreatFeedAggregatorState
from shieldops.agents.threat_feed_aggregator.nodes import (
    collect_feeds,
    correlate_threats,
    distribute_intel,
    enrich_context,
    generate_report,
    normalize_iocs,
)
from shieldops.agents.threat_feed_aggregator.tools import ThreatFeedAggregatorToolkit


class ThreatFeedAggregatorAgent(Agent):
    """Declarative spec for ``threat_feed_aggregator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_feed_aggregator"
    state_model = ThreatFeedAggregatorState
    toolkit_factory = ThreatFeedAggregatorToolkit

    nodes = {
        "collect_feeds": collect_feeds,
        "normalize_iocs": normalize_iocs,
        "correlate_threats": correlate_threats,
        "enrich_context": enrich_context,
        "distribute_intel": distribute_intel,
        "report": generate_report,
    }

    edges = [
        edge("collect_feeds", "normalize_iocs"),
        edge("normalize_iocs", "correlate_threats"),
        edge("correlate_threats", "enrich_context"),
        edge("enrich_context", "distribute_intel"),
        edge("distribute_intel", "report"),
        edge("report", END),
    ]

    entry = "collect_feeds"
