# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the key_lifecycle_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.key_lifecycle_manager.models import KeyLifecycleManagerState
from shieldops.agents.key_lifecycle_manager.nodes import (
    assess_compliance,
    audit_ceremonies,
    check_rotation,
    discover_keys,
    report,
    track_escrow,
)
from shieldops.agents.key_lifecycle_manager.tools import KeyLifecycleManagerToolkit
from shieldops.agents.runtime import END, Agent, edge


class KeyLifecycleManagerAgent(Agent):
    """Declarative spec for ``key_lifecycle_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "key_lifecycle_manager"
    state_model = KeyLifecycleManagerState
    toolkit_factory = KeyLifecycleManagerToolkit

    nodes = {
        "discover_keys": discover_keys,
        "audit_ceremonies": audit_ceremonies,
        "check_rotation": check_rotation,
        "assess_compliance": assess_compliance,
        "track_escrow": track_escrow,
        "report": report,
    }

    edges = [
        edge("track_escrow", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_keys" via _check_error()
        # TODO: cond(...) from "audit_ceremonies" via _check_error()
        # TODO: cond(...) from "check_rotation" via _check_error()
        # TODO: cond(...) from "assess_compliance" via _check_error()
    ]

    entry = "discover_keys"
