# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the attack_replay_simulator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.attack_replay_simulator.models import AttackReplaySimulatorState
from shieldops.agents.attack_replay_simulator.nodes import (
    capture_telemetry,
    configure_sandbox,
    evaluate_detection,
    execute_replay,
    generate_report,
    select_techniques,
)
from shieldops.agents.attack_replay_simulator.tools import AttackReplaySimulatorToolkit
from shieldops.agents.runtime import END, Agent, edge


class AttackReplaySimulatorAgent(Agent):
    """Declarative spec for ``attack_replay_simulator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "attack_replay_simulator"
    state_model = AttackReplaySimulatorState
    toolkit_factory = AttackReplaySimulatorToolkit

    nodes = {
        "select_techniques": select_techniques,
        "configure_sandbox": configure_sandbox,
        "execute_replay": execute_replay,
        "capture_telemetry": capture_telemetry,
        "evaluate_detection": evaluate_detection,
        "generate_report": generate_report,
    }

    edges = [
        edge("evaluate_detection", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "select_techniques" via _check_error()
        # TODO: cond(...) from "configure_sandbox" via _check_error()
        # TODO: cond(...) from "execute_replay" via _check_error()
        # TODO: cond(...) from "capture_telemetry" via _check_error()
    ]

    entry = "select_techniques"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AttackReplaySimulatorRunner`` keep working via this alias; new code
# should use ``AttackReplaySimulatorAgent`` directly through AgentRuntime.
AttackReplaySimulatorRunner = AttackReplaySimulatorAgent
