# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the mfa_bypass_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.mfa_bypass_detector.models import MFABypassDetectorState
from shieldops.agents.mfa_bypass_detector.nodes import (
    analyze_patterns,
    apply_remediation,
    assess_risk,
    collect_auth_events,
    detect_mfa_bypass,
    generate_report,
)
from shieldops.agents.mfa_bypass_detector.tools import MFABypassDetectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class MfaBypassDetectorAgent(Agent):
    """Declarative spec for ``mfa_bypass_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "mfa_bypass_detector"
    state_model = MFABypassDetectorState
    toolkit_factory = MFABypassDetectorToolkit

    nodes = {
        "collect_auth_events": collect_auth_events,
        "analyze_patterns": analyze_patterns,
        "detect_bypass": detect_mfa_bypass,
        "assess_risk": assess_risk,
        "remediate": apply_remediation,
        "report": generate_report,
    }

    edges = [
        edge("collect_auth_events", "analyze_patterns"),
        edge("analyze_patterns", "detect_bypass"),
        edge("detect_bypass", "assess_risk"),
        edge("assess_risk", "remediate"),
        edge("remediate", "report"),
        edge("report", END),
    ]

    entry = "collect_auth_events"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``MFABypassDetectorRunner`` keep working via this alias; new code
# should use ``MfaBypassDetectorAgent`` directly through AgentRuntime.
MFABypassDetectorRunner = MfaBypassDetectorAgent
