# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the model_drift_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.model_drift_detector.models import ModelDriftDetectorState
from shieldops.agents.model_drift_detector.nodes import (
    analyze_concept_drift,
    analyze_data_drift,
    analyze_prediction_drift,
    collect,
    complete,
    evaluate_thresholds,
    failed,
    report,
)
from shieldops.agents.model_drift_detector.tools import ModelDriftDetectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class ModelDriftDetectorAgent(Agent):
    """Declarative spec for ``model_drift_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "model_drift_detector"
    state_model = ModelDriftDetectorState
    toolkit_factory = ModelDriftDetectorToolkit

    nodes = {
        "collect": collect,
        "analyze_data_drift": analyze_data_drift,
        "analyze_concept_drift": analyze_concept_drift,
        "analyze_prediction_drift": analyze_prediction_drift,
        "evaluate_thresholds": evaluate_thresholds,
        "report": report,
        "complete": complete,
        "failed": failed,
    }

    edges = [
        edge("evaluate_thresholds", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect" via _check_error()
        # TODO: cond(...) from "analyze_data_drift" via _check_error()
        # TODO: cond(...) from "analyze_concept_drift" via _check_error()
        # TODO: cond(...) from "analyze_prediction_drift" via _check_error()
        # TODO: cond(...) from "report" via _check_error()
        # TODO: cond(...) from "complete" via _check_error()
    ]

    entry = "collect"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ModelDriftDetectorRunner`` keep working via this alias; new code
# should use ``ModelDriftDetectorAgent`` directly through AgentRuntime.
ModelDriftDetectorRunner = ModelDriftDetectorAgent
