# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_intelligence_platform agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_intelligence_platform.models import ThreatIntelligencePlatformState
from shieldops.agents.threat_intelligence_platform.nodes import (
    assess_relevance,
    collect_intelligence,
    correlate_threats,
    generate_advisories,
    normalize_indicators,
    report,
)
from shieldops.agents.threat_intelligence_platform.tools import ThreatIntelligencePlatformToolkit


class ThreatIntelligencePlatformAgent(Agent):
    """Declarative spec for ``threat_intelligence_platform`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_intelligence_platform"
    state_model = ThreatIntelligencePlatformState
    toolkit_factory = ThreatIntelligencePlatformToolkit

    nodes = {
        "collect_intelligence": collect_intelligence,
        "normalize_indicators": normalize_indicators,
        "correlate_threats": correlate_threats,
        "assess_relevance": assess_relevance,
        "generate_advisories": generate_advisories,
        "report": report,
    }

    edges = [
        edge("collect_intelligence", "normalize_indicators"),
        edge("normalize_indicators", "correlate_threats"),
        edge("correlate_threats", "assess_relevance"),
        edge("generate_advisories", "report"),
        edge("report", END),
        # TODO: conditional edge from "assess_relevance"
        #   routed by should_generate_advisories() — wrap with cond(...)
    ]

    entry = "collect_intelligence"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ThreatIntelligencePlatformRunner`` keep working via this alias; new code
# should use ``ThreatIntelligencePlatformAgent`` directly through AgentRuntime.
ThreatIntelligencePlatformRunner = ThreatIntelligencePlatformAgent
