# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_metrics_collector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_metrics_collector.models import SecurityMetricsCollectorState
from shieldops.agents.security_metrics_collector.nodes import (
    benchmark_performance,
    calculate_kpis,
    collect_data,
    define_metrics,
    generate_dashboard,
    report,
)
from shieldops.agents.security_metrics_collector.tools import SecurityMetricsCollectorToolkit


class SecurityMetricsCollectorAgent(Agent):
    """Declarative spec for ``security_metrics_collector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_metrics_collector"
    state_model = SecurityMetricsCollectorState
    toolkit_factory = SecurityMetricsCollectorToolkit

    nodes = {
        "define_metrics": define_metrics,
        "collect_data": collect_data,
        "calculate_kpis": calculate_kpis,
        "benchmark_performance": benchmark_performance,
        "generate_dashboard": generate_dashboard,
        "report": report,
    }

    edges = [
        edge("generate_dashboard", "report"),
        edge("report", END),
        # TODO: cond(...) from "define_metrics" via _check_error()
        # TODO: cond(...) from "collect_data" via _check_error()
        # TODO: cond(...) from "calculate_kpis" via _check_error()
        # TODO: cond(...) from "benchmark_performance" via _check_error()
    ]

    entry = "define_metrics"
