# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the scada_security_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.scada_security_analyzer.models import SCADASecurityAnalyzerState
from shieldops.agents.scada_security_analyzer.nodes import (
    analyze_traffic,
    assess_risk,
    check_firmware,
    detect_anomalies,
    discover_assets,
    report,
)
from shieldops.agents.scada_security_analyzer.tools import SCADASecurityAnalyzerToolkit


class ScadaSecurityAnalyzerAgent(Agent):
    """Declarative spec for ``scada_security_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "scada_security_analyzer"
    state_model = SCADASecurityAnalyzerState
    toolkit_factory = SCADASecurityAnalyzerToolkit

    nodes = {
        "discover_assets": discover_assets,
        "analyze_traffic": analyze_traffic,
        "detect_anomalies": detect_anomalies,
        "check_firmware": check_firmware,
        "assess_risk": assess_risk,
        "report": report,
    }

    edges = [
        edge("assess_risk", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_assets" via _check_error()
        # TODO: cond(...) from "analyze_traffic" via _check_error()
        # TODO: cond(...) from "detect_anomalies" via _check_error()
        # TODO: cond(...) from "check_firmware" via _check_error()
    ]

    entry = "discover_assets"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SCADASecurityAnalyzerRunner`` keep working via this alias; new code
# should use ``ScadaSecurityAnalyzerAgent`` directly through AgentRuntime.
SCADASecurityAnalyzerRunner = ScadaSecurityAnalyzerAgent
