# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_billing_protector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_billing_protector.models import CloudBillingProtectorState
from shieldops.agents.cloud_billing_protector.nodes import (
    analyze_patterns,
    classify_fraud,
    collect_billing,
    detect_anomalies,
    enforce_limits,
    generate_report,
)
from shieldops.agents.cloud_billing_protector.tools import CloudBillingProtectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudBillingProtectorAgent(Agent):
    """Declarative spec for ``cloud_billing_protector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_billing_protector"
    state_model = CloudBillingProtectorState
    toolkit_factory = CloudBillingProtectorToolkit

    nodes = {
        "collect_billing": collect_billing,
        "analyze_patterns": analyze_patterns,
        "detect_anomalies": detect_anomalies,
        "classify_fraud": classify_fraud,
        "enforce_limits": enforce_limits,
        "report": generate_report,
    }

    edges = [
        edge("collect_billing", "analyze_patterns"),
        edge("analyze_patterns", "detect_anomalies"),
        edge("detect_anomalies", "classify_fraud"),
        edge("classify_fraud", "enforce_limits"),
        edge("enforce_limits", "report"),
        edge("report", END),
    ]

    entry = "collect_billing"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CloudBillingProtectorRunner`` keep working via this alias; new code
# should use ``CloudBillingProtectorAgent`` directly through AgentRuntime.
CloudBillingProtectorRunner = CloudBillingProtectorAgent
