# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the runbook_automation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runbook_automation.models import RunbookAutomationState
from shieldops.agents.runbook_automation.nodes import (
    execute_steps,
    report,
    request_approval,
    select_runbook,
    validate_preconditions,
    verify_outcome,
)
from shieldops.agents.runbook_automation.tools import RunbookAutomationToolkit
from shieldops.agents.runtime import END, Agent, edge


class RunbookAutomationAgent(Agent):
    """Declarative spec for ``runbook_automation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "runbook_automation"
    state_model = RunbookAutomationState
    toolkit_factory = RunbookAutomationToolkit

    nodes = {
        "select_runbook": select_runbook,
        "validate_preconditions": validate_preconditions,
        "request_approval": request_approval,
        "execute_steps": execute_steps,
        "verify_outcome": verify_outcome,
        "report": report,
    }

    edges = [
        edge("verify_outcome", "report"),
        edge("report", END),
        # TODO: cond(...) from "select_runbook" via _route_after_select()
        # TODO: cond(...) from "validate_preconditions" via _route_after_validate()
        # TODO: cond(...) from "request_approval" via _route_after_approve()
        # TODO: cond(...) from "execute_steps" via _route_after_execute()
    ]

    entry = "select_runbook"
