# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the privacy_impact_assessor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.privacy_impact_assessor.models import PrivacyImpactAssessorState
from shieldops.agents.privacy_impact_assessor.nodes import (
    assess_risks,
    document,
    identify_mitigations,
    identify_processing,
    map_data_flows,
    report,
)
from shieldops.agents.privacy_impact_assessor.tools import PrivacyImpactAssessorToolkit
from shieldops.agents.runtime import END, Agent, edge


class PrivacyImpactAssessorAgent(Agent):
    """Declarative spec for ``privacy_impact_assessor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "privacy_impact_assessor"
    state_model = PrivacyImpactAssessorState
    toolkit_factory = PrivacyImpactAssessorToolkit

    nodes = {
        "identify_processing": identify_processing,
        "map_data_flows": map_data_flows,
        "assess_risks": assess_risks,
        "identify_mitigations": identify_mitigations,
        "document": document,
        "report": report,
    }

    edges = [
        edge("document", "report"),
        edge("report", END),
        # TODO: cond(...) from "identify_processing" via _check_error()
        # TODO: cond(...) from "map_data_flows" via _check_error()
        # TODO: cond(...) from "assess_risks" via _check_error()
        # TODO: cond(...) from "identify_mitigations" via _check_error()
    ]

    entry = "identify_processing"
