# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_workload_inspector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_workload_inspector.models import CloudWorkloadInspectorState
from shieldops.agents.cloud_workload_inspector.nodes import (
    analyze_config,
    assess_risk,
    check_compliance,
    discover_workloads,
    generate_report,
    recommend,
)
from shieldops.agents.cloud_workload_inspector.tools import CloudWorkloadInspectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudWorkloadInspectorAgent(Agent):
    """Declarative spec for ``cloud_workload_inspector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_workload_inspector"
    state_model = CloudWorkloadInspectorState
    toolkit_factory = CloudWorkloadInspectorToolkit

    nodes = {
        "discover_workloads": discover_workloads,
        "analyze_config": analyze_config,
        "check_compliance": check_compliance,
        "assess_risk": assess_risk,
        "recommend": recommend,
        "generate_report": generate_report,
    }

    edges = [
        edge("analyze_config", "check_compliance"),
        edge("assess_risk", "recommend"),
        edge("recommend", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "discover_workloads"
        #   routed by _should_analyze() — wrap with cond(...)
        # TODO: conditional edge from "check_compliance"
        #   routed by _should_assess_risk() — wrap with cond(...)
    ]

    entry = "discover_workloads"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CloudWorkloadInspectorRunner`` keep working via this alias; new code
# should use ``CloudWorkloadInspectorAgent`` directly through AgentRuntime.
CloudWorkloadInspectorRunner = CloudWorkloadInspectorAgent
