# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the incident_playbook_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.incident_playbook_engine.models import IncidentPlaybookEngineState
from shieldops.agents.incident_playbook_engine.nodes import (
    adapt_steps,
    classify_incident,
    execute_playbook,
    generate_report,
    select_playbook,
    validate_outcome,
)
from shieldops.agents.incident_playbook_engine.tools import IncidentPlaybookEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class IncidentPlaybookEngineAgent(Agent):
    """Declarative spec for ``incident_playbook_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "incident_playbook_engine"
    state_model = IncidentPlaybookEngineState
    toolkit_factory = IncidentPlaybookEngineToolkit

    nodes = {
        "classify_incident": classify_incident,
        "select_playbook": select_playbook,
        "adapt_steps": adapt_steps,
        "execute_playbook": execute_playbook,
        "validate_outcome": validate_outcome,
        "generate_report": generate_report,
    }

    edges = [
        edge("classify_incident", "select_playbook"),
        edge("select_playbook", "adapt_steps"),
        edge("adapt_steps", "execute_playbook"),
        edge("execute_playbook", "validate_outcome"),
        edge("validate_outcome", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "classify_incident"
