# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the backup_validator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.backup_validator.models import BackupValidatorState
from shieldops.agents.backup_validator.nodes import (
    assess_gaps,
    generate_report,
    inventory_backups,
    remediate,
    test_recovery,
    validate_integrity,
)
from shieldops.agents.backup_validator.tools import BackupValidatorToolkit
from shieldops.agents.runtime import END, Agent, edge


class BackupValidatorAgent(Agent):
    """Declarative spec for ``backup_validator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "backup_validator"
    state_model = BackupValidatorState
    toolkit_factory = BackupValidatorToolkit

    nodes = {
        "inventory_backups": inventory_backups,
        "validate_integrity": validate_integrity,
        "test_recovery": test_recovery,
        "assess_gaps": assess_gaps,
        "remediate": remediate,
        "report": generate_report,
    }

    edges = [
        edge("inventory_backups", "validate_integrity"),
        edge("validate_integrity", "test_recovery"),
        edge("test_recovery", "assess_gaps"),
        edge("assess_gaps", "remediate"),
        edge("remediate", "report"),
        edge("report", END),
    ]

    entry = "inventory_backups"
