# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the situation_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.situation_manager.models import SituationManagerState
from shieldops.agents.situation_manager.nodes import (
    aggregate_alerts,
    compose_narrative,
    generate_report,
    prioritize_situations,
    recommend_actions,
    track_outcomes,
)
from shieldops.agents.situation_manager.tools import SituationManagerToolkit


class SituationManagerAgent(Agent):
    """Declarative spec for ``situation_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "situation_manager"
    state_model = SituationManagerState
    toolkit_factory = SituationManagerToolkit

    nodes = {
        "aggregate_alerts": aggregate_alerts,
        "compose_narrative": compose_narrative,
        "prioritize_situations": prioritize_situations,
        "recommend_actions": recommend_actions,
        "track_outcomes": track_outcomes,
        "generate_report": generate_report,
    }

    edges = [
        edge("compose_narrative", "prioritize_situations"),
        edge("recommend_actions", "track_outcomes"),
        edge("track_outcomes", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "aggregate_alerts"
        #   routed by _has_aggregates() — wrap with cond(...)
        # TODO: conditional edge from "prioritize_situations"
        #   routed by _has_situations() — wrap with cond(...)
    ]

    entry = "aggregate_alerts"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SituationManagerRunner`` keep working via this alias; new code
# should use ``SituationManagerAgent`` directly through AgentRuntime.
SituationManagerRunner = SituationManagerAgent
