# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the otel_pipeline agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.otel_pipeline.models import OTelPipelineState
from shieldops.agents.otel_pipeline.nodes import (
    configure_pipeline,
    discover_pipeline,
    monitor_pipeline,
    validate_pipeline,
)
from shieldops.agents.otel_pipeline.tools import OTelPipelineToolkit
from shieldops.agents.runtime import END, Agent, edge


class OtelPipelineAgent(Agent):
    """Declarative spec for ``otel_pipeline`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "otel_pipeline"
    state_model = OTelPipelineState
    toolkit_factory = OTelPipelineToolkit

    nodes = {
        "discover": discover_pipeline,
        "configure": configure_pipeline,
        "validate": validate_pipeline,
        "monitor": monitor_pipeline,
    }

    edges = [
        edge("discover", "configure"),
        edge("configure", "validate"),
        edge("monitor", END),
        # TODO: conditional edge from "validate"
        #   routed by should_redeploy() — wrap with cond(...)
    ]

    entry = "discover"
