# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_simulation_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_simulation_engine.models import ThreatSimulationEngineState
from shieldops.agents.threat_simulation_engine.nodes import (
    deploy_attack,
    evaluate_response,
    generate_gaps,
    generate_report,
    monitor_detection,
    plan_scenario,
)
from shieldops.agents.threat_simulation_engine.tools import ThreatSimulationEngineToolkit


class ThreatSimulationEngineAgent(Agent):
    """Declarative spec for ``threat_simulation_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_simulation_engine"
    state_model = ThreatSimulationEngineState
    toolkit_factory = ThreatSimulationEngineToolkit

    nodes = {
        "plan_scenario": plan_scenario,
        "deploy_attack": deploy_attack,
        "monitor_detection": monitor_detection,
        "evaluate_response": evaluate_response,
        "generate_gaps": generate_gaps,
        "generate_report": generate_report,
    }

    edges = [
        edge("plan_scenario", "deploy_attack"),
        edge("deploy_attack", "monitor_detection"),
        edge("monitor_detection", "evaluate_response"),
        edge("generate_gaps", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "evaluate_response"
        #   routed by _should_generate_gaps() — wrap with cond(...)
    ]

    entry = "plan_scenario"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ThreatSimulationEngineRunner`` keep working via this alias; new code
# should use ``ThreatSimulationEngineAgent`` directly through AgentRuntime.
ThreatSimulationEngineRunner = ThreatSimulationEngineAgent
