# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the backup_integrity_verifier agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.backup_integrity_verifier.models import BackupIntegrityVerifierState
from shieldops.agents.backup_integrity_verifier.nodes import (
    assess_coverage,
    check_encryption,
    discover_backups,
    generate_report,
    test_restore,
    verify_integrity,
)
from shieldops.agents.backup_integrity_verifier.tools import BackupIntegrityVerifierToolkit
from shieldops.agents.runtime import END, Agent, edge


class BackupIntegrityVerifierAgent(Agent):
    """Declarative spec for ``backup_integrity_verifier`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "backup_integrity_verifier"
    state_model = BackupIntegrityVerifierState
    toolkit_factory = BackupIntegrityVerifierToolkit

    nodes = {
        "discover_backups": discover_backups,
        "verify_integrity": verify_integrity,
        "check_encryption": check_encryption,
        "test_restore": test_restore,
        "assess_coverage": assess_coverage,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_backups", "verify_integrity"),
        edge("verify_integrity", "check_encryption"),
        edge("test_restore", "assess_coverage"),
        edge("assess_coverage", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "check_encryption"
        #   routed by _should_test_restore() — wrap with cond(...)
    ]

    entry = "discover_backups"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``BackupIntegrityVerifierRunner`` keep working via this alias; new code
# should use ``BackupIntegrityVerifierAgent`` directly through AgentRuntime.
BackupIntegrityVerifierRunner = BackupIntegrityVerifierAgent
