# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_dashboard_aggregator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_dashboard_aggregator.models import SecurityDashboardAggregatorState
from shieldops.agents.security_dashboard_aggregator.nodes import (
    aggregate_by_domain,
    calculate_kpis,
    collect_agent_metrics,
    detect_anomalies,
    generate_dashboard,
    generate_report,
)
from shieldops.agents.security_dashboard_aggregator.tools import SecurityDashboardAggregatorToolkit


class SecurityDashboardAggregatorAgent(Agent):
    """Declarative spec for ``security_dashboard_aggregator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_dashboard_aggregator"
    state_model = SecurityDashboardAggregatorState
    toolkit_factory = SecurityDashboardAggregatorToolkit

    nodes = {
        "collect_agent_metrics": collect_agent_metrics,
        "aggregate_by_domain": aggregate_by_domain,
        "calculate_kpis": calculate_kpis,
        "detect_anomalies": detect_anomalies,
        "generate_dashboard": generate_dashboard,
        "generate_report": generate_report,
    }

    edges = [
        edge("aggregate_by_domain", "calculate_kpis"),
        edge("calculate_kpis", "detect_anomalies"),
        edge("detect_anomalies", "generate_dashboard"),
        edge("generate_dashboard", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "collect_agent_metrics"
        #   routed by _has_metrics() — wrap with cond(...)
    ]

    entry = "collect_agent_metrics"
