# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the mfa_compliance_checker agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.mfa_compliance_checker.models import MfaComplianceCheckerState
from shieldops.agents.mfa_compliance_checker.nodes import (
    check_mfa_status,
    classify_risk,
    discover_accounts,
    enforce_policy,
    report,
    report_gaps,
)
from shieldops.agents.mfa_compliance_checker.tools import MfaComplianceCheckerToolkit
from shieldops.agents.runtime import END, Agent, edge


class MfaComplianceCheckerAgent(Agent):
    """Declarative spec for ``mfa_compliance_checker`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "mfa_compliance_checker"
    state_model = MfaComplianceCheckerState
    toolkit_factory = MfaComplianceCheckerToolkit

    nodes = {
        "discover_accounts": discover_accounts,
        "check_mfa_status": check_mfa_status,
        "classify_risk": classify_risk,
        "enforce_policy": enforce_policy,
        "report_gaps": report_gaps,
        "report": report,
    }

    edges = [
        edge("report_gaps", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_accounts" via _check_error()
        # TODO: cond(...) from "check_mfa_status" via _check_error()
        # TODO: cond(...) from "classify_risk" via _check_error()
        # TODO: cond(...) from "enforce_policy" via _check_error()
    ]

    entry = "discover_accounts"
