# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the log_intelligence agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.log_intelligence.models import LogIntelligenceState
from shieldops.agents.log_intelligence.nodes import (
    correlate_threats,
    detect_patterns,
    generate_insights,
    generate_report,
    ingest_logs,
    parse_and_normalize,
)
from shieldops.agents.log_intelligence.tools import LogIntelligenceToolkit
from shieldops.agents.runtime import END, Agent, edge


class LogIntelligenceAgent(Agent):
    """Declarative spec for ``log_intelligence`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "log_intelligence"
    state_model = LogIntelligenceState
    toolkit_factory = LogIntelligenceToolkit

    nodes = {
        "ingest_logs": ingest_logs,
        "parse_and_normalize": parse_and_normalize,
        "detect_patterns": detect_patterns,
        "correlate_threats": correlate_threats,
        "generate_insights": generate_insights,
        "generate_report": generate_report,
    }

    edges = [
        edge("ingest_logs", "parse_and_normalize"),
        edge("parse_and_normalize", "detect_patterns"),
        edge("generate_insights", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_patterns"
        #   routed by should_correlate() — wrap with cond(...)
        # TODO: conditional edge from "correlate_threats"
        #   routed by should_generate_insights() — wrap with cond(...)
    ]

    entry = "ingest_logs"
