# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the stakeholder_notifier agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.stakeholder_notifier.models import StakeholderNotifierState
from shieldops.agents.stakeholder_notifier.nodes import (
    assess_impact,
    compose_message,
    deliver_notification,
    identify_stakeholders,
    report,
    select_channels,
)
from shieldops.agents.stakeholder_notifier.tools import StakeholderNotifierToolkit


class StakeholderNotifierAgent(Agent):
    """Declarative spec for ``stakeholder_notifier`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "stakeholder_notifier"
    state_model = StakeholderNotifierState
    toolkit_factory = StakeholderNotifierToolkit

    nodes = {
        "identify_stakeholders": identify_stakeholders,
        "assess_impact": assess_impact,
        "compose_message": compose_message,
        "select_channels": select_channels,
        "deliver_notification": deliver_notification,
        "report": report,
    }

    edges = [
        edge("identify_stakeholders", "assess_impact"),
        edge("assess_impact", "compose_message"),
        edge("compose_message", "select_channels"),
        edge("select_channels", "deliver_notification"),
        edge("deliver_notification", "report"),
        edge("report", END),
    ]

    entry = "identify_stakeholders"
