# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_threat_hunting agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_threat_hunting.models import DataThreatHuntingState
from shieldops.agents.data_threat_hunting.nodes import (
    analyze_indicators,
    collect_evidence,
    correlate_findings,
    generate_hypotheses,
    hunt_in_backups,
    report,
)
from shieldops.agents.data_threat_hunting.tools import DataThreatHuntingToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataThreatHuntingAgent(Agent):
    """Declarative spec for ``data_threat_hunting`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_threat_hunting"
    state_model = DataThreatHuntingState
    toolkit_factory = DataThreatHuntingToolkit

    nodes = {
        "generate_hypotheses": generate_hypotheses,
        "collect_evidence": collect_evidence,
        "analyze_indicators": analyze_indicators,
        "hunt_in_backups": hunt_in_backups,
        "correlate_findings": correlate_findings,
        "report": report,
    }

    edges = [
        edge("generate_hypotheses", "collect_evidence"),
        edge("collect_evidence", "analyze_indicators"),
        edge("hunt_in_backups", "correlate_findings"),
        edge("correlate_findings", "report"),
        edge("report", END),
        # TODO: conditional edge from "analyze_indicators"
        #   routed by should_hunt_backups() — wrap with cond(...)
    ]

    entry = "generate_hypotheses"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DataThreatHuntingRunner`` keep working via this alias; new code
# should use ``DataThreatHuntingAgent`` directly through AgentRuntime.
DataThreatHuntingRunner = DataThreatHuntingAgent
