# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the platform_intelligence agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.platform_intelligence.models import PlatformIntelligenceState
from shieldops.agents.platform_intelligence.nodes import (
    analyze_patterns,
    compute_insights,
    finalize_intelligence,
    gather_telemetry,
    generate_strategy,
)
from shieldops.agents.platform_intelligence.tools import PlatformIntelligenceToolkit
from shieldops.agents.runtime import END, Agent, edge


class PlatformIntelligenceAgent(Agent):
    """Declarative spec for ``platform_intelligence`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "platform_intelligence"
    state_model = PlatformIntelligenceState
    toolkit_factory = PlatformIntelligenceToolkit

    nodes = {
        "gather_telemetry": gather_telemetry,
        "analyze_patterns": analyze_patterns,
        "compute_insights": compute_insights,
        "generate_strategy": generate_strategy,
        "finalize_intelligence": finalize_intelligence,
    }

    edges = [
        edge("analyze_patterns", "compute_insights"),
        edge("compute_insights", "generate_strategy"),
        edge("generate_strategy", "finalize_intelligence"),
        edge("finalize_intelligence", END),
        # TODO: conditional edge from "gather_telemetry"
        #   routed by should_continue() — wrap with cond(...)
    ]

    entry = "gather_telemetry"
