# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_landscape_mapper agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_landscape_mapper.models import ThreatLandscapeMapperState
from shieldops.agents.threat_landscape_mapper.nodes import (
    assess_relevance,
    collect_intel,
    identify_trends,
    map_actors,
    prioritize,
    report,
)
from shieldops.agents.threat_landscape_mapper.tools import ThreatLandscapeMapperToolkit


class ThreatLandscapeMapperAgent(Agent):
    """Declarative spec for ``threat_landscape_mapper`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_landscape_mapper"
    state_model = ThreatLandscapeMapperState
    toolkit_factory = ThreatLandscapeMapperToolkit

    nodes = {
        "collect_intel": collect_intel,
        "map_actors": map_actors,
        "identify_trends": identify_trends,
        "assess_relevance": assess_relevance,
        "prioritize": prioritize,
        "report": report,
    }

    edges = [
        edge("prioritize", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_intel" via _check_error()
        # TODO: cond(...) from "map_actors" via _check_error()
        # TODO: cond(...) from "identify_trends" via _check_error()
        # TODO: cond(...) from "assess_relevance" via _check_error()
    ]

    entry = "collect_intel"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ThreatLandscapeMapperRunner`` keep working via this alias; new code
# should use ``ThreatLandscapeMapperAgent`` directly through AgentRuntime.
ThreatLandscapeMapperRunner = ThreatLandscapeMapperAgent
