# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the executive_reporter agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.executive_reporter.models import ExecutiveReporterState
from shieldops.agents.executive_reporter.nodes import (
    analyze_trends,
    collect_metrics,
    compose_report,
    generate_recommendations,
    generate_report,
    summarize_findings,
)
from shieldops.agents.executive_reporter.tools import ExecutiveReporterToolkit
from shieldops.agents.runtime import END, Agent, edge


class ExecutiveReporterAgent(Agent):
    """Declarative spec for ``executive_reporter`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "executive_reporter"
    state_model = ExecutiveReporterState
    toolkit_factory = ExecutiveReporterToolkit

    nodes = {
        "collect_metrics": collect_metrics,
        "analyze_trends": analyze_trends,
        "summarize_findings": summarize_findings,
        "generate_recommendations": generate_recommendations,
        "compose_report": compose_report,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_metrics", "analyze_trends"),
        edge("analyze_trends", "summarize_findings"),
        edge("summarize_findings", "generate_recommendations"),
        edge("generate_recommendations", "compose_report"),
        edge("compose_report", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "collect_metrics"
