# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the service_dependency_mapper agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.service_dependency_mapper.models import ServiceDependencyMapperState
from shieldops.agents.service_dependency_mapper.nodes import (
    assess_resilience,
    detect_cycles,
    discover_services,
    map_dependencies,
    report,
    trace_connections,
)
from shieldops.agents.service_dependency_mapper.tools import ServiceDependencyMapperToolkit


class ServiceDependencyMapperAgent(Agent):
    """Declarative spec for ``service_dependency_mapper`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "service_dependency_mapper"
    state_model = ServiceDependencyMapperState
    toolkit_factory = ServiceDependencyMapperToolkit

    nodes = {
        "discover_services": discover_services,
        "trace_connections": trace_connections,
        "map_dependencies": map_dependencies,
        "detect_cycles": detect_cycles,
        "assess_resilience": assess_resilience,
        "report": report,
    }

    edges = [
        edge("assess_resilience", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_services" via _check_error()
        # TODO: cond(...) from "trace_connections" via _check_error()
        # TODO: cond(...) from "map_dependencies" via _check_error()
        # TODO: cond(...) from "detect_cycles" via _check_error()
    ]

    entry = "discover_services"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ServiceDependencyMapperRunner`` keep working via this alias; new code
# should use ``ServiceDependencyMapperAgent`` directly through AgentRuntime.
ServiceDependencyMapperRunner = ServiceDependencyMapperAgent
