# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_feed_orchestrator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_feed_orchestrator.models import ThreatFeedOrchestratorState
from shieldops.agents.threat_feed_orchestrator.nodes import (
    connect_feeds,
    deduplicate,
    distribute,
    enrich,
    generate_report,
    normalize,
)
from shieldops.agents.threat_feed_orchestrator.tools import ThreatFeedOrchestratorToolkit


class ThreatFeedOrchestratorAgent(Agent):
    """Declarative spec for ``threat_feed_orchestrator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_feed_orchestrator"
    state_model = ThreatFeedOrchestratorState
    toolkit_factory = ThreatFeedOrchestratorToolkit

    nodes = {
        "connect_feeds": connect_feeds,
        "normalize": normalize,
        "deduplicate": deduplicate,
        "enrich": enrich,
        "distribute": distribute,
        "generate_report": generate_report,
    }

    edges = [
        edge("connect_feeds", "normalize"),
        edge("normalize", "deduplicate"),
        edge("deduplicate", "enrich"),
        edge("distribute", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "enrich"
        #   routed by _should_distribute() — wrap with cond(...)
    ]

    entry = "connect_feeds"
