# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the runtime_application_protector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.runtime_application_protector.models import RuntimeApplicationProtectorState
from shieldops.agents.runtime_application_protector.nodes import (
    classify_threat,
    detect_attacks,
    generate_report,
    instrument_app,
    monitor_runtime,
    protect,
)
from shieldops.agents.runtime_application_protector.tools import RuntimeApplicationProtectorToolkit


class RuntimeApplicationProtectorAgent(Agent):
    """Declarative spec for ``runtime_application_protector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "runtime_application_protector"
    state_model = RuntimeApplicationProtectorState
    toolkit_factory = RuntimeApplicationProtectorToolkit

    nodes = {
        "instrument_app": instrument_app,
        "monitor_runtime": monitor_runtime,
        "detect_attacks": detect_attacks,
        "classify_threat": classify_threat,
        "protect": protect,
        "generate_report": generate_report,
    }

    edges = [
        edge("instrument_app", "monitor_runtime"),
        edge("monitor_runtime", "detect_attacks"),
        edge("detect_attacks", "classify_threat"),
        edge("protect", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "classify_threat"
        #   routed by _should_protect() — wrap with cond(...)
    ]

    entry = "instrument_app"
