# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the identity_graph agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.identity_graph.models import IdentityGraphState
from shieldops.agents.identity_graph.nodes import (
    analyze_trust_chains,
    assess_risks,
    discover_identities,
    generate_remediations,
    map_relationships,
    report,
)
from shieldops.agents.identity_graph.tools import IdentityGraphToolkit
from shieldops.agents.runtime import END, Agent, edge


class IdentityGraphAgent(Agent):
    """Declarative spec for ``identity_graph`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "identity_graph"
    state_model = IdentityGraphState
    toolkit_factory = IdentityGraphToolkit

    nodes = {
        "discover_identities": discover_identities,
        "map_relationships": map_relationships,
        "analyze_trust_chains": analyze_trust_chains,
        "assess_risks": assess_risks,
        "generate_remediations": generate_remediations,
        "report": report,
    }

    edges = [
        edge("discover_identities", "map_relationships"),
        edge("map_relationships", "analyze_trust_chains"),
        edge("analyze_trust_chains", "assess_risks"),
        edge("generate_remediations", "report"),
        edge("report", END),
        # TODO: conditional edge from "assess_risks"
        #   routed by has_high_risk() — wrap with cond(...)
    ]

    entry = "discover_identities"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``IdentityGraphRunner`` keep working via this alias; new code
# should use ``IdentityGraphAgent`` directly through AgentRuntime.
IdentityGraphRunner = IdentityGraphAgent
