# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the incident_playbook_generator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.incident_playbook_generator.models import IncidentPlaybookGeneratorState
from shieldops.agents.incident_playbook_generator.nodes import (
    analyze_threat,
    design_workflow,
    generate_steps,
    map_techniques,
    report,
    validate_playbook,
)
from shieldops.agents.incident_playbook_generator.tools import IncidentPlaybookGeneratorToolkit
from shieldops.agents.runtime import END, Agent, edge


class IncidentPlaybookGeneratorAgent(Agent):
    """Declarative spec for ``incident_playbook_generator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "incident_playbook_generator"
    state_model = IncidentPlaybookGeneratorState
    toolkit_factory = IncidentPlaybookGeneratorToolkit

    nodes = {
        "analyze_threat": analyze_threat,
        "map_techniques": map_techniques,
        "design_workflow": design_workflow,
        "generate_steps": generate_steps,
        "validate_playbook": validate_playbook,
        "report": report,
    }

    edges = [
        edge("validate_playbook", "report"),
        edge("report", END),
        # TODO: cond(...) from "analyze_threat" via _check_error()
        # TODO: cond(...) from "map_techniques" via _check_error()
        # TODO: cond(...) from "design_workflow" via _check_error()
        # TODO: cond(...) from "generate_steps" via _check_error()
    ]

    entry = "analyze_threat"
