# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the agent_memory_store agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.agent_memory_store.models import AgentMemoryStoreState
from shieldops.agents.agent_memory_store.nodes import (
    classify_memory,
    index_for_retrieval,
    prune_stale,
    receive_memory,
    report,
    store_memory,
)
from shieldops.agents.agent_memory_store.tools import AgentMemoryStoreToolkit
from shieldops.agents.runtime import END, Agent, edge


class AgentMemoryStoreAgent(Agent):
    """Declarative spec for ``agent_memory_store`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "agent_memory_store"
    state_model = AgentMemoryStoreState
    toolkit_factory = AgentMemoryStoreToolkit

    nodes = {
        "receive_memory": receive_memory,
        "classify_memory": classify_memory,
        "store_memory": store_memory,
        "index_for_retrieval": index_for_retrieval,
        "prune_stale": prune_stale,
        "report": report,
    }

    edges = [
        edge("classify_memory", "store_memory"),
        edge("store_memory", "index_for_retrieval"),
        edge("prune_stale", "report"),
        edge("report", END),
        # TODO: conditional edge from "receive_memory"
        #   routed by route_operation() — wrap with cond(...)
        # TODO: conditional edge from "index_for_retrieval"
        #   routed by should_prune_after_store() — wrap with cond(...)
    ]

    entry = "receive_memory"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AgentMemoryStoreRunner`` keep working via this alias; new code
# should use ``AgentMemoryStoreAgent`` directly through AgentRuntime.
AgentMemoryStoreRunner = AgentMemoryStoreAgent
