# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the crypto_agility_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.crypto_agility_manager.models import CryptoAgilityManagerState
from shieldops.agents.crypto_agility_manager.nodes import (
    assess_agility,
    discover_algorithms,
    execute_migration,
    plan_migration,
    report,
    test_compatibility,
)
from shieldops.agents.crypto_agility_manager.tools import CryptoAgilityManagerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CryptoAgilityManagerAgent(Agent):
    """Declarative spec for ``crypto_agility_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "crypto_agility_manager"
    state_model = CryptoAgilityManagerState
    toolkit_factory = CryptoAgilityManagerToolkit

    nodes = {
        "discover_algorithms": discover_algorithms,
        "assess_agility": assess_agility,
        "plan_migration": plan_migration,
        "test_compatibility": test_compatibility,
        "execute_migration": execute_migration,
        "report": report,
    }

    edges = [
        edge("assess_agility", "plan_migration"),
        edge("plan_migration", "test_compatibility"),
        edge("test_compatibility", "execute_migration"),
        edge("execute_migration", "report"),
        edge("report", END),
        # TODO: conditional edge from "discover_algorithms"
        #   routed by _route_after_discover() — wrap with cond(...)
    ]

    entry = "discover_algorithms"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CryptoAgilityManagerRunner`` keep working via this alias; new code
# should use ``CryptoAgilityManagerAgent`` directly through AgentRuntime.
CryptoAgilityManagerRunner = CryptoAgilityManagerAgent
