# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_hunt_automation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_hunt_automation.models import ThreatHuntAutomationState
from shieldops.agents.threat_hunt_automation.nodes import (
    analyze_results,
    design_queries,
    document_findings,
    execute_hunts,
    generate_hypotheses,
    report,
)
from shieldops.agents.threat_hunt_automation.tools import ThreatHuntAutomationToolkit


class ThreatHuntAutomationAgent(Agent):
    """Declarative spec for ``threat_hunt_automation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_hunt_automation"
    state_model = ThreatHuntAutomationState
    toolkit_factory = ThreatHuntAutomationToolkit

    nodes = {
        "generate_hypotheses": generate_hypotheses,
        "design_queries": design_queries,
        "execute_hunts": execute_hunts,
        "analyze_results": analyze_results,
        "document_findings": document_findings,
        "report": report,
    }

    edges = [
        edge("document_findings", "report"),
        edge("report", END),
        # TODO: cond(...) from "generate_hypotheses" via _check_error()
        # TODO: cond(...) from "design_queries" via _check_error()
        # TODO: cond(...) from "execute_hunts" via _check_error()
        # TODO: cond(...) from "analyze_results" via _check_error()
    ]

    entry = "generate_hypotheses"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ThreatHuntAutomationRunner`` keep working via this alias; new code
# should use ``ThreatHuntAutomationAgent`` directly through AgentRuntime.
ThreatHuntAutomationRunner = ThreatHuntAutomationAgent
