# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cnapp_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cnapp_analyzer.models import CNAPPAnalyzerState
from shieldops.agents.cnapp_analyzer.nodes import (
    analyze_identity_entitlements,
    assess_workload_protection,
    correlate_risks,
    generate_report,
    scan_cloud_posture,
    scan_code_security,
)
from shieldops.agents.cnapp_analyzer.tools import CNAPPAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CnappAnalyzerAgent(Agent):
    """Declarative spec for ``cnapp_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cnapp_analyzer"
    state_model = CNAPPAnalyzerState
    toolkit_factory = CNAPPAnalyzerToolkit

    nodes = {
        "scan_cloud_posture": scan_cloud_posture,
        "assess_workload_protection": assess_workload_protection,
        "analyze_identity_entitlements": analyze_identity_entitlements,
        "scan_code_security": scan_code_security,
        "correlate_risks": correlate_risks,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_cloud_posture", "assess_workload_protection"),
        edge("assess_workload_protection", "analyze_identity_entitlements"),
        edge("analyze_identity_entitlements", "scan_code_security"),
        edge("scan_code_security", "correlate_risks"),
        edge("correlate_risks", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "scan_cloud_posture"
