# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the agent_fleet_optimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.agent_fleet_optimizer.models import AgentFleetOptimizerState
from shieldops.agents.agent_fleet_optimizer.nodes import (
    analyze_health,
    collect_fleet_status,
    detect_issues,
    optimize_schedules,
    recommend_actions,
    report,
)
from shieldops.agents.agent_fleet_optimizer.tools import AgentFleetOptimizerToolkit
from shieldops.agents.runtime import END, Agent, edge


class AgentFleetOptimizerAgent(Agent):
    """Declarative spec for ``agent_fleet_optimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "agent_fleet_optimizer"
    state_model = AgentFleetOptimizerState
    toolkit_factory = AgentFleetOptimizerToolkit

    nodes = {
        "collect_fleet_status": collect_fleet_status,
        "analyze_health": analyze_health,
        "optimize_schedules": optimize_schedules,
        "detect_issues": detect_issues,
        "recommend_actions": recommend_actions,
        "report": report,
    }

    edges = [
        edge("collect_fleet_status", "analyze_health"),
        edge("analyze_health", "optimize_schedules"),
        edge("optimize_schedules", "detect_issues"),
        edge("detect_issues", "recommend_actions"),
        edge("recommend_actions", "report"),
        edge("report", END),
    ]

    entry = "collect_fleet_status"
