# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the service_health_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.service_health_monitor.models import ServiceHealthMonitorState
from shieldops.agents.service_health_monitor.nodes import (
    analyze_dependencies,
    check_health,
    detect_degradation,
    discover_services,
    report,
    trigger_remediation,
)
from shieldops.agents.service_health_monitor.tools import ServiceHealthMonitorToolkit


class ServiceHealthMonitorAgent(Agent):
    """Declarative spec for ``service_health_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "service_health_monitor"
    state_model = ServiceHealthMonitorState
    toolkit_factory = ServiceHealthMonitorToolkit

    nodes = {
        "discover_services": discover_services,
        "check_health": check_health,
        "analyze_dependencies": analyze_dependencies,
        "detect_degradation": detect_degradation,
        "trigger_remediation": trigger_remediation,
        "report": report,
    }

    edges = [
        edge("discover_services", "check_health"),
        edge("check_health", "analyze_dependencies"),
        edge("analyze_dependencies", "detect_degradation"),
        edge("trigger_remediation", "report"),
        edge("report", END),
        # TODO: conditional edge from "detect_degradation"
        #   routed by should_remediate() — wrap with cond(...)
    ]

    entry = "discover_services"
