# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the usb_device_controller agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.usb_device_controller.models import USBDeviceControllerState
from shieldops.agents.usb_device_controller.nodes import (
    check_whitelist,
    enforce_policy,
    generate_report,
    monitor_transfers,
    scan_devices,
)
from shieldops.agents.usb_device_controller.tools import USBDeviceControllerToolkit


class UsbDeviceControllerAgent(Agent):
    """Declarative spec for ``usb_device_controller`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "usb_device_controller"
    state_model = USBDeviceControllerState
    toolkit_factory = USBDeviceControllerToolkit

    nodes = {
        "scan_devices": scan_devices,
        "check_whitelist": check_whitelist,
        "monitor_transfers": monitor_transfers,
        "enforce_policy": enforce_policy,
        "report": generate_report,
        # TODO: resolve node fn for "error_end"
    }

    edges = [
        edge("check_whitelist", "monitor_transfers"),
        edge("monitor_transfers", "enforce_policy"),
        edge("enforce_policy", "report"),
        edge("report", END),
        edge("error_end", END),
        # TODO: conditional edge from "scan_devices"
        #   routed by _check_error() — wrap with cond(...)
    ]

    entry = "scan_devices"
