# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ai_soc_assistant agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ai_soc_assistant.models import AISOCAssistantState
from shieldops.agents.ai_soc_assistant.nodes import (
    gather_context,
    generate_actions,
    parse_query,
    present_results,
    reason_about_findings,
    report,
)
from shieldops.agents.ai_soc_assistant.tools import AISOCAssistantToolkit
from shieldops.agents.runtime import END, Agent, edge


class AiSocAssistantAgent(Agent):
    """Declarative spec for ``ai_soc_assistant`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ai_soc_assistant"
    state_model = AISOCAssistantState
    toolkit_factory = AISOCAssistantToolkit

    nodes = {
        "parse_query": parse_query,
        "gather_context": gather_context,
        "reason_about_findings": reason_about_findings,
        "generate_actions": generate_actions,
        "present_results": present_results,
        "report": report,
    }

    edges = [
        edge("parse_query", "gather_context"),
        edge("gather_context", "reason_about_findings"),
        edge("generate_actions", "present_results"),
        edge("present_results", "report"),
        edge("report", END),
        # TODO: conditional edge from "reason_about_findings"
        #   routed by needs_actions() — wrap with cond(...)
    ]

    entry = "parse_query"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AISOCAssistantRunner`` keep working via this alias; new code
# should use ``AiSocAssistantAgent`` directly through AgentRuntime.
AISOCAssistantRunner = AiSocAssistantAgent
