# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the iam_policy_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.iam_policy_analyzer.models import IAMPolicyAnalyzerState
from shieldops.agents.iam_policy_analyzer.nodes import (
    analyze_permissions,
    collect_policies,
    detect_overprivilege,
    find_unused,
    generate_report,
    recommend_fixes,
)
from shieldops.agents.iam_policy_analyzer.tools import IAMPolicyAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class IamPolicyAnalyzerAgent(Agent):
    """Declarative spec for ``iam_policy_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "iam_policy_analyzer"
    state_model = IAMPolicyAnalyzerState
    toolkit_factory = IAMPolicyAnalyzerToolkit

    nodes = {
        "collect_policies": collect_policies,
        "analyze_permissions": analyze_permissions,
        "detect_overprivilege": detect_overprivilege,
        "find_unused": find_unused,
        "recommend_fixes": recommend_fixes,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_policies", "analyze_permissions"),
        edge("analyze_permissions", "detect_overprivilege"),
        edge("find_unused", "recommend_fixes"),
        edge("recommend_fixes", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_overprivilege"
        #   routed by _has_overprivilege() — wrap with cond(...)
    ]

    entry = "collect_policies"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``IAMPolicyAnalyzerRunner`` keep working via this alias; new code
# should use ``IamPolicyAnalyzerAgent`` directly through AgentRuntime.
IAMPolicyAnalyzerRunner = IamPolicyAnalyzerAgent
