# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the email_security_gateway agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.email_security_gateway.models import EmailSecurityGatewayState
from shieldops.agents.email_security_gateway.nodes import (
    analyze_headers,
    check_reputation,
    generate_report,
    ingest_email,
    quarantine_messages,
    scan_attachments,
)
from shieldops.agents.email_security_gateway.tools import EmailSecurityGatewayToolkit
from shieldops.agents.runtime import END, Agent, edge


class EmailSecurityGatewayAgent(Agent):
    """Declarative spec for ``email_security_gateway`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "email_security_gateway"
    state_model = EmailSecurityGatewayState
    toolkit_factory = EmailSecurityGatewayToolkit

    nodes = {
        "ingest_email": ingest_email,
        "analyze_headers": analyze_headers,
        "scan_attachments": scan_attachments,
        "check_reputation": check_reputation,
        "quarantine_messages": quarantine_messages,
        "generate_report": generate_report,
    }

    edges = [
        edge("ingest_email", "analyze_headers"),
        edge("scan_attachments", "check_reputation"),
        edge("quarantine_messages", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "analyze_headers"
        #   routed by _should_scan_attachments() — wrap with cond(...)
        # TODO: conditional edge from "check_reputation"
        #   routed by _should_quarantine() — wrap with cond(...)
    ]

    entry = "ingest_email"
