# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the risk_prioritizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.risk_prioritizer.models import RiskPrioritizerState
from shieldops.agents.risk_prioritizer.nodes import (
    collect_findings,
    enrich_context,
    generate_action_plan,
    generate_report,
    rank_findings,
    score_risk,
)
from shieldops.agents.risk_prioritizer.tools import RiskPrioritizerToolkit
from shieldops.agents.runtime import END, Agent, edge


class RiskPrioritizerAgent(Agent):
    """Declarative spec for ``risk_prioritizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "risk_prioritizer"
    state_model = RiskPrioritizerState
    toolkit_factory = RiskPrioritizerToolkit

    nodes = {
        "collect_findings": collect_findings,
        "enrich_context": enrich_context,
        "score_risk": score_risk,
        "rank_findings": rank_findings,
        "generate_action_plan": generate_action_plan,
        "generate_report": generate_report,
    }

    edges = [
        edge("enrich_context", "score_risk"),
        edge("score_risk", "rank_findings"),
        edge("rank_findings", "generate_action_plan"),
        edge("generate_action_plan", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "collect_findings"
        #   routed by _has_findings() — wrap with cond(...)
    ]

    entry = "collect_findings"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``RiskPrioritizerRunner`` keep working via this alias; new code
# should use ``RiskPrioritizerAgent`` directly through AgentRuntime.
RiskPrioritizerRunner = RiskPrioritizerAgent
