# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the risk_scoring agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.risk_scoring.models import RiskScoringState
from shieldops.agents.risk_scoring.nodes import (
    aggregate_by_entity,
    collect_observations,
    decide_actions,
    enrich_observations,
)
from shieldops.agents.risk_scoring.tools import RiskScoringToolkit
from shieldops.agents.runtime import END, Agent, edge


class RiskScoringAgent(Agent):
    """Declarative spec for ``risk_scoring`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "risk_scoring"
    state_model = RiskScoringState
    toolkit_factory = RiskScoringToolkit

    nodes = {
        "collect": collect_observations,
        "enrich": enrich_observations,
        "aggregate": aggregate_by_entity,
        "decide": decide_actions,
    }

    edges = [
        edge("collect", "enrich"),
        edge("enrich", "aggregate"),
        edge("aggregate", "decide"),
        edge("decide", END),
    ]

    entry = "collect"
