# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the quantum_risk_assessor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.quantum_risk_assessor.models import QuantumRiskAssessorState
from shieldops.agents.quantum_risk_assessor.nodes import (
    assess_vulnerability,
    inventory_algorithms,
    recommend_migration,
    report,
    scan_infrastructure,
    score_readiness,
)
from shieldops.agents.quantum_risk_assessor.tools import QuantumRiskAssessorToolkit
from shieldops.agents.runtime import END, Agent, edge


class QuantumRiskAssessorAgent(Agent):
    """Declarative spec for ``quantum_risk_assessor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "quantum_risk_assessor"
    state_model = QuantumRiskAssessorState
    toolkit_factory = QuantumRiskAssessorToolkit

    nodes = {
        "scan_infrastructure": scan_infrastructure,
        "inventory_algorithms": inventory_algorithms,
        "assess_vulnerability": assess_vulnerability,
        "score_readiness": score_readiness,
        "recommend_migration": recommend_migration,
        "report": report,
    }

    edges = [
        edge("recommend_migration", "report"),
        edge("report", END),
        # TODO: cond(...) from "scan_infrastructure" via _after_scan()
        # TODO: cond(...) from "inventory_algorithms" via _after_inventory()
        # TODO: cond(...) from "assess_vulnerability" via _after_assess()
        # TODO: cond(...) from "score_readiness" via _after_readiness()
    ]

    entry = "scan_infrastructure"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``QuantumRiskAssessorRunner`` keep working via this alias; new code
# should use ``QuantumRiskAssessorAgent`` directly through AgentRuntime.
QuantumRiskAssessorRunner = QuantumRiskAssessorAgent
