# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_audit_logger agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_audit_logger.models import CloudAuditLoggerState
from shieldops.agents.cloud_audit_logger.nodes import (
    assess_risk,
    correlate_activity,
    detect_anomalies,
    ingest_logs,
)
from shieldops.agents.cloud_audit_logger.tools import CloudAuditLoggerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudAuditLoggerAgent(Agent):
    """Declarative spec for ``cloud_audit_logger`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_audit_logger"
    state_model = CloudAuditLoggerState
    toolkit_factory = CloudAuditLoggerToolkit

    nodes = {
        "ingest_logs": ingest_logs,
        "detect_anomalies": detect_anomalies,
        "correlate_activity": correlate_activity,
        "assess_risk": assess_risk,
    }

    edges = [
        edge("detect_anomalies", "correlate_activity"),
        edge("correlate_activity", "assess_risk"),
        edge("assess_risk", END),
        # TODO: conditional edge from "ingest_logs"
        #   routed by _has_error() — wrap with cond(...)
    ]

    entry = "ingest_logs"
