# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the endpoint_forensics agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.endpoint_forensics.models import EndpointForensicsState
from shieldops.agents.endpoint_forensics.nodes import (
    analyze_memory,
    carve_files,
    collect_artifacts,
    generate_report,
    investigate_processes,
    reconstruct_timeline,
)
from shieldops.agents.endpoint_forensics.tools import EndpointForensicsToolkit
from shieldops.agents.runtime import END, Agent, edge


class EndpointForensicsAgent(Agent):
    """Declarative spec for ``endpoint_forensics`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "endpoint_forensics"
    state_model = EndpointForensicsState
    toolkit_factory = EndpointForensicsToolkit

    nodes = {
        "collect_artifacts": collect_artifacts,
        "analyze_memory": analyze_memory,
        "investigate_processes": investigate_processes,
        "carve_files": carve_files,
        "reconstruct_timeline": reconstruct_timeline,
        "report": generate_report,
        # TODO: resolve node fn for "error_end"
    }

    edges = [
        edge("analyze_memory", "investigate_processes"),
        edge("investigate_processes", "carve_files"),
        edge("carve_files", "reconstruct_timeline"),
        edge("reconstruct_timeline", "report"),
        edge("report", END),
        edge("error_end", END),
        # TODO: conditional edge from "collect_artifacts"
        #   routed by _check_error() — wrap with cond(...)
    ]

    entry = "collect_artifacts"
