# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the service_account_tracker agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.service_account_tracker.models import ServiceAccountTrackerState
from shieldops.agents.service_account_tracker.nodes import (
    analyze_usage,
    classify_risk,
    detect_anomalies,
    discover,
    generate_report,
    remediate,
)
from shieldops.agents.service_account_tracker.tools import ServiceAccountTrackerToolkit


class ServiceAccountTrackerAgent(Agent):
    """Declarative spec for ``service_account_tracker`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "service_account_tracker"
    state_model = ServiceAccountTrackerState
    toolkit_factory = ServiceAccountTrackerToolkit

    nodes = {
        "discover": discover,
        "analyze_usage": analyze_usage,
        "detect_anomalies": detect_anomalies,
        "classify_risk": classify_risk,
        "remediate": remediate,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover", "analyze_usage"),
        edge("analyze_usage", "detect_anomalies"),
        edge("detect_anomalies", "classify_risk"),
        edge("remediate", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "classify_risk"
        #   routed by _has_anomalies() — wrap with cond(...)
    ]

    entry = "discover"
