# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the physical_access_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.physical_access_monitor.models import PhysicalAccessMonitorState
from shieldops.agents.physical_access_monitor.nodes import (
    analyze_patterns,
    detect_anomalies,
    evaluate_policies,
    generate_alerts,
    generate_report,
    ingest_events,
)
from shieldops.agents.physical_access_monitor.tools import PhysicalAccessMonitorToolkit
from shieldops.agents.runtime import END, Agent, edge


class PhysicalAccessMonitorAgent(Agent):
    """Declarative spec for ``physical_access_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "physical_access_monitor"
    state_model = PhysicalAccessMonitorState
    toolkit_factory = PhysicalAccessMonitorToolkit

    nodes = {
        "ingest_events": ingest_events,
        "analyze_patterns": analyze_patterns,
        "detect_anomalies": detect_anomalies,
        "evaluate_policies": evaluate_policies,
        "generate_alerts": generate_alerts,
        "generate_report": generate_report,
    }

    edges = [
        edge("ingest_events", "analyze_patterns"),
        edge("analyze_patterns", "detect_anomalies"),
        edge("detect_anomalies", "evaluate_policies"),
        edge("generate_alerts", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "evaluate_policies"
        #   routed by _needs_alerts() — wrap with cond(...)
    ]

    entry = "ingest_events"
