# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ci_cd_security_auditor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ci_cd_security_auditor.models import CiCdSecurityAuditorState
from shieldops.agents.ci_cd_security_auditor.nodes import (
    assess_risk,
    check_permissions,
    detect_injection,
    map_pipelines,
    report,
    scan_configs,
)
from shieldops.agents.ci_cd_security_auditor.tools import CiCdSecurityAuditorToolkit
from shieldops.agents.runtime import END, Agent, edge


class CiCdSecurityAuditorAgent(Agent):
    """Declarative spec for ``ci_cd_security_auditor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ci_cd_security_auditor"
    state_model = CiCdSecurityAuditorState
    toolkit_factory = CiCdSecurityAuditorToolkit

    nodes = {
        "map_pipelines": map_pipelines,
        "check_permissions": check_permissions,
        "scan_configs": scan_configs,
        "detect_injection": detect_injection,
        "assess_risk": assess_risk,
        "report": report,
    }

    edges = [
        edge("assess_risk", "report"),
        edge("report", END),
        # TODO: cond(...) from "map_pipelines" via _check_error()
        # TODO: cond(...) from "check_permissions" via _check_error()
        # TODO: cond(...) from "scan_configs" via _check_error()
        # TODO: cond(...) from "detect_injection" via _check_error()
    ]

    entry = "map_pipelines"
