# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_mesh_orchestrator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_mesh_orchestrator.models import SecurityMeshOrchestratorState
from shieldops.agents.security_mesh_orchestrator.nodes import (
    detect_anomalies,
    discover_services,
    enforce_mtls,
    generate_report,
    map_mesh,
    monitor_traffic,
)
from shieldops.agents.security_mesh_orchestrator.tools import SecurityMeshOrchestratorToolkit


class SecurityMeshOrchestratorAgent(Agent):
    """Declarative spec for ``security_mesh_orchestrator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_mesh_orchestrator"
    state_model = SecurityMeshOrchestratorState
    toolkit_factory = SecurityMeshOrchestratorToolkit

    nodes = {
        "discover_services": discover_services,
        "map_mesh": map_mesh,
        "enforce_mtls": enforce_mtls,
        "monitor_traffic": monitor_traffic,
        "detect_anomalies": detect_anomalies,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_services", "map_mesh"),
        edge("map_mesh", "enforce_mtls"),
        edge("enforce_mtls", "monitor_traffic"),
        edge("monitor_traffic", "detect_anomalies"),
        edge("detect_anomalies", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "discover_services"
