# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the nhi_registry agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.nhi_registry.models import NHIRegistryState
from shieldops.agents.nhi_registry.nodes import (
    assess_risk,
    classify_identities,
    detect_shadow_ai,
    generate_recommendations,
    report,
    scan_cicd,
    scan_cloud_iam,
    scan_kubernetes,
)
from shieldops.agents.nhi_registry.tools import NHIRegistryToolkit
from shieldops.agents.runtime import END, Agent, edge


class NhiRegistryAgent(Agent):
    """Declarative spec for ``nhi_registry`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "nhi_registry"
    state_model = NHIRegistryState
    toolkit_factory = NHIRegistryToolkit

    nodes = {
        "scan_cloud_iam": scan_cloud_iam,
        "scan_kubernetes": scan_kubernetes,
        "scan_cicd": scan_cicd,
        "detect_shadow_ai": detect_shadow_ai,
        "classify_identities": classify_identities,
        "assess_risk": assess_risk,
        "generate_recommendations": generate_recommendations,
        "report": report,
    }

    edges = [
        edge("scan_cloud_iam", "scan_kubernetes"),
        edge("scan_kubernetes", "scan_cicd"),
        edge("scan_cicd", "detect_shadow_ai"),
        edge("detect_shadow_ai", "classify_identities"),
        edge("classify_identities", "assess_risk"),
        edge("assess_risk", "generate_recommendations"),
        edge("generate_recommendations", "report"),
        edge("report", END),
    ]

    entry = "scan_cloud_iam"
