# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the reflection_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.reflection_engine.models import ReflectionEngineState
from shieldops.agents.reflection_engine.nodes import (
    apply_learnings,
    collect_agent_actions,
    evaluate_outcomes,
    generate_improvements,
    generate_report,
    identify_mistakes,
)
from shieldops.agents.reflection_engine.tools import ReflectionEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class ReflectionEngineAgent(Agent):
    """Declarative spec for ``reflection_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "reflection_engine"
    state_model = ReflectionEngineState
    toolkit_factory = ReflectionEngineToolkit

    nodes = {
        "collect_agent_actions": collect_agent_actions,
        "evaluate_outcomes": evaluate_outcomes,
        "identify_mistakes": identify_mistakes,
        "generate_improvements": generate_improvements,
        "apply_learnings": apply_learnings,
        "generate_report": generate_report,
    }

    edges = [
        edge("evaluate_outcomes", "identify_mistakes"),
        edge("apply_learnings", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "collect_agent_actions"
        #   routed by has_actions() — wrap with cond(...)
        # TODO: conditional edge from "identify_mistakes"
        #   routed by has_mistakes() — wrap with cond(...)
        # TODO: conditional edge from "generate_improvements"
        #   routed by has_improvements() — wrap with cond(...)
    ]

    entry = "collect_agent_actions"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ReflectionEngineRunner`` keep working via this alias; new code
# should use ``ReflectionEngineAgent`` directly through AgentRuntime.
ReflectionEngineRunner = ReflectionEngineAgent
