# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the network_forensics agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.network_forensics.models import NetworkForensicsState
from shieldops.agents.network_forensics.nodes import (
    build_timeline,
    ingest_capture,
    map_exfiltration,
    reconstruct_sessions,
    report,
    trace_lateral,
)
from shieldops.agents.network_forensics.tools import NetworkForensicsToolkit
from shieldops.agents.runtime import END, Agent, edge


class NetworkForensicsAgent(Agent):
    """Declarative spec for ``network_forensics`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "network_forensics"
    state_model = NetworkForensicsState
    toolkit_factory = NetworkForensicsToolkit

    nodes = {
        "ingest_capture": ingest_capture,
        "reconstruct_sessions": reconstruct_sessions,
        "build_timeline": build_timeline,
        "trace_lateral": trace_lateral,
        "map_exfiltration": map_exfiltration,
        "report": report,
    }

    edges = [
        edge("build_timeline", "trace_lateral"),
        edge("trace_lateral", "map_exfiltration"),
        edge("map_exfiltration", "report"),
        edge("report", END),
        # TODO: conditional edge from "ingest_capture"
        #   routed by _check_error() — wrap with cond(...)
        # TODO: conditional edge from "reconstruct_sessions"
        #   routed by _check_error() — wrap with cond(...)
    ]

    entry = "ingest_capture"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``NetworkForensicsRunner`` keep working via this alias; new code
# should use ``NetworkForensicsAgent`` directly through AgentRuntime.
NetworkForensicsRunner = NetworkForensicsAgent
