# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the behavioral_analytics_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.behavioral_analytics_engine.models import BehavioralAnalyticsEngineState
from shieldops.agents.behavioral_analytics_engine.nodes import (
    alert_violations,
    build_profiles,
    collect_telemetry,
    detect_anomalies,
    report,
    score_risk,
)
from shieldops.agents.behavioral_analytics_engine.tools import BehavioralAnalyticsEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class BehavioralAnalyticsEngineAgent(Agent):
    """Declarative spec for ``behavioral_analytics_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "behavioral_analytics_engine"
    state_model = BehavioralAnalyticsEngineState
    toolkit_factory = BehavioralAnalyticsEngineToolkit

    nodes = {
        "collect_telemetry": collect_telemetry,
        "build_profiles": build_profiles,
        "detect_anomalies": detect_anomalies,
        "score_risk": score_risk,
        "alert_violations": alert_violations,
        "report": report,
    }

    edges = [
        edge("alert_violations", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_telemetry" via _check_error()
        # TODO: cond(...) from "build_profiles" via _check_error()
        # TODO: cond(...) from "detect_anomalies" via _check_error()
        # TODO: cond(...) from "score_risk" via _check_error()
    ]

    entry = "collect_telemetry"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``BehavioralAnalyticsEngineRunner`` keep working via this alias; new code
# should use ``BehavioralAnalyticsEngineAgent`` directly through AgentRuntime.
BehavioralAnalyticsEngineRunner = BehavioralAnalyticsEngineAgent
