# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_scorecard agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_scorecard.models import SecurityScorecardState
from shieldops.agents.security_scorecard.nodes import (
    calculate_composite,
    collect_domain_scores,
    compare_benchmarks,
    generate_insights,
    generate_report,
    track_trends,
)
from shieldops.agents.security_scorecard.tools import SecurityScorecardToolkit


class SecurityScorecardAgent(Agent):
    """Declarative spec for ``security_scorecard`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_scorecard"
    state_model = SecurityScorecardState
    toolkit_factory = SecurityScorecardToolkit

    nodes = {
        "collect_domain_scores": collect_domain_scores,
        "calculate_composite": calculate_composite,
        "track_trends": track_trends,
        "compare_benchmarks": compare_benchmarks,
        "generate_insights": generate_insights,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_domain_scores", "calculate_composite"),
        edge("calculate_composite", "track_trends"),
        edge("track_trends", "compare_benchmarks"),
        edge("compare_benchmarks", "generate_insights"),
        edge("generate_insights", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "collect_domain_scores"
