# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the dns_security agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.dns_security.models import DNSSecurityState
from shieldops.agents.dns_security.nodes import (
    collect_dns,
    detect_dga,
    detect_tunneling,
    detect_typosquatting,
    generate_report,
    respond_to_threats,
)
from shieldops.agents.dns_security.tools import DNSSecurityToolkit
from shieldops.agents.runtime import END, Agent, edge


class DnsSecurityAgent(Agent):
    """Declarative spec for ``dns_security`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "dns_security"
    state_model = DNSSecurityState
    toolkit_factory = DNSSecurityToolkit

    nodes = {
        "collect_dns": collect_dns,
        "detect_tunneling": detect_tunneling,
        "detect_dga": detect_dga,
        "detect_typosquatting": detect_typosquatting,
        "respond": respond_to_threats,
        "report": generate_report,
    }

    edges = [
        edge("collect_dns", "detect_tunneling"),
        edge("detect_tunneling", "detect_dga"),
        edge("detect_dga", "detect_typosquatting"),
        edge("detect_typosquatting", "respond"),
        edge("respond", "report"),
        edge("report", END),
    ]

    entry = "collect_dns"
