# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the file_integrity_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.file_integrity_monitor.models import FileIntegrityMonitorState
from shieldops.agents.file_integrity_monitor.nodes import (
    assess_impact,
    classify_changes,
    detect_changes,
    generate_report,
    respond,
    scan_baseline,
)
from shieldops.agents.file_integrity_monitor.tools import FileIntegrityMonitorToolkit
from shieldops.agents.runtime import END, Agent, edge


class FileIntegrityMonitorAgent(Agent):
    """Declarative spec for ``file_integrity_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "file_integrity_monitor"
    state_model = FileIntegrityMonitorState
    toolkit_factory = FileIntegrityMonitorToolkit

    nodes = {
        "scan_baseline": scan_baseline,
        "detect_changes": detect_changes,
        "classify_changes": classify_changes,
        "assess_impact": assess_impact,
        "respond": respond,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_baseline", "detect_changes"),
        edge("detect_changes", "classify_changes"),
        edge("classify_changes", "assess_impact"),
        edge("respond", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "assess_impact"
        #   routed by should_respond() — wrap with cond(...)
    ]

    entry = "scan_baseline"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``FileIntegrityMonitorRunner`` keep working via this alias; new code
# should use ``FileIntegrityMonitorAgent`` directly through AgentRuntime.
FileIntegrityMonitorRunner = FileIntegrityMonitorAgent
