# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the remediation_verifier agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.remediation_verifier.models import RemediationVerifierState
from shieldops.agents.remediation_verifier.nodes import (
    assess_results,
    collect_remediations,
    design_verification_tests,
    execute_tests,
    flag_regressions,
    generate_report,
)
from shieldops.agents.remediation_verifier.tools import RemediationVerifierToolkit
from shieldops.agents.runtime import END, Agent, edge


class RemediationVerifierAgent(Agent):
    """Declarative spec for ``remediation_verifier`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "remediation_verifier"
    state_model = RemediationVerifierState
    toolkit_factory = RemediationVerifierToolkit

    nodes = {
        "collect_remediations": collect_remediations,
        "design_verification_tests": design_verification_tests,
        "execute_tests": execute_tests,
        "assess_results": assess_results,
        "flag_regressions": flag_regressions,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_remediations", "design_verification_tests"),
        edge("design_verification_tests", "execute_tests"),
        edge("execute_tests", "assess_results"),
        edge("flag_regressions", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "assess_results"
        #   routed by route_after_assess() — wrap with cond(...)
    ]

    entry = "collect_remediations"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``RemediationVerifierRunner`` keep working via this alias; new code
# should use ``RemediationVerifierAgent`` directly through AgentRuntime.
RemediationVerifierRunner = RemediationVerifierAgent
