# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_metric_dashboard agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_metric_dashboard.models import SecurityMetricDashboardState
from shieldops.agents.security_metric_dashboard.nodes import (
    benchmark_industry,
    build_dashboard,
    calculate_kpis,
    collect_metrics,
    generate_report,
    normalize_metrics,
)
from shieldops.agents.security_metric_dashboard.tools import SecurityMetricDashboardToolkit


class SecurityMetricDashboardAgent(Agent):
    """Declarative spec for ``security_metric_dashboard`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_metric_dashboard"
    state_model = SecurityMetricDashboardState
    toolkit_factory = SecurityMetricDashboardToolkit

    nodes = {
        "collect_metrics": collect_metrics,
        "normalize_metrics": normalize_metrics,
        "calculate_kpis": calculate_kpis,
        "benchmark_industry": benchmark_industry,
        "build_dashboard": build_dashboard,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_metrics", "normalize_metrics"),
        edge("normalize_metrics", "calculate_kpis"),
        edge("benchmark_industry", "build_dashboard"),
        edge("build_dashboard", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "calculate_kpis"
        #   routed by _should_benchmark() — wrap with cond(...)
    ]

    entry = "collect_metrics"
