import {
  LayoutDashboard,
  Search,
  Wrench,
  BarChart3,
  Gauge,
  TrendingUp,
  HardDrive,
  Brain,
  HeartPulse,
  ShieldAlert,
  Bug,
  Layers,
  BookOpen,
  DollarSign,
  CreditCard,
  ShieldCheck,
  FileText,
  Store,
  Rocket,
  Code,
  Settings,
  Users,
  Sparkles,
  Siren,
  Activity,
  GitBranch,
  Key,
  Workflow,
  CalendarClock,
  Server,
  MessageSquare,
  Plug,
  Zap,
  Target,
  Shield,
  FileCheck,
  Filter,
  Crosshair,
  TestTube2,
  ScrollText,
  KeyRound,
  Database,
  ArrowRightLeft,
  Puzzle,
  Eye,
  Lock,
  Globe,
  FileCode,
  Cloud,
  Container,
  Package,
  ClipboardCheck,
  Tag,
  RefreshCw,
  Network,
  Boxes,
  Scale,
  Bot,
  Timer,
  Radar,
  Fingerprint,
  RotateCcw,
  UserCheck,
  UserX,
  Cpu,
  Blocks,
  LayoutList,
  type LucideIcon,
} from "lucide-react";

export type ProductId = "sre" | "soc" | "finops" | "compliance" | "platform" | "api" | "marketplace";

export interface Product {
  id: ProductId;
  name: string;
  tagline: string;
  description: string;
  icon: LucideIcon;
  color: string;
  bgGradient: string;
  demoPath: string;
}

export const PRODUCTS: Record<Exclude<ProductId, "platform">, Product> = {
  sre: {
    id: "sre",
    name: "SRE Intelligence",
    tagline: "Autonomous incident response",
    description:
      "50 autonomous agents that investigate alerts, identify root causes, optimize telemetry pipelines, and learn from outcomes — across AWS, GCP, Azure, K8s, and on-prem.",
    icon: LayoutDashboard,
    color: "text-brand-400",
    bgGradient: "from-brand-600/20 to-brand-800/20",
    demoPath: "/app?demo=true",
  },
  soc: {
    id: "soc",
    name: "Security Operations",
    tagline: "AI-powered threat defense",
    description:
      "Autonomous SOC agents for threat intelligence, risk-based alerting, MITRE ATT&CK mapping, vulnerability management, and SOAR playbook orchestration.",
    icon: ShieldAlert,
    color: "text-red-400",
    bgGradient: "from-red-600/20 to-red-800/20",
    demoPath: "/app/security?demo=true",
  },
  finops: {
    id: "finops",
    name: "FinOps Intelligence",
    tagline: "Cloud cost optimization",
    description:
      "Intelligent cost analysis, budget forecasting, and resource optimization across all cloud providers.",
    icon: DollarSign,
    color: "text-emerald-400",
    bgGradient: "from-emerald-600/20 to-emerald-800/20",
    demoPath: "/app/cost?demo=true",
  },
  compliance: {
    id: "compliance",
    name: "Compliance Automation",
    tagline: "Continuous compliance assurance",
    description:
      "Automated compliance monitoring, evidence collection, audit trails, and policy enforcement across your infrastructure.",
    icon: ShieldCheck,
    color: "text-amber-400",
    bgGradient: "from-amber-600/20 to-amber-800/20",
    demoPath: "/app/compliance?demo=true",
  },
  api: {
    id: "api",
    name: "API Platform",
    tagline: "Developer-first agent APIs",
    description:
      "Expose ShieldOps capabilities as metered APIs — investigations, remediations, analytics, and more — for integration into your own tools and portals.",
    icon: Code,
    color: "text-sky-400",
    bgGradient: "from-sky-600/20 to-sky-800/20",
    demoPath: "/app/api-keys?demo=true",
  },
  marketplace: {
    id: "marketplace",
    name: "Agent Marketplace",
    tagline: "Extensible agent ecosystem",
    description:
      "Discover and deploy community-built agents, connectors, and playbooks. Publish your own and earn revenue through the marketplace.",
    icon: Store,
    color: "text-orange-400",
    bgGradient: "from-orange-600/20 to-orange-800/20",
    demoPath: "/app/marketplace?demo=true",
  },
};

export interface NavItem {
  to: string;
  icon: LucideIcon;
  label: string;
}

export interface NavGroup {
  id: string;
  label: string;
  productId?: ProductId;
  color: string;
  items: NavItem[];
}

export const NAV_GROUPS: NavGroup[] = [
  {
    id: "agent-factory",
    label: "Agent Factory",
    color: "text-brand-400",
    items: [
      { to: "/app", icon: Sparkles, label: "Agent Factory" },
      { to: "/app/war-room", icon: Siren, label: "War Rooms" },
      { to: "/app/workflows", icon: Workflow, label: "Workflows" },
      { to: "/app/agent-history", icon: Activity, label: "Agent History" },
      { to: "/app/schedules", icon: CalendarClock, label: "Schedules" },
    ],
  },
  {
    id: "sre",
    label: "SRE Intelligence",
    productId: "sre",
    color: "text-brand-400",
    items: [
      { to: "/app/fleet", icon: LayoutDashboard, label: "Fleet Overview" },
      { to: "/app/investigations", icon: Search, label: "Investigations" },
      { to: "/app/remediations", icon: Wrench, label: "Remediations" },
      { to: "/app/pipeline", icon: GitBranch, label: "Pipeline" },
      { to: "/app/analytics", icon: BarChart3, label: "Analytics" },
      { to: "/app/agent-performance", icon: Gauge, label: "Agent Perf" },
      { to: "/app/predictions", icon: TrendingUp, label: "Predictions" },
      { to: "/app/capacity", icon: HardDrive, label: "Capacity" },
      { to: "/app/learning", icon: Brain, label: "Learning" },
      { to: "/app/system-health", icon: HeartPulse, label: "System Health" },
      { to: "/app/telemetry-optimizer", icon: BarChart3, label: "Telemetry Costs" },
      { to: "/app/incident-commander", icon: Siren, label: "Incident Commander" },
    ],
  },
  {
    id: "security",
    label: "Security Operations",
    productId: "soc",
    color: "text-red-400",
    items: [
      { to: "/app/situations", icon: Target, label: "Situations" },
      { to: "/app/agent-firewall", icon: Shield, label: "Agent Firewall" },
      { to: "/app/nhi-registry", icon: KeyRound, label: "NHI Registry" },
      { to: "/app/mcp-security", icon: Plug, label: "MCP Security" },
      { to: "/app/security", icon: ShieldAlert, label: "Security" },
      { to: "/app/vulnerabilities", icon: Bug, label: "Vulnerabilities" },
      { to: "/app/incidents", icon: Layers, label: "Incident Correlation" },
      { to: "/app/playbooks", icon: BookOpen, label: "Playbooks" },
      { to: "/app/risk-scoring", icon: Target, label: "Risk Scoring" },
      { to: "/app/threat-intel", icon: Shield, label: "Threat Intel" },
      { to: "/app/compliance-audit", icon: FileCheck, label: "Compliance Audit" },
      { to: "/app/adaptive-security", icon: ShieldCheck, label: "Adaptive Security" },
      { to: "/app/security-posture", icon: ShieldAlert, label: "Security Posture" },
      { to: "/app/soar-workflow", icon: Zap, label: "SOAR Workflows" },
      { to: "/app/detection-engineering", icon: Crosshair, label: "Detection Eng." },
      { to: "/app/security-testing", icon: TestTube2, label: "Security Testing" },
      { to: "/app/threat-modeling", icon: Shield, label: "Threat Modeling" },
      { to: "/app/data-pipeline-security", icon: Database, label: "Data Pipeline Security" },
      { to: "/app/credential-lifecycle", icon: Key, label: "Credential Lifecycle" },
      { to: "/app/vendor-normalizer", icon: ArrowRightLeft, label: "Vendor Normalizer" },
      { to: "/app/attack-campaign", icon: Crosshair, label: "Attack Campaigns" },
      { to: "/app/situation-composer", icon: Puzzle, label: "Situation Composer" },
      { to: "/app/compliance-reporter", icon: FileCheck, label: "Compliance Reporter" },
      { to: "/app/oauth-analyzer", icon: KeyRound, label: "OAuth Analyzer" },
      { to: "/app/lateral-movement", icon: GitBranch, label: "Lateral Movement" },
      { to: "/app/shadow-ai-discovery", icon: Eye, label: "Shadow AI Discovery" },
      { to: "/app/secrets-scanner", icon: Lock, label: "Secrets Scanner" },
      { to: "/app/api-security", icon: Globe, label: "API Security" },
      { to: "/app/policy-engine", icon: FileCode, label: "Policy Engine" },
      { to: "/app/cloud-posture", icon: Cloud, label: "Cloud Posture" },
      { to: "/app/container-security", icon: Container, label: "Container Security" },
      { to: "/app/supply-chain-security", icon: Package, label: "Supply Chain" },
      { to: "/app/incident-triage", icon: Siren, label: "Incident Triage" },
      { to: "/app/change-risk-analyzer", icon: GitBranch, label: "Change Risk" },
      { to: "/app/cost-anomaly", icon: DollarSign, label: "Cost Anomalies" },
      { to: "/app/adversarial-validation", icon: RefreshCw, label: "Adversarial Validation" },
      { to: "/app/mcp-gateway", icon: Plug, label: "MCP Gateway" },
      { to: "/app/service-account-tracker", icon: Users, label: "Service Accounts" },
      { to: "/app/data-classification", icon: Tag, label: "Data Classification" },
      { to: "/app/access-review", icon: ClipboardCheck, label: "Access Review" },
      { to: "/app/runbook-automation", icon: BookOpen, label: "Runbook Automation" },
      { to: "/app/capacity-planner", icon: Server, label: "Capacity Planner" },
      { to: "/app/disaster-recovery", icon: Shield, label: "Disaster Recovery" },
      { to: "/app/log-analyzer", icon: FileText, label: "Log Analyzer" },
      { to: "/app/chaos-engineering", icon: Zap, label: "Chaos Engineering" },
      { to: "/app/sla-monitor", icon: Gauge, label: "SLA Monitor" },
      { to: "/app/config-validator", icon: Settings, label: "Config Validator" },
      { to: "/app/network-segmentation", icon: Shield, label: "Network Segmentation" },
      { to: "/app/workflow-engine", icon: Workflow, label: "Workflow Engine" },
      { to: "/app/alert-correlation", icon: Layers, label: "Alert Correlation" },
      { to: "/app/performance-profiler", icon: Activity, label: "Performance Profiler" },
      { to: "/app/anomaly-detector", icon: Activity, label: "Anomaly Detector" },
      { to: "/app/certificate-manager", icon: Lock, label: "Certificate Manager" },
      { to: "/app/dns-security", icon: Globe, label: "DNS Security" },
      { to: "/app/backup-validator", icon: Database, label: "Backup Validator" },
      { to: "/app/vulnerability-manager", icon: Bug, label: "Vulnerability Manager" },
      { to: "/app/compliance-scanner", icon: FileCheck, label: "Compliance Scanner" },
      { to: "/app/threat-response", icon: Zap, label: "Threat Response" },
      { to: "/app/agent-governance", icon: ShieldCheck, label: "Agent Governance" },
      { to: "/app/model-security", icon: Lock, label: "Model Security" },
      { to: "/app/prompt-shield", icon: ShieldAlert, label: "Prompt Shield" },
      { to: "/app/multi-agent-security", icon: Network, label: "Multi-Agent Security" },
      { to: "/app/digital-twin-security", icon: Boxes, label: "Digital Twin Security" },
      { to: "/app/agentic-mdr", icon: Bot, label: "Agentic MDR" },
      { to: "/app/breakout-defender", icon: Timer, label: "Breakout Defender" },
      { to: "/app/ai-triage-accelerator", icon: Gauge, label: "AI Triage" },
      { to: "/app/cloud-risk-ranker", icon: Cloud, label: "Cloud Risk Ranker" },
      { to: "/app/data-loss-prevention", icon: ShieldAlert, label: "DLP" },
      { to: "/app/autonomous-xdr", icon: Radar, label: "Autonomous XDR" },
      { to: "/app/autonomous-soc", icon: Brain, label: "Autonomous SOC" },
      { to: "/app/cnapp-analyzer", icon: Cloud, label: "CNAPP" },
      { to: "/app/zero-trust-network", icon: Fingerprint, label: "Zero Trust" },
      { to: "/app/intelligent-soar", icon: Workflow, label: "Intelligent SOAR" },
      { to: "/app/malware-analyzer", icon: Bug, label: "Malware Analyzer" },
      { to: "/app/cyber-recovery", icon: RotateCcw, label: "Cyber Recovery" },
      { to: "/app/data-threat-hunting", icon: Search, label: "Data Threat Hunting" },
      { to: "/app/sensitive-data-monitor", icon: Eye, label: "Sensitive Data Monitor" },
      { to: "/app/identity-protection", icon: UserCheck, label: "Identity Protection" },
      { to: "/app/exposure-management", icon: Globe, label: "Exposure Mgmt" },
      { to: "/app/ai-soc-assistant", icon: MessageSquare, label: "AI SOC Assistant" },
      { to: "/app/log-intelligence", icon: FileText, label: "Log Intelligence" },
      { to: "/app/insider-threat", icon: UserX, label: "Insider Threat" },
      { to: "/app/ransomware-forensics", icon: Shield, label: "Ransomware Forensics" },
      { to: "/app/threat-intel-platform", icon: Globe, label: "Threat Intel Platform" },
      { to: "/app/code-security-scanner", icon: Code, label: "Code Security" },
      { to: "/app/data-resilience", icon: HardDrive, label: "Data Resilience" },
      { to: "/app/managed-threat-hunting", icon: Crosshair, label: "Managed Hunting" },
      { to: "/app/vulnerability-intelligence", icon: Bug, label: "Vuln Intelligence" },
      { to: "/app/file-integrity-monitor", icon: FileSearch, label: "File Integrity" },
      { to: "/app/iot-ot-security", icon: Cpu, label: "IoT/OT Security" },
      { to: "/app/security-app-builder", icon: Blocks, label: "App Builder" },
      { to: "/app/air-gap-vault", icon: Lock, label: "Air-Gap Vault" },
      { to: "/app/agent-memory-store", icon: Brain, label: "Agent Memory" },
      { to: "/app/reflection-engine", icon: RefreshCw, label: "Reflection" },
      { to: "/app/supply-chain-scanner", icon: Package, label: "Supply Chain" },
      { to: "/app/cross-vendor-correlator", icon: Layers, label: "Cross-Vendor" },
      { to: "/app/situation-manager", icon: LayoutList, label: "Situations" },
      { to: "/app/trust-relationship-mapper", icon: GitBranch, label: "Trust Map" },
      { to: "/app/it-asset-intelligence", icon: Server, label: "IT Asset Intel" },
      { to: "/app/ai-runtime-guardian", icon: ShieldCheck, label: "AI Guardian" },
      { to: "/app/data-intelligence", icon: Database, label: "Data Intelligence" },
      { to: "/app/endpoint-dlp", icon: Monitor, label: "Endpoint DLP" },
      { to: "/app/unified-cloud-security", icon: Cloud, label: "Unified Cloud" },
      { to: "/app/backup-security-posture", icon: HardDrive, label: "Backup Posture" },
    ],
  },
  {
    id: "finops",
    label: "FinOps Intelligence",
    productId: "finops",
    color: "text-emerald-400",
    items: [
      { to: "/app/cost", icon: DollarSign, label: "Cost" },
      { to: "/app/billing", icon: CreditCard, label: "Billing" },
    ],
  },
  {
    id: "compliance",
    label: "Compliance & Audit",
    productId: "compliance",
    color: "text-amber-400",
    items: [
      { to: "/app/compliance", icon: ShieldCheck, label: "Compliance" },
      { to: "/app/audit-log", icon: FileText, label: "Audit Log" },
      { to: "/app/ai-compliance", icon: Scale, label: "AI Compliance" },
    ],
  },
  {
    id: "observability",
    label: "Observability",
    color: "text-cyan-400",
    items: [
      { to: "/app/otel-pipeline", icon: Activity, label: "OTel Pipeline" },
      { to: "/app/otel-collector-manager", icon: Server, label: "Collector Mgmt" },
      { to: "/app/otel-deployer", icon: Rocket, label: "OTel Deployer" },
      { to: "/app/otel-semantic", icon: FileCheck, label: "Semantic Conv." },
      { to: "/app/tail-sampling", icon: Filter, label: "Tail Sampling" },
      { to: "/app/metrics-pipeline", icon: BarChart3, label: "Metrics Pipeline" },
      { to: "/app/logs-pipeline", icon: ScrollText, label: "Logs Pipeline" },
      { to: "/app/soc-transformation", icon: Workflow, label: "SOC Transformation" },
    ],
  },
  {
    id: "enterprise",
    label: "Enterprise",
    color: "text-sky-400",
    items: [
      { to: "/app/chatops", icon: MessageSquare, label: "ChatOps" },
      { to: "/app/integrations", icon: Plug, label: "Integrations" },
      { to: "/app/automation", icon: Zap, label: "Automation Rules" },
    ],
  },
  {
    id: "platform",
    label: "Platform",
    color: "text-gray-400",
    items: [
      { to: "/app/marketplace", icon: Store, label: "Marketplace" },
      { to: "/app/onboarding", icon: Rocket, label: "Onboarding" },
      { to: "/app/infra-as-code", icon: Code, label: "Infra as Code" },
      { to: "/app/api-keys", icon: Key, label: "API Keys" },
      { to: "/app/mcp-servers", icon: Server, label: "MCP Servers" },
      { to: "/app/settings", icon: Settings, label: "Settings" },
      { to: "/app/users", icon: Users, label: "Users" },
    ],
  },
];
