import {
  LayoutDashboard,
  Search,
  Wrench,
  BarChart3,
  Gauge,
  TrendingUp,
  HardDrive,
  Brain,
  HeartPulse,
  ShieldAlert,
  Bug,
  Layers,
  BookOpen,
  DollarSign,
  CreditCard,
  ShieldCheck,
  FileText,
  Store,
  Rocket,
  Code,
  Settings,
  Users,
  Sparkles,
  Siren,
  Activity,
  GitBranch,
  Key,
  Workflow,
  CalendarClock,
  Server,
  MessageSquare,
  Plug,
  Zap,
  Target,
  Shield,
  FileCheck,
  Filter,
  Crosshair,
  TestTube2,
  ScrollText,
  KeyRound,
  Database,
  ArrowRightLeft,
  Puzzle,
  Eye,
  Lock,
  Globe,
  FileCode,
  Cloud,
  Container,
  Package,
  ClipboardCheck,
  Tag,
  RefreshCw,
  Network,
  Boxes,
  Scale,
  Bot,
  Timer,
  Radar,
  Fingerprint,
  RotateCcw,
  UserCheck,
  UserX,
  Cpu,
  Blocks,
  LayoutList,
  Monitor,
  FileSearch,
  Wifi,
  Mail,
  Grid3X3,
  Play,
  Download,
  CheckCircle,
  Dna,
  Heart,
  ClipboardList,
  Radio,
  Smartphone,
  type LucideIcon,
} from "lucide-react";

export type ProductId = "sre" | "soc" | "finops" | "compliance" | "platform" | "api" | "marketplace";

export interface Product {
  id: ProductId;
  name: string;
  tagline: string;
  description: string;
  icon: LucideIcon;
  color: string;
  bgGradient: string;
  demoPath: string;
}

export const PRODUCTS: Record<Exclude<ProductId, "platform">, Product> = {
  sre: {
    id: "sre",
    name: "SRE Intelligence",
    tagline: "Autonomous incident response",
    description:
      "50 autonomous agents that investigate alerts, identify root causes, optimize telemetry pipelines, and learn from outcomes — across AWS, GCP, Azure, K8s, and on-prem.",
    icon: LayoutDashboard,
    color: "text-brand-400",
    bgGradient: "from-brand-600/20 to-brand-800/20",
    demoPath: "/app?demo=true",
  },
  soc: {
    id: "soc",
    name: "Security Operations",
    tagline: "AI-powered threat defense",
    description:
      "Autonomous SOC agents for threat intelligence, risk-based alerting, MITRE ATT&CK mapping, vulnerability management, and SOAR playbook orchestration.",
    icon: ShieldAlert,
    color: "text-red-400",
    bgGradient: "from-red-600/20 to-red-800/20",
    demoPath: "/app/security?demo=true",
  },
  finops: {
    id: "finops",
    name: "FinOps Intelligence",
    tagline: "Cloud cost optimization",
    description:
      "Intelligent cost analysis, budget forecasting, and resource optimization across all cloud providers.",
    icon: DollarSign,
    color: "text-emerald-400",
    bgGradient: "from-emerald-600/20 to-emerald-800/20",
    demoPath: "/app/cost?demo=true",
  },
  compliance: {
    id: "compliance",
    name: "Compliance Automation",
    tagline: "Continuous compliance assurance",
    description:
      "Automated compliance monitoring, evidence collection, audit trails, and policy enforcement across your infrastructure.",
    icon: ShieldCheck,
    color: "text-amber-400",
    bgGradient: "from-amber-600/20 to-amber-800/20",
    demoPath: "/app/compliance?demo=true",
  },
  api: {
    id: "api",
    name: "API Platform",
    tagline: "Developer-first agent APIs",
    description:
      "Expose ShieldOps capabilities as metered APIs — investigations, remediations, analytics, and more — for integration into your own tools and portals.",
    icon: Code,
    color: "text-sky-400",
    bgGradient: "from-sky-600/20 to-sky-800/20",
    demoPath: "/app/api-keys?demo=true",
  },
  marketplace: {
    id: "marketplace",
    name: "Agent Marketplace",
    tagline: "Extensible agent ecosystem",
    description:
      "Discover and deploy community-built agents, connectors, and playbooks. Publish your own and earn revenue through the marketplace.",
    icon: Store,
    color: "text-orange-400",
    bgGradient: "from-orange-600/20 to-orange-800/20",
    demoPath: "/app/marketplace?demo=true",
  },
};

export interface NavItem {
  to: string;
  icon: LucideIcon;
  label: string;
}

export interface NavGroup {
  id: string;
  label: string;
  productId?: ProductId;
  color: string;
  items: NavItem[];
}

export const NAV_GROUPS: NavGroup[] = [
  {
    id: "agent-factory",
    label: "Agent Factory",
    color: "text-brand-400",
    items: [
      { to: "/app", icon: Sparkles, label: "Agent Factory" },
      { to: "/app/war-room", icon: Siren, label: "War Rooms" },
      { to: "/app/workflows", icon: Workflow, label: "Workflows" },
      { to: "/app/agent-history", icon: Activity, label: "Agent History" },
      { to: "/app/schedules", icon: CalendarClock, label: "Schedules" },
      { to: "/app/evolution", icon: Dna, label: "Agent Evolution" },
    ],
  },
  {
    id: "sre",
    label: "SRE Intelligence",
    productId: "sre",
    color: "text-brand-400",
    items: [
      { to: "/app/fleet", icon: LayoutDashboard, label: "Fleet Overview" },
      { to: "/app/investigations", icon: Search, label: "Investigations" },
      { to: "/app/remediations", icon: Wrench, label: "Remediations" },
      { to: "/app/pipeline", icon: GitBranch, label: "Pipeline" },
      { to: "/app/analytics", icon: BarChart3, label: "Analytics" },
      { to: "/app/agent-performance", icon: Gauge, label: "Agent Perf" },
      { to: "/app/predictions", icon: TrendingUp, label: "Predictions" },
      { to: "/app/capacity", icon: HardDrive, label: "Capacity" },
      { to: "/app/learning", icon: Brain, label: "Learning" },
      { to: "/app/system-health", icon: HeartPulse, label: "System Health" },
      { to: "/app/telemetry-optimizer", icon: BarChart3, label: "Telemetry Costs" },
      { to: "/app/incident-commander", icon: Siren, label: "Incident Commander" },
    ],
  },
  {
    id: "security",
    label: "Security Operations",
    productId: "soc",
    color: "text-red-400",
    items: [
      { to: "/app/situations", icon: Target, label: "Situations" },
      { to: "/app/agent-firewall", icon: Shield, label: "Agent Firewall" },
      { to: "/app/nhi-registry", icon: KeyRound, label: "NHI Registry" },
      { to: "/app/mcp-security", icon: Plug, label: "MCP Security" },
      { to: "/app/security", icon: ShieldAlert, label: "Security" },
      { to: "/app/vulnerabilities", icon: Bug, label: "Vulnerabilities" },
      { to: "/app/incidents", icon: Layers, label: "Incident Correlation" },
      { to: "/app/playbooks", icon: BookOpen, label: "Playbooks" },
      { to: "/app/risk-scoring", icon: Target, label: "Risk Scoring" },
      { to: "/app/threat-intel", icon: Shield, label: "Threat Intel" },
      { to: "/app/compliance-audit", icon: FileCheck, label: "Compliance Audit" },
      { to: "/app/adaptive-security", icon: ShieldCheck, label: "Adaptive Security" },
      { to: "/app/security-posture", icon: ShieldAlert, label: "Security Posture" },
      { to: "/app/soar-workflow", icon: Zap, label: "SOAR Workflows" },
      { to: "/app/detection-engineering", icon: Crosshair, label: "Detection Eng." },
      { to: "/app/security-testing", icon: TestTube2, label: "Security Testing" },
      { to: "/app/threat-modeling", icon: Shield, label: "Threat Modeling" },
      { to: "/app/data-pipeline-security", icon: Database, label: "Data Pipeline Security" },
      { to: "/app/credential-lifecycle", icon: Key, label: "Credential Lifecycle" },
      { to: "/app/vendor-normalizer", icon: ArrowRightLeft, label: "Vendor Normalizer" },
      { to: "/app/attack-campaign", icon: Crosshair, label: "Attack Campaigns" },
      { to: "/app/situation-composer", icon: Puzzle, label: "Situation Composer" },
      { to: "/app/compliance-reporter", icon: FileCheck, label: "Compliance Reporter" },
      { to: "/app/oauth-analyzer", icon: KeyRound, label: "OAuth Analyzer" },
      { to: "/app/lateral-movement", icon: GitBranch, label: "Lateral Movement" },
      { to: "/app/shadow-ai-discovery", icon: Eye, label: "Shadow AI Discovery" },
      { to: "/app/secrets-scanner", icon: Lock, label: "Secrets Scanner" },
      { to: "/app/api-security", icon: Globe, label: "API Security" },
      { to: "/app/policy-engine", icon: FileCode, label: "Policy Engine" },
      { to: "/app/cloud-posture", icon: Cloud, label: "Cloud Posture" },
      { to: "/app/container-security", icon: Container, label: "Container Security" },
      { to: "/app/supply-chain-security", icon: Package, label: "Supply Chain" },
      { to: "/app/incident-triage", icon: Siren, label: "Incident Triage" },
      { to: "/app/change-risk-analyzer", icon: GitBranch, label: "Change Risk" },
      { to: "/app/cost-anomaly", icon: DollarSign, label: "Cost Anomalies" },
      { to: "/app/adversarial-validation", icon: RefreshCw, label: "Adversarial Validation" },
      { to: "/app/mcp-gateway", icon: Plug, label: "MCP Gateway" },
      { to: "/app/service-account-tracker", icon: Users, label: "Service Accounts" },
      { to: "/app/data-classification", icon: Tag, label: "Data Classification" },
      { to: "/app/access-review", icon: ClipboardCheck, label: "Access Review" },
      { to: "/app/runbook-automation", icon: BookOpen, label: "Runbook Automation" },
      { to: "/app/capacity-planner", icon: Server, label: "Capacity Planner" },
      { to: "/app/disaster-recovery", icon: Shield, label: "Disaster Recovery" },
      { to: "/app/log-analyzer", icon: FileText, label: "Log Analyzer" },
      { to: "/app/chaos-engineering", icon: Zap, label: "Chaos Engineering" },
      { to: "/app/sla-monitor", icon: Gauge, label: "SLA Monitor" },
      { to: "/app/config-validator", icon: Settings, label: "Config Validator" },
      { to: "/app/network-segmentation", icon: Shield, label: "Network Segmentation" },
      { to: "/app/workflow-engine", icon: Workflow, label: "Workflow Engine" },
      { to: "/app/alert-correlation", icon: Layers, label: "Alert Correlation" },
      { to: "/app/performance-profiler", icon: Activity, label: "Performance Profiler" },
      { to: "/app/anomaly-detector", icon: Activity, label: "Anomaly Detector" },
      { to: "/app/certificate-manager", icon: Lock, label: "Certificate Manager" },
      { to: "/app/dns-security", icon: Globe, label: "DNS Security" },
      { to: "/app/backup-validator", icon: Database, label: "Backup Validator" },
      { to: "/app/vulnerability-manager", icon: Bug, label: "Vulnerability Manager" },
      { to: "/app/compliance-scanner", icon: FileCheck, label: "Compliance Scanner" },
      { to: "/app/threat-response", icon: Zap, label: "Threat Response" },
      { to: "/app/agent-governance", icon: ShieldCheck, label: "Agent Governance" },
      { to: "/app/model-security", icon: Lock, label: "Model Security" },
      { to: "/app/prompt-shield", icon: ShieldAlert, label: "Prompt Shield" },
      { to: "/app/multi-agent-security", icon: Network, label: "Multi-Agent Security" },
      { to: "/app/digital-twin-security", icon: Boxes, label: "Digital Twin Security" },
      { to: "/app/agentic-mdr", icon: Bot, label: "Agentic MDR" },
      { to: "/app/breakout-defender", icon: Timer, label: "Breakout Defender" },
      { to: "/app/ai-triage-accelerator", icon: Gauge, label: "AI Triage" },
      { to: "/app/cloud-risk-ranker", icon: Cloud, label: "Cloud Risk Ranker" },
      { to: "/app/data-loss-prevention", icon: ShieldAlert, label: "DLP" },
      { to: "/app/autonomous-xdr", icon: Radar, label: "Autonomous XDR" },
      { to: "/app/autonomous-soc", icon: Brain, label: "Autonomous SOC" },
      { to: "/app/cnapp-analyzer", icon: Cloud, label: "CNAPP" },
      { to: "/app/zero-trust-network", icon: Fingerprint, label: "Zero Trust" },
      { to: "/app/intelligent-soar", icon: Workflow, label: "Intelligent SOAR" },
      { to: "/app/malware-analyzer", icon: Bug, label: "Malware Analyzer" },
      { to: "/app/cyber-recovery", icon: RotateCcw, label: "Cyber Recovery" },
      { to: "/app/data-threat-hunting", icon: Search, label: "Data Threat Hunting" },
      { to: "/app/sensitive-data-monitor", icon: Eye, label: "Sensitive Data Monitor" },
      { to: "/app/identity-protection", icon: UserCheck, label: "Identity Protection" },
      { to: "/app/exposure-management", icon: Globe, label: "Exposure Mgmt" },
      { to: "/app/ai-soc-assistant", icon: MessageSquare, label: "AI SOC Assistant" },
      { to: "/app/log-intelligence", icon: FileText, label: "Log Intelligence" },
      { to: "/app/insider-threat", icon: UserX, label: "Insider Threat" },
      { to: "/app/ransomware-forensics", icon: Shield, label: "Ransomware Forensics" },
      { to: "/app/threat-intel-platform", icon: Globe, label: "Threat Intel Platform" },
      { to: "/app/code-security-scanner", icon: Code, label: "Code Security" },
      { to: "/app/data-resilience", icon: HardDrive, label: "Data Resilience" },
      { to: "/app/managed-threat-hunting", icon: Crosshair, label: "Managed Hunting" },
      { to: "/app/vulnerability-intelligence", icon: Bug, label: "Vuln Intelligence" },
      { to: "/app/file-integrity-monitor", icon: FileSearch, label: "File Integrity" },
      { to: "/app/iot-ot-security", icon: Cpu, label: "IoT/OT Security" },
      { to: "/app/security-app-builder", icon: Blocks, label: "App Builder" },
      { to: "/app/air-gap-vault", icon: Lock, label: "Air-Gap Vault" },
      { to: "/app/agent-memory-store", icon: Brain, label: "Agent Memory" },
      { to: "/app/reflection-engine", icon: RefreshCw, label: "Reflection" },
      { to: "/app/supply-chain-scanner", icon: Package, label: "Supply Chain" },
      { to: "/app/cross-vendor-correlator", icon: Layers, label: "Cross-Vendor" },
      { to: "/app/situation-manager", icon: LayoutList, label: "Situations" },
      { to: "/app/trust-relationship-mapper", icon: GitBranch, label: "Trust Map" },
      { to: "/app/it-asset-intelligence", icon: Server, label: "IT Asset Intel" },
      { to: "/app/ai-runtime-guardian", icon: ShieldCheck, label: "AI Guardian" },
      { to: "/app/data-intelligence", icon: Database, label: "Data Intelligence" },
      { to: "/app/endpoint-dlp", icon: Monitor, label: "Endpoint DLP" },
      { to: "/app/unified-cloud-security", icon: Cloud, label: "Unified Cloud" },
      { to: "/app/backup-security-posture", icon: HardDrive, label: "Backup Posture" },
      { to: "/app/network-pentest", icon: Wifi, label: "Network Pentest" },
      { to: "/app/web-app-scanner", icon: Globe, label: "Web App Scanner" },
      { to: "/app/cloud-pentest", icon: Cloud, label: "Cloud Pentest" },
      { to: "/app/api-pentest", icon: Plug, label: "API Pentest" },
      { to: "/app/credential-tester", icon: Key, label: "Credential Tester" },
      { to: "/app/phishing-simulator", icon: Mail, label: "Phishing Simulator" },
      { to: "/app/patch-orchestrator", icon: Download, label: "Patch Orchestrator" },
      { to: "/app/config-remediation", icon: Settings, label: "Config Remediation" },
      { to: "/app/access-remediation", icon: Users, label: "Access Remediation" },
      { to: "/app/vulnerability-remediation", icon: Wrench, label: "Vuln Remediation" },
      { to: "/app/remediation-verifier", icon: CheckCircle, label: "Remediation Verifier" },
      { to: "/app/remediation-orchestrator", icon: Workflow, label: "Remediation Pipeline" },
      { to: "/app/mitre-coverage", icon: Grid3X3, label: "MITRE Coverage" },
      { to: "/app/detection-gaps", icon: Search, label: "Detection Gaps" },
      { to: "/app/security-scorecard", icon: BarChart3, label: "Security Scorecard" },
      { to: "/app/compliance-gaps", icon: Scale, label: "Compliance Gaps" },
      { to: "/app/attack-readiness", icon: Crosshair, label: "Attack Readiness" },
      { to: "/app/executive-reports", icon: FileText, label: "Executive Reports" },
      { to: "/app/security-pipeline", icon: Workflow, label: "Security Pipeline" },
      { to: "/app/finding-correlator", icon: Layers, label: "Finding Correlator" },
      { to: "/app/auto-tickets", icon: Plug, label: "Auto Tickets" },
      { to: "/app/continuous-scanner", icon: RefreshCw, label: "Continuous Scanner" },
      { to: "/app/risk-prioritizer", icon: Target, label: "Risk Prioritizer" },
      { to: "/app/security-dashboard-agg", icon: LayoutDashboard, label: "CISO Dashboard" },
      { to: "/app/apt-emulator", icon: Crosshair, label: "APT Emulator" },
      { to: "/app/purple-team", icon: Users, label: "Purple Team" },
      { to: "/app/threat-scenarios", icon: Play, label: "Threat Scenarios" },
      { to: "/app/fleet-optimizer", icon: Cpu, label: "Fleet Optimizer" },
      { to: "/app/security-data-lake", icon: Database, label: "Data Lake" },
      { to: "/app/agent-factory", icon: Blocks, label: "Agent Factory" },
      { to: "/app/ir-playbook", icon: BookOpen, label: "IR Playbook" },
      { to: "/app/incident-communicator", icon: MessageSquare, label: "Incident Comms" },
      { to: "/app/evidence-collector", icon: FileSearch, label: "Evidence Collector" },
      { to: "/app/post-incident-analyzer", icon: Search, label: "Post-Incident" },
      { to: "/app/incident-simulator", icon: Play, label: "Incident Simulator" },
      { to: "/app/threat-feed-manager", icon: Globe, label: "Threat Feeds" },
      { to: "/app/ioc-lifecycle", icon: Target, label: "IOC Lifecycle" },
      { to: "/app/threat-attribution", icon: Crosshair, label: "Threat Attribution" },
      { to: "/app/security-awareness", icon: Users, label: "Security Awareness" },
      { to: "/app/compliance-workflow", icon: ClipboardCheck, label: "Compliance Workflow" },
      { to: "/app/governance-dashboard", icon: LayoutDashboard, label: "Governance" },
      { to: "/app/data-encryption-monitor", icon: Lock, label: "Encryption Monitor" },
      { to: "/app/privilege-escalation", icon: ShieldAlert, label: "Privilege Escalation" },
      { to: "/app/session-hijack", icon: Eye, label: "Session Hijack" },
      { to: "/app/api-rate-limiter", icon: Gauge, label: "API Rate Limiter" },
      { to: "/app/vulnerability-lifecycle", icon: Bug, label: "Vuln Lifecycle" },
      { to: "/app/asset-inventory", icon: Server, label: "Asset Inventory" },
      { to: "/app/network-traffic-analyzer", icon: Activity, label: "Traffic Analyzer" },
      { to: "/app/firewall-rule-auditor", icon: Shield, label: "Firewall Auditor" },
      { to: "/app/waf-manager", icon: ShieldAlert, label: "WAF Manager" },
      { to: "/app/packet-inspector", icon: Search, label: "Packet Inspector" },
      { to: "/app/network-forensics", icon: FileSearch, label: "Network Forensics" },
      { to: "/app/bandwidth-anomaly", icon: TrendingUp, label: "Bandwidth Anomaly" },
      { to: "/app/sast-scanner", icon: Code, label: "SAST Scanner" },
      { to: "/app/dast-runner", icon: Zap, label: "DAST Runner" },
      { to: "/app/sca-dependency", icon: Package, label: "SCA Dependencies" },
      { to: "/app/container-image-scanner", icon: Container, label: "Image Scanner" },
      { to: "/app/iac-security-scanner", icon: FileText, label: "IaC Scanner" },
      { to: "/app/secrets-in-code", icon: Key, label: "Secrets Detector" },
      { to: "/app/endpoint-behavior", icon: Monitor, label: "Endpoint Behavior" },
      { to: "/app/mobile-device-manager", icon: Cpu, label: "Mobile MDM" },
      { to: "/app/browser-isolation", icon: Globe, label: "Browser Isolation" },
      { to: "/app/usb-device-controller", icon: HardDrive, label: "USB Controller" },
      { to: "/app/patch-compliance", icon: CheckCircle, label: "Patch Compliance" },
      { to: "/app/endpoint-forensics", icon: Search, label: "Endpoint Forensics" },
      { to: "/app/cloud-audit-logger", icon: FileText, label: "Cloud Audit" },
      { to: "/app/serverless-security", icon: Zap, label: "Serverless Security" },
      { to: "/app/cloud-workload-protector", icon: Shield, label: "Workload Protection" },
      { to: "/app/multi-cloud-compliance", icon: Cloud, label: "Multi-Cloud Compliance" },
      { to: "/app/cloud-identity-federation", icon: Users, label: "Identity Federation" },
      { to: "/app/cloud-storage-scanner", icon: Database, label: "Storage Scanner" },
      { to: "/app/email-gateway", icon: Mail, label: "Email Gateway" },
      { to: "/app/phishing-email", icon: AlertTriangle, label: "Phishing Analyzer" },
      { to: "/app/spam-filter", icon: Shield, label: "Spam Filter" },
      { to: "/app/email-dlp", icon: Lock, label: "Email DLP" },
      { to: "/app/communication-auditor", icon: MessageSquare, label: "Comms Auditor" },
      { to: "/app/social-engineering", icon: Users, label: "Social Engineering" },
      { to: "/app/gdpr-processor", icon: Scale, label: "GDPR Processor" },
      { to: "/app/hipaa-monitor", icon: HeartPulse, label: "HIPAA Monitor" },
      { to: "/app/pci-scanner", icon: CreditCard, label: "PCI Scanner" },
      { to: "/app/sox-auditor", icon: FileCheck, label: "SOX Auditor" },
      { to: "/app/iso27001-assessor", icon: ClipboardCheck, label: "ISO 27001" },
      { to: "/app/nist-framework", icon: LayoutDashboard, label: "NIST Framework" },
      { to: "/app/model-drift", icon: TrendingUp, label: "Model Drift" },
      { to: "/app/training-data", icon: Database, label: "Training Data" },
      { to: "/app/inference-attack", icon: Zap, label: "Inference Attack" },
      { to: "/app/model-explainability", icon: Brain, label: "Explainability" },
      { to: "/app/ai-bias", icon: Scale, label: "AI Bias Scanner" },
      { to: "/app/federated-learning", icon: Network, label: "Federated Learning" },
      { to: "/app/physical-access", icon: Lock, label: "Physical Access" },
      { to: "/app/cctv-analytics", icon: Eye, label: "CCTV Analytics" },
      { to: "/app/environmental-monitor", icon: Activity, label: "Environmental" },
      { to: "/app/scada-security", icon: Cpu, label: "SCADA Security" },
      { to: "/app/industrial-protocol", icon: Network, label: "Industrial Protocol" },
      { to: "/app/building-management", icon: Server, label: "Building Mgmt" },
      { to: "/app/dark-web-monitor", icon: Globe, label: "Dark Web Monitor" },
      { to: "/app/brand-protection", icon: Shield, label: "Brand Protection" },
      { to: "/app/threat-landscape", icon: Globe, label: "Threat Landscape" },
      { to: "/app/kill-chain", icon: Target, label: "Kill Chain" },
      { to: "/app/adversary-emulator", icon: Crosshair, label: "Adversary Emulator" },
      { to: "/app/hunt-hypotheses", icon: Search, label: "Hunt Hypotheses" },
      { to: "/app/alert-enrichment", icon: Bell, label: "Alert Enrichment" },
      { to: "/app/ticket-automation", icon: Layers, label: "Ticket Automation" },
      { to: "/app/shift-handoff", icon: Users, label: "Shift Handoff" },
      { to: "/app/soc-metrics", icon: BarChart3, label: "SOC Metrics" },
      { to: "/app/playbook-optimizer", icon: BookOpen, label: "Playbook Optimizer" },
      { to: "/app/war-gaming", icon: Crosshair, label: "War Gaming" },
      { to: "/app/data-masking", icon: Lock, label: "Data Masking" },
      { to: "/app/tokenization", icon: Key, label: "Tokenization" },
      { to: "/app/privacy-impact", icon: Scale, label: "Privacy Impact" },
      { to: "/app/data-lineage", icon: GitBranch, label: "Data Lineage" },
      { to: "/app/consent-manager", icon: CheckCircle, label: "Consent Manager" },
      { to: "/app/breach-response", icon: AlertTriangle, label: "Breach Response" },
      { to: "/app/zero-trust-validator", icon: Shield, label: "Zero Trust" },
      { to: "/app/micro-segmentation", icon: Network, label: "Micro Segmentation" },
      { to: "/app/architecture-review", icon: Layers, label: "Architecture Review" },
      { to: "/app/threat-surface", icon: Target, label: "Threat Surface" },
      { to: "/app/defense-in-depth", icon: Shield, label: "Defense In Depth" },
      { to: "/app/control-mapper", icon: LayoutDashboard, label: "Control Mapper" },
      { to: "/app/vendor-risk", icon: Shield, label: "Vendor Risk" },
      { to: "/app/sbom-analyzer", icon: Package, label: "SBOM Analyzer" },
      { to: "/app/dependency-graph", icon: GitBranch, label: "Dependency Graph" },
      { to: "/app/license-scanner", icon: Scale, label: "License Scanner" },
      { to: "/app/artifact-integrity", icon: CheckCircle, label: "Artifact Integrity" },
      { to: "/app/cicd-security", icon: Workflow, label: "CI/CD Security" },
      { to: "/app/mfa-compliance", icon: Key, label: "MFA Compliance" },
      { to: "/app/orphan-accounts", icon: Users, label: "Orphan Accounts" },
      { to: "/app/permission-creep", icon: Shield, label: "Permission Creep" },
      { to: "/app/jit-access", icon: Clock, label: "JIT Access" },
      { to: "/app/credential-rotation", icon: RefreshCw, label: "Credential Rotation" },
      { to: "/app/session-recorder", icon: Eye, label: "Session Recorder" },
      { to: "/app/incident-prediction", icon: TrendingUp, label: "Incident Prediction" },
      { to: "/app/incident-cost", icon: DollarSign, label: "Incident Cost" },
      { to: "/app/incident-similarity", icon: Layers, label: "Incident Similarity" },
      { to: "/app/threat-brief", icon: FileText, label: "Threat Brief" },
      { to: "/app/sla-predictor", icon: Gauge, label: "SLA Predictor" },
      { to: "/app/runbook-kb", icon: BookOpen, label: "Runbook KB" },
      { to: "/app/quantum-risk", icon: Cpu, label: "Quantum Risk" },
      { to: "/app/crypto-agility", icon: RefreshCw, label: "Crypto Agility" },
      { to: "/app/key-lifecycle", icon: Key, label: "Key Lifecycle" },
      { to: "/app/privacy-engineering", icon: Lock, label: "Privacy Engineering" },
      { to: "/app/data-sovereignty", icon: Globe, label: "Data Sovereignty" },
      { to: "/app/deepfake-detector", icon: Eye, label: "Deepfake Detector" },
      { to: "/app/threat-correlation", icon: Layers, label: "Threat Correlation" },
      { to: "/app/security-copilot", icon: MessageSquare, label: "Security Copilot" },
      { to: "/app/compliance-automation", icon: FileCheck, label: "Compliance Auto" },
      { to: "/app/playbook-generator", icon: BookOpen, label: "Playbook Generator" },
      { to: "/app/attack-path", icon: Target, label: "Attack Paths" },
      { to: "/app/security-metrics", icon: BarChart3, label: "Security Metrics" },
      { to: "/app/threat-feed-aggregator", icon: Globe, label: "Threat Feeds" },
      { to: "/app/ioc-enrichment", icon: Search, label: "IOC Enrichment" },
      { to: "/app/response-automation", icon: Zap, label: "Response Automation" },
      { to: "/app/risk-quantification", icon: Scale, label: "Risk Quantification" },
      { to: "/app/awareness-trainer", icon: Users, label: "Awareness Training" },
      { to: "/app/threat-hunt-automation", icon: Crosshair, label: "Hunt Automation" },
      { to: "/app/api-gateway-security", icon: Globe, label: "API Gateway" },
      { to: "/app/session-manager", icon: Key, label: "Session Manager" },
      { to: "/app/rate-limit-enforcer", icon: Gauge, label: "Rate Limiter" },
      { to: "/app/health-orchestrator", icon: HeartPulse, label: "Health Orchestrator" },
      { to: "/app/config-auditor", icon: Settings, label: "Config Auditor" },
      { to: "/app/deployment-guardian", icon: Rocket, label: "Deploy Guardian" },
      { to: "/app/behavioral-analytics", icon: Activity, label: "Behavioral UEBA" },
      { to: "/app/anomaly-prediction", icon: TrendingUp, label: "Anomaly Prediction" },
      { to: "/app/root-cause", icon: Search, label: "Root Cause" },
      { to: "/app/capacity-intelligence", icon: Server, label: "Capacity Intel" },
      { to: "/app/service-dependencies", icon: Network, label: "Service Deps" },
      { to: "/app/performance-baselines", icon: BarChart3, label: "Perf Baselines" },
      { to: "/app/regulatory-changes", icon: FileText, label: "Regulatory Changes" },
      { to: "/app/evidence-automation", icon: FileCheck, label: "Evidence Auto" },
      { to: "/app/vendor-compliance", icon: Shield, label: "Vendor Compliance" },
      { to: "/app/data-retention", icon: Database, label: "Data Retention" },
      { to: "/app/privacy-consent", icon: CheckCircle, label: "Privacy Consent" },
      { to: "/app/audit-trail-analyzer", icon: FileSearch, label: "Audit Trail" },
      { to: "/app/incident-escalation", icon: Siren, label: "Escalation Engine" },
      { to: "/app/war-room-automator", icon: Users, label: "War Room Auto" },
      { to: "/app/stakeholder-notifier", icon: MessageSquare, label: "Stakeholder Notify" },
      { to: "/app/postmortem-generator", icon: FileText, label: "Postmortem Gen" },
      { to: "/app/sla-violations", icon: Gauge, label: "SLA Violations" },
      { to: "/app/oncall-optimizer", icon: CalendarClock, label: "On-Call Optimizer" },
      { to: "/app/cloud-cost-optimizer", icon: DollarSign, label: "Cloud Cost Opt" },
      { to: "/app/infra-drift", icon: GitBranch, label: "Infra Drift" },
      { to: "/app/resource-rightsizer", icon: Server, label: "Rightsizer" },
      { to: "/app/multi-cloud-orchestrator", icon: Cloud, label: "Multi-Cloud Orch" },
      { to: "/app/cloud-migration-planner", icon: Rocket, label: "Migration Planner" },
      { to: "/app/finops-forecaster", icon: TrendingUp, label: "FinOps Forecast" },
      { to: "/app/predictive-scaler", icon: Activity, label: "Predictive Scaler" },
      { to: "/app/service-health-monitor", icon: Heart, label: "Service Health" },
      { to: "/app/cloud-workload-protector", icon: Shield, label: "Workload Protect" },
      { to: "/app/compliance-workflow", icon: ClipboardList, label: "Compliance Flow" },
      { to: "/app/compliance-gap-analyzer", icon: Target, label: "Gap Analyzer" },
      { to: "/app/network-traffic-analyzer", icon: Network, label: "Traffic Analyzer" },
      { to: "/app/secret-rotation-manager", icon: KeyRound, label: "Secret Rotation" },
      { to: "/app/incident-playbook-engine", icon: Workflow, label: "Playbook Engine" },
      { to: "/app/cloud-storage-scanner", icon: Database, label: "Storage Scanner" },
      { to: "/app/threat-feed-aggregator", icon: Radar, label: "Threat Feeds" },
      { to: "/app/iam-policy-analyzer", icon: UserCheck, label: "IAM Analyzer" },
      { to: "/app/observability-pipeline-optimizer", icon: Filter, label: "OTel Optimizer" },
      { to: "/app/database-security-scanner", icon: Database, label: "DB Scanner" },
      { to: "/app/endpoint-protection-manager", icon: Monitor, label: "Endpoint Protect" },
      { to: "/app/security-awareness-engine", icon: BookOpen, label: "Awareness" },
      { to: "/app/vulnerability-prioritizer", icon: Target, label: "Vuln Prioritizer" },
      { to: "/app/data-pipeline-protector", icon: Database, label: "Pipeline Protect" },
      { to: "/app/cloud-permission-auditor", icon: Lock, label: "Perm Auditor" },
      { to: "/app/incident-timeline-builder", icon: Activity, label: "Timeline Builder" },
      { to: "/app/soc-metrics-analyzer", icon: BarChart3, label: "SOC Metrics" },
      { to: "/app/automated-pentest", icon: Crosshair, label: "Auto Pentest" },
      { to: "/app/attack-surface-mapper", icon: Globe, label: "Attack Surface" },
      { to: "/app/dns-threat-analyzer", icon: Globe, label: "DNS Threats" },
      { to: "/app/certificate-lifecycle", icon: Lock, label: "Cert Lifecycle" },
      { to: "/app/security-config-assessor", icon: Settings, label: "Config Assessor" },
      { to: "/app/cloud-network-firewall", icon: Network, label: "Cloud Firewall" },
      { to: "/app/threat-hunt-orchestrator", icon: Crosshair, label: "Threat Hunt" },
      { to: "/app/email-security-gateway", icon: Mail, label: "Email Security" },
      { to: "/app/firmware-security-scanner", icon: Cpu, label: "Firmware Scanner" },
      { to: "/app/threat-intel-fusion", icon: Radio, label: "Threat Intel Fusion" },
      { to: "/app/api-abuse-detector", icon: ShieldAlert, label: "API Abuse" },
      { to: "/app/cloud-secret-vault", icon: KeyRound, label: "Secret Vault" },
      { to: "/app/compliance-evidence-collector", icon: ClipboardCheck, label: "Evidence Collector" },
      { to: "/app/network-traffic-inspector", icon: Activity, label: "Traffic Inspector" },
      { to: "/app/security-training-platform", icon: BookOpen, label: "Training Platform" },
      { to: "/app/container-runtime-protector", icon: Container, label: "Runtime Protector" },
      { to: "/app/data-exfiltration-monitor", icon: Eye, label: "Exfil Monitor" },
      { to: "/app/browser-threat-protector", icon: Globe, label: "Browser Protect" },
      { to: "/app/identity-threat-detector", icon: Fingerprint, label: "Identity ITDR" },
      { to: "/app/security-orchestration-hub", icon: Workflow, label: "Security Orch Hub" },
      { to: "/app/privilege-access-monitor", icon: KeyRound, label: "PAM Monitor" },
      { to: "/app/vulnerability-correlation-engine", icon: Layers, label: "Vuln Correlation" },
      { to: "/app/cloud-workload-inspector", icon: Cloud, label: "Workload Inspector" },
      { to: "/app/log-anomaly-detector", icon: Search, label: "Log Anomalies" },
      { to: "/app/mobile-threat-defender", icon: Smartphone, label: "Mobile Defense" },
      { to: "/app/cloud-entitlement-manager", icon: Key, label: "Cloud Entitlement" },
      { to: "/app/security-chaos-tester", icon: Zap, label: "Security Chaos" },
      { to: "/app/wireless-security-auditor", icon: Wifi, label: "Wireless Audit" },
      { to: "/app/ml-model-scanner", icon: Cpu, label: "ML Model Scanner" },
      { to: "/app/data-privacy-scanner", icon: Database, label: "Privacy Scanner" },
      { to: "/app/kubernetes-policy-engine", icon: Server, label: "K8s Policy Engine" },
      { to: "/app/siem-rule-optimizer", icon: Filter, label: "SIEM Optimizer" },
      { to: "/app/third-party-risk-monitor", icon: Globe, label: "Vendor Risk Monitor" },
      { to: "/app/shadow-api-detector", icon: Eye, label: "Shadow API Detector" },
      { to: "/app/security-data-mesh", icon: Database, label: "Security Data Mesh" },
      { to: "/app/attack-narrative-builder", icon: BookOpen, label: "Attack Narrative" },
      { to: "/app/agentless-scanner", icon: Cloud, label: "Agentless Scanner" },
      { to: "/app/toxic-combination-detector", icon: ShieldAlert, label: "Toxic Combos" },
      { to: "/app/autonomous-response-engine", icon: Bot, label: "Auto Response" },
      { to: "/app/dependency-vulnerability-tracker", icon: Package, label: "Dep Vuln Tracker" },
      { to: "/app/security-budget-optimizer", icon: DollarSign, label: "Budget Optimizer" },
      { to: "/app/cloud-drift-remediator", icon: GitBranch, label: "Drift Remediator" },
      { to: "/app/cloud-key-manager", icon: Key, label: "Key Manager" },
      { to: "/app/security-posture-scorer", icon: Gauge, label: "Posture Scorer" },
      { to: "/app/alert-fatigue-reducer", icon: Filter, label: "Alert Fatigue" },
    ],
  },
  {
    id: "finops",
    label: "FinOps Intelligence",
    productId: "finops",
    color: "text-emerald-400",
    items: [
      { to: "/app/cost", icon: DollarSign, label: "Cost" },
      { to: "/app/billing", icon: CreditCard, label: "Billing" },
    ],
  },
  {
    id: "compliance",
    label: "Compliance & Audit",
    productId: "compliance",
    color: "text-amber-400",
    items: [
      { to: "/app/compliance", icon: ShieldCheck, label: "Compliance" },
      { to: "/app/audit-log", icon: FileText, label: "Audit Log" },
      { to: "/app/ai-compliance", icon: Scale, label: "AI Compliance" },
      { to: "/app/regulatory-change-monitor", icon: FileText, label: "Regulatory Monitor" },
    ],
  },
  {
    id: "observability",
    label: "Observability",
    color: "text-cyan-400",
    items: [
      { to: "/app/otel-pipeline", icon: Activity, label: "OTel Pipeline" },
      { to: "/app/otel-collector-manager", icon: Server, label: "Collector Mgmt" },
      { to: "/app/otel-deployer", icon: Rocket, label: "OTel Deployer" },
      { to: "/app/otel-semantic", icon: FileCheck, label: "Semantic Conv." },
      { to: "/app/tail-sampling", icon: Filter, label: "Tail Sampling" },
      { to: "/app/metrics-pipeline", icon: BarChart3, label: "Metrics Pipeline" },
      { to: "/app/logs-pipeline", icon: ScrollText, label: "Logs Pipeline" },
      { to: "/app/soc-transformation", icon: Workflow, label: "SOC Transformation" },
    ],
  },
  {
    id: "enterprise",
    label: "Enterprise",
    color: "text-sky-400",
    items: [
      { to: "/app/chatops", icon: MessageSquare, label: "ChatOps" },
      { to: "/app/integrations", icon: Plug, label: "Integrations" },
      { to: "/app/automation", icon: Zap, label: "Automation Rules" },
      { to: "/app/dns-firewall-controller", icon: Shield, label: "DNS Firewall" },
      { to: "/app/saas-security-posture", icon: Cloud, label: "SaaS Security" },
      { to: "/app/event-stream-processor", icon: Zap, label: "Event Streams" },
      { to: "/app/deception-network-manager", icon: Target, label: "Deception Network" },
      { to: "/app/backup-integrity-verifier", icon: HardDrive, label: "Backup Integrity" },
      { to: "/app/incident-cost-tracker", icon: DollarSign, label: "Incident Costs" },
      { to: "/app/threat-simulation-engine", icon: Target, label: "Threat Simulation" },
      { to: "/app/policy-compliance-enforcer", icon: Scale, label: "Policy Enforcer" },
      { to: "/app/secret-sprawl-detector", icon: KeyRound, label: "Secret Sprawl" },
    ],
  },
  {
    id: "platform",
    label: "Platform",
    color: "text-gray-400",
    items: [
      { to: "/app/marketplace", icon: Store, label: "Marketplace" },
      { to: "/app/onboarding", icon: Rocket, label: "Onboarding" },
      { to: "/app/infra-as-code", icon: Code, label: "Infra as Code" },
      { to: "/app/api-keys", icon: Key, label: "API Keys" },
      { to: "/app/mcp-servers", icon: Server, label: "MCP Servers" },
      { to: "/app/settings", icon: Settings, label: "Settings" },
      { to: "/app/users", icon: Users, label: "Users" },
    ],
  },
];
