# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the brand_protection_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.brand_protection_scanner.models import BrandProtectionScannerState
from shieldops.agents.brand_protection_scanner.nodes import (
    analyze_similarity,
    check_certificates,
    classify_threats,
    discover_domains,
    report,
    takedown,
)
from shieldops.agents.brand_protection_scanner.tools import BrandProtectionScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class BrandProtectionScannerAgent(Agent):
    """Declarative spec for ``brand_protection_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "brand_protection_scanner"
    state_model = BrandProtectionScannerState
    toolkit_factory = BrandProtectionScannerToolkit

    nodes = {
        "discover_domains": discover_domains,
        "analyze_similarity": analyze_similarity,
        "check_certificates": check_certificates,
        "classify_threats": classify_threats,
        "takedown": takedown,
        "report": report,
    }

    edges = [
        edge("takedown", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_domains" via _check_error()
        # TODO: cond(...) from "analyze_similarity" via _check_error()
        # TODO: cond(...) from "check_certificates" via _check_error()
        # TODO: cond(...) from "classify_threats" via _check_error()
    ]

    entry = "discover_domains"
