# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the config_remediation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.config_remediation.models import ConfigRemediationState
from shieldops.agents.config_remediation.nodes import (
    apply_fixes,
    generate_fixes,
    generate_report,
    identify_misconfigs,
    scan_configurations,
    verify_fixes,
)
from shieldops.agents.config_remediation.tools import ConfigRemediationToolkit
from shieldops.agents.runtime import END, Agent, edge


class ConfigRemediationAgent(Agent):
    """Declarative spec for ``config_remediation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "config_remediation"
    state_model = ConfigRemediationState
    toolkit_factory = ConfigRemediationToolkit

    nodes = {
        "scan_configurations": scan_configurations,
        "identify_misconfigs": identify_misconfigs,
        "generate_fixes": generate_fixes,
        "apply_fixes": apply_fixes,
        "verify_fixes": verify_fixes,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_configurations", "identify_misconfigs"),
        edge("identify_misconfigs", "generate_fixes"),
        edge("generate_fixes", "apply_fixes"),
        edge("apply_fixes", "verify_fixes"),
        edge("verify_fixes", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "scan_configurations"
