# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_onboarding_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_onboarding_engine.models import SecurityOnboardingEngineState
from shieldops.agents.security_onboarding_engine.nodes import (
    assess_risk_profile,
    generate_report,
    generate_requirements,
    intake_service,
    provision_controls,
    validate_onboarding,
)
from shieldops.agents.security_onboarding_engine.tools import SecurityOnboardingEngineToolkit


class SecurityOnboardingEngineAgent(Agent):
    """Declarative spec for ``security_onboarding_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_onboarding_engine"
    state_model = SecurityOnboardingEngineState
    toolkit_factory = SecurityOnboardingEngineToolkit

    nodes = {
        "intake_service": intake_service,
        "assess_risk_profile": assess_risk_profile,
        "generate_requirements": generate_requirements,
        "provision_controls": provision_controls,
        "validate_onboarding": validate_onboarding,
        "generate_report": generate_report,
    }

    edges = [
        edge("intake_service", "assess_risk_profile"),
        edge("assess_risk_profile", "generate_requirements"),
        edge("generate_requirements", "provision_controls"),
        edge("validate_onboarding", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "provision_controls"
        #   routed by _should_validate() — wrap with cond(...)
    ]

    entry = "intake_service"
