# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the risk_quantification_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.risk_quantification_engine.models import RiskQuantificationEngineState
from shieldops.agents.risk_quantification_engine.nodes import (
    calculate_exposure,
    estimate_loss,
    identify_assets,
    model_threats,
    prioritize_risks,
    report,
)
from shieldops.agents.risk_quantification_engine.tools import RiskQuantificationEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class RiskQuantificationEngineAgent(Agent):
    """Declarative spec for ``risk_quantification_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "risk_quantification_engine"
    state_model = RiskQuantificationEngineState
    toolkit_factory = RiskQuantificationEngineToolkit

    nodes = {
        "identify_assets": identify_assets,
        "model_threats": model_threats,
        "calculate_exposure": calculate_exposure,
        "estimate_loss": estimate_loss,
        "prioritize_risks": prioritize_risks,
        "report": report,
    }

    edges = [
        edge("prioritize_risks", "report"),
        edge("report", END),
        # TODO: cond(...) from "identify_assets" via _check_error()
        # TODO: cond(...) from "model_threats" via _check_error()
        # TODO: cond(...) from "calculate_exposure" via _check_error()
        # TODO: cond(...) from "estimate_loss" via _check_error()
    ]

    entry = "identify_assets"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``RiskQuantificationEngineRunner`` keep working via this alias; new code
# should use ``RiskQuantificationEngineAgent`` directly through AgentRuntime.
RiskQuantificationEngineRunner = RiskQuantificationEngineAgent
