# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the shift_handoff_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.shift_handoff_manager.models import ShiftHandoffManagerState
from shieldops.agents.shift_handoff_manager.nodes import (
    brief_incoming,
    collect_state,
    document_actions,
    report,
    summarize_incidents,
    transfer,
)
from shieldops.agents.shift_handoff_manager.tools import ShiftHandoffManagerToolkit


class ShiftHandoffManagerAgent(Agent):
    """Declarative spec for ``shift_handoff_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "shift_handoff_manager"
    state_model = ShiftHandoffManagerState
    toolkit_factory = ShiftHandoffManagerToolkit

    nodes = {
        "collect_state": collect_state,
        "summarize_incidents": summarize_incidents,
        "document_actions": document_actions,
        "brief_incoming": brief_incoming,
        "transfer": transfer,
        "report": report,
    }

    edges = [
        edge("transfer", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_state" via _check_error()
        # TODO: cond(...) from "summarize_incidents" via _check_error()
        # TODO: cond(...) from "document_actions" via _check_error()
        # TODO: cond(...) from "brief_incoming" via _check_error()
    ]

    entry = "collect_state"
