# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the nist_framework_mapper agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.nist_framework_mapper.models import NISTFrameworkMapperState
from shieldops.agents.nist_framework_mapper.nodes import (
    assess_categories,
    identify_gaps,
    map_functions,
    recommend,
    report,
    score_maturity,
)
from shieldops.agents.nist_framework_mapper.tools import NISTFrameworkMapperToolkit
from shieldops.agents.runtime import END, Agent, edge


class NistFrameworkMapperAgent(Agent):
    """Declarative spec for ``nist_framework_mapper`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "nist_framework_mapper"
    state_model = NISTFrameworkMapperState
    toolkit_factory = NISTFrameworkMapperToolkit

    nodes = {
        "map_functions": map_functions,
        "assess_categories": assess_categories,
        "score_maturity": score_maturity,
        "identify_gaps": identify_gaps,
        "recommend": recommend,
        "report": report,
    }

    edges = [
        edge("recommend", "report"),
        edge("report", END),
        # TODO: cond(...) from "map_functions" via _check_error()
        # TODO: cond(...) from "assess_categories" via _check_error()
        # TODO: cond(...) from "score_maturity" via _check_error()
        # TODO: cond(...) from "identify_gaps" via _check_error()
    ]

    entry = "map_functions"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``NISTFrameworkMapperRunner`` keep working via this alias; new code
# should use ``NistFrameworkMapperAgent`` directly through AgentRuntime.
NISTFrameworkMapperRunner = NistFrameworkMapperAgent
