# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_policy_optimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_policy_optimizer.models import SecurityPolicyOptimizerState
from shieldops.agents.security_policy_optimizer.nodes import (
    analyze_effectiveness,
    apply_changes,
    collect_policies,
    generate_report,
    identify_optimizations,
    validate_changes,
)
from shieldops.agents.security_policy_optimizer.tools import SecurityPolicyOptimizerToolkit


class SecurityPolicyOptimizerAgent(Agent):
    """Declarative spec for ``security_policy_optimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_policy_optimizer"
    state_model = SecurityPolicyOptimizerState
    toolkit_factory = SecurityPolicyOptimizerToolkit

    nodes = {
        "collect_policies": collect_policies,
        "analyze_effectiveness": analyze_effectiveness,
        "identify_optimizations": identify_optimizations,
        "apply_changes": apply_changes,
        "validate_changes": validate_changes,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_policies", "analyze_effectiveness"),
        edge("identify_optimizations", "apply_changes"),
        edge("validate_changes", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "analyze_effectiveness" via _should_optimize()
        # TODO: cond(...) from "apply_changes" via _should_validate()
    ]

    entry = "collect_policies"
