# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the autonomous_ops_controller agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.autonomous_ops_controller.models import AutonomousOpsControllerState
from shieldops.agents.autonomous_ops_controller.nodes import (
    assess_fleet,
    dispatch_tasks,
    evaluate_outcomes,
    generate_report,
    monitor_execution,
    plan_operations,
)
from shieldops.agents.autonomous_ops_controller.tools import AutonomousOpsControllerToolkit
from shieldops.agents.runtime import END, Agent, edge


class AutonomousOpsControllerAgent(Agent):
    """Declarative spec for ``autonomous_ops_controller`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "autonomous_ops_controller"
    state_model = AutonomousOpsControllerState
    toolkit_factory = AutonomousOpsControllerToolkit

    nodes = {
        "assess_fleet": assess_fleet,
        "plan_operations": plan_operations,
        "dispatch_tasks": dispatch_tasks,
        "monitor_execution": monitor_execution,
        "evaluate_outcomes": evaluate_outcomes,
        "generate_report": generate_report,
    }

    edges = [
        edge("assess_fleet", "plan_operations"),
        edge("dispatch_tasks", "monitor_execution"),
        edge("evaluate_outcomes", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "plan_operations" via should_dispatch_tasks()
        # TODO: cond(...) from "monitor_execution" via should_evaluate_outcomes()
    ]

    entry = "assess_fleet"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AutonomousOpsControllerRunner`` keep working via this alias; new code
# should use ``AutonomousOpsControllerAgent`` directly through AgentRuntime.
AutonomousOpsControllerRunner = AutonomousOpsControllerAgent
