# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_data_pipeline agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_data_pipeline.models import SecurityDataPipelineState
from shieldops.agents.security_data_pipeline.nodes import (
    enrich_records,
    generate_report,
    ingest_sources,
    load_destination,
    transform_data,
    validate_quality,
)
from shieldops.agents.security_data_pipeline.tools import SecurityDataPipelineToolkit


class SecurityDataPipelineAgent(Agent):
    """Declarative spec for ``security_data_pipeline`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_data_pipeline"
    state_model = SecurityDataPipelineState
    toolkit_factory = SecurityDataPipelineToolkit

    nodes = {
        "ingest_sources": ingest_sources,
        "transform_data": transform_data,
        "enrich": enrich_records,
        "validate_quality": validate_quality,
        "load_destination": load_destination,
        "report": generate_report,
    }

    edges = [
        edge("ingest_sources", "transform_data"),
        edge("transform_data", "enrich"),
        edge("enrich", "validate_quality"),
        edge("validate_quality", "load_destination"),
        edge("load_destination", "report"),
        edge("report", END),
    ]

    entry = "ingest_sources"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityDataPipelineRunner`` keep working via this alias; new code
# should use ``SecurityDataPipelineAgent`` directly through AgentRuntime.
SecurityDataPipelineRunner = SecurityDataPipelineAgent
