# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the inference_attack_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.inference_attack_detector.models import InferenceAttackDetectorState
from shieldops.agents.inference_attack_detector.nodes import (
    analyze_patterns,
    assess_impact,
    classify_attack,
    collect_queries,
    mitigate,
    report,
)
from shieldops.agents.inference_attack_detector.tools import InferenceAttackDetectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class InferenceAttackDetectorAgent(Agent):
    """Declarative spec for ``inference_attack_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "inference_attack_detector"
    state_model = InferenceAttackDetectorState
    toolkit_factory = InferenceAttackDetectorToolkit

    nodes = {
        "collect_queries": collect_queries,
        "analyze_patterns": analyze_patterns,
        "classify_attack": classify_attack,
        "assess_impact": assess_impact,
        "mitigate": mitigate,
        "report": report,
    }

    edges = [
        edge("mitigate", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_queries" via _check_error()
        # TODO: cond(...) from "analyze_patterns" via _check_error()
        # TODO: cond(...) from "classify_attack" via _check_error()
        # TODO: cond(...) from "assess_impact" via _check_error()
    ]

    entry = "collect_queries"
