# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the web_app_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.web_app_scanner.models import WebAppScannerState
from shieldops.agents.web_app_scanner.nodes import (
    crawl_application,
    discover_endpoints,
    generate_report,
    test_access_control,
    test_authentication,
    test_injection,
)
from shieldops.agents.web_app_scanner.tools import WebAppScannerToolkit


class WebAppScannerAgent(Agent):
    """Declarative spec for ``web_app_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "web_app_scanner"
    state_model = WebAppScannerState
    toolkit_factory = WebAppScannerToolkit

    nodes = {
        "discover_endpoints": discover_endpoints,
        "crawl_application": crawl_application,
        "test_injection": test_injection,
        "test_authentication": test_authentication,
        "test_access_control": test_access_control,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_endpoints", "crawl_application"),
        edge("crawl_application", "test_injection"),
        edge("test_authentication", "test_access_control"),
        edge("test_access_control", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "test_injection"
        #   routed by _has_injection_findings() — wrap with cond(...)
    ]

    entry = "discover_endpoints"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``WebAppScannerRunner`` keep working via this alias; new code
# should use ``WebAppScannerAgent`` directly through AgentRuntime.
WebAppScannerRunner = WebAppScannerAgent
