# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the incident_similarity_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.incident_similarity_engine.models import IncidentSimilarityEngineState
from shieldops.agents.incident_similarity_engine.nodes import (
    compute_similarity,
    extract_features,
    ingest_incident,
    rank_matches,
    recommend,
    report,
)
from shieldops.agents.incident_similarity_engine.tools import IncidentSimilarityEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class IncidentSimilarityEngineAgent(Agent):
    """Declarative spec for ``incident_similarity_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "incident_similarity_engine"
    state_model = IncidentSimilarityEngineState
    toolkit_factory = IncidentSimilarityEngineToolkit

    nodes = {
        "ingest_incident": ingest_incident,
        "extract_features": extract_features,
        "compute_similarity": compute_similarity,
        "rank_matches": rank_matches,
        "recommend": recommend,
        "report": report,
    }

    edges = [
        edge("recommend", "report"),
        edge("report", END),
        # TODO: cond(...) from "ingest_incident" via _check_error()
        # TODO: cond(...) from "extract_features" via _check_error()
        # TODO: cond(...) from "compute_similarity" via _check_error()
        # TODO: cond(...) from "rank_matches" via _check_error()
    ]

    entry = "ingest_incident"
