# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the identity_threat_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.identity_threat_detector.models import IdentityThreatDetectorState
from shieldops.agents.identity_threat_detector.nodes import (
    analyze_behavior,
    assess_risk,
    collect_auth_events,
    detect_anomalies,
    generate_report,
    respond_to_threats,
)
from shieldops.agents.identity_threat_detector.tools import IdentityThreatDetectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class IdentityThreatDetectorAgent(Agent):
    """Declarative spec for ``identity_threat_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "identity_threat_detector"
    state_model = IdentityThreatDetectorState
    toolkit_factory = IdentityThreatDetectorToolkit

    nodes = {
        "collect_auth_events": collect_auth_events,
        "analyze_behavior": analyze_behavior,
        "detect_anomalies": detect_anomalies,
        "assess_risk": assess_risk,
        "respond_to_threats": respond_to_threats,
        "generate_report": generate_report,
    }

    edges = [
        edge("analyze_behavior", "detect_anomalies"),
        edge("detect_anomalies", "assess_risk"),
        edge("respond_to_threats", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "collect_auth_events"
        #   routed by _should_analyze() — wrap with cond(...)
        # TODO: conditional edge from "assess_risk"
        #   routed by _should_respond() — wrap with cond(...)
    ]

    entry = "collect_auth_events"
