# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the just_in_time_access agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.just_in_time_access.models import JustInTimeAccessState
from shieldops.agents.just_in_time_access.nodes import (
    evaluate_policy,
    monitor_session,
    provision_access,
    receive_request,
    report,
    revoke_access,
)
from shieldops.agents.just_in_time_access.tools import JustInTimeAccessToolkit
from shieldops.agents.runtime import END, Agent, edge


class JustInTimeAccessAgent(Agent):
    """Declarative spec for ``just_in_time_access`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "just_in_time_access"
    state_model = JustInTimeAccessState
    toolkit_factory = JustInTimeAccessToolkit

    nodes = {
        "receive_request": receive_request,
        "evaluate_policy": evaluate_policy,
        "provision_access": provision_access,
        "monitor_session": monitor_session,
        "revoke_access": revoke_access,
        "report": report,
    }

    edges = [
        edge("revoke_access", "report"),
        edge("report", END),
        # TODO: cond(...) from "receive_request" via _check_error()
        # TODO: cond(...) from "evaluate_policy" via _check_error()
        # TODO: cond(...) from "provision_access" via _check_error()
        # TODO: cond(...) from "monitor_session" via _check_error()
    ]

    entry = "receive_request"
