# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the behavioral_threat_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.behavioral_threat_detector.models import BehavioralThreatDetectorState
from shieldops.agents.behavioral_threat_detector.nodes import (
    build_baselines,
    collect_behaviors,
    detect_deviations,
    generate_alerts,
    generate_report,
    score_threats,
)
from shieldops.agents.behavioral_threat_detector.tools import BehavioralThreatDetectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class BehavioralThreatDetectorAgent(Agent):
    """Declarative spec for ``behavioral_threat_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "behavioral_threat_detector"
    state_model = BehavioralThreatDetectorState
    toolkit_factory = BehavioralThreatDetectorToolkit

    nodes = {
        "collect_behaviors": collect_behaviors,
        "build_baselines": build_baselines,
        "detect_deviations": detect_deviations,
        "score_threats": score_threats,
        "generate_alerts": generate_alerts,
        "generate_report": generate_report,
    }

    edges = [
        edge("detect_deviations", "score_threats"),
        edge("generate_alerts", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "collect_behaviors" via _check_error()
        # TODO: cond(...) from "build_baselines" via _check_error()
        # TODO: cond(...) from "score_threats" via should_generate_alerts()
    ]

    entry = "collect_behaviors"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``BehavioralThreatDetectorRunner`` keep working via this alias; new code
# should use ``BehavioralThreatDetectorAgent`` directly through AgentRuntime.
BehavioralThreatDetectorRunner = BehavioralThreatDetectorAgent
