# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the soc_brain agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.soc_brain.models import SOCBrainState
from shieldops.agents.soc_brain.nodes import (
    analyze_situations,
    correlate_findings,
    create_situations,
    execute_response,
    ingest_telemetry,
    normalize_events,
    recommend_actions,
    triage_events,
    update_metrics,
)
from shieldops.agents.soc_brain.tools import SOCBrainToolkit


class SocBrainAgent(Agent):
    """Declarative spec for ``soc_brain`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "soc_brain"
    state_model = SOCBrainState
    toolkit_factory = SOCBrainToolkit

    nodes = {
        "ingest_telemetry": ingest_telemetry,
        "normalize_events": normalize_events,
        "correlate_findings": correlate_findings,
        "triage_events": triage_events,
        "create_situations": create_situations,
        "analyze_situations": analyze_situations,
        "recommend_actions": recommend_actions,
        "execute_response": execute_response,
        "update_metrics": update_metrics,
    }

    edges = [
        edge("ingest_telemetry", "normalize_events"),
        edge("normalize_events", "correlate_findings"),
        edge("correlate_findings", "triage_events"),
        edge("create_situations", "analyze_situations"),
        edge("analyze_situations", "recommend_actions"),
        edge("execute_response", "update_metrics"),
        edge("update_metrics", END),
        # TODO: conditional edge from "triage_events"
        #   routed by has_situation() — wrap with cond(...)
        # TODO: conditional edge from "recommend_actions"
        #   routed by should_auto_execute() — wrap with cond(...)
    ]

    entry = "ingest_telemetry"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SOCBrainRunner`` keep working via this alias; new code
# should use ``SocBrainAgent`` directly through AgentRuntime.
SOCBrainRunner = SocBrainAgent
