# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the mobile_threat_defender agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.mobile_threat_defender.models import MobileThreatDefenderState
from shieldops.agents.mobile_threat_defender.nodes import (
    analyze_apps,
    check_network,
    detect_threats,
    enforce_policy,
    generate_report,
    scan_device,
)
from shieldops.agents.mobile_threat_defender.tools import MobileThreatDefenderToolkit
from shieldops.agents.runtime import END, Agent, edge


class MobileThreatDefenderAgent(Agent):
    """Declarative spec for ``mobile_threat_defender`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "mobile_threat_defender"
    state_model = MobileThreatDefenderState
    toolkit_factory = MobileThreatDefenderToolkit

    nodes = {
        "scan_device": scan_device,
        "analyze_apps": analyze_apps,
        "check_network": check_network,
        "detect_threats": detect_threats,
        "enforce_policy": enforce_policy,
        "generate_report": generate_report,
    }

    edges = [
        edge("analyze_apps", "check_network"),
        edge("check_network", "detect_threats"),
        edge("enforce_policy", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "scan_device"
        #   routed by _should_analyze() — wrap with cond(...)
        # TODO: conditional edge from "detect_threats"
        #   routed by _should_enforce() — wrap with cond(...)
    ]

    entry = "scan_device"
