# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the oauth_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.oauth_analyzer.models import OAuthAnalyzerState
from shieldops.agents.oauth_analyzer.nodes import (
    assess_risk,
    classify_permissions,
    detect_anomalies,
    discover_grants,
    generate_report,
    recommend_actions,
)
from shieldops.agents.oauth_analyzer.tools import OAuthAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class OauthAnalyzerAgent(Agent):
    """Declarative spec for ``oauth_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "oauth_analyzer"
    state_model = OAuthAnalyzerState
    toolkit_factory = OAuthAnalyzerToolkit

    nodes = {
        "discover_grants": discover_grants,
        "classify_permissions": classify_permissions,
        "assess_risk": assess_risk,
        "detect_anomalies": detect_anomalies,
        "recommend_actions": recommend_actions,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_grants", "classify_permissions"),
        edge("classify_permissions", "assess_risk"),
        edge("assess_risk", "detect_anomalies"),
        edge("recommend_actions", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_anomalies"
        #   routed by has_anomalies() — wrap with cond(...)
    ]

    entry = "discover_grants"
