# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_masking_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_masking_engine.models import DataMaskingEngineState
from shieldops.agents.data_masking_engine.nodes import (
    apply_masks,
    classify_sensitivity,
    discover_data,
    report,
    select_technique,
    validate,
)
from shieldops.agents.data_masking_engine.tools import DataMaskingEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataMaskingEngineAgent(Agent):
    """Declarative spec for ``data_masking_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_masking_engine"
    state_model = DataMaskingEngineState
    toolkit_factory = DataMaskingEngineToolkit

    nodes = {
        "discover_data": discover_data,
        "classify_sensitivity": classify_sensitivity,
        "select_technique": select_technique,
        "apply_masks": apply_masks,
        "validate": validate,
        "report": report,
    }

    edges = [
        edge("validate", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_data" via _check_error()
        # TODO: cond(...) from "classify_sensitivity" via _check_error()
        # TODO: cond(...) from "select_technique" via _check_error()
        # TODO: cond(...) from "apply_masks" via _check_error()
    ]

    entry = "discover_data"
