# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the network_microsegmentation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.network_microsegmentation.models import NetworkMicrosegmentationState
from shieldops.agents.network_microsegmentation.nodes import (
    analyze_flows,
    deploy_policies,
    generate_policies,
    generate_report,
    map_topology,
    validate_policies,
)
from shieldops.agents.network_microsegmentation.tools import NetworkMicrosegmentationToolkit
from shieldops.agents.runtime import END, Agent, edge


class NetworkMicrosegmentationAgent(Agent):
    """Declarative spec for ``network_microsegmentation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "network_microsegmentation"
    state_model = NetworkMicrosegmentationState
    toolkit_factory = NetworkMicrosegmentationToolkit

    nodes = {
        "map_topology": map_topology,
        "analyze_flows": analyze_flows,
        "generate_policies": generate_policies,
        "validate_policies": validate_policies,
        "deploy_policies": deploy_policies,
        "generate_report": generate_report,
    }

    edges = [
        edge("map_topology", "analyze_flows"),
        edge("analyze_flows", "generate_policies"),
        edge("generate_policies", "validate_policies"),
        edge("deploy_policies", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "validate_policies"
        #   routed by _should_deploy() — wrap with cond(...)
    ]

    entry = "map_topology"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``NetworkMicrosegmentationRunner`` keep working via this alias; new code
# should use ``NetworkMicrosegmentationAgent`` directly through AgentRuntime.
NetworkMicrosegmentationRunner = NetworkMicrosegmentationAgent
