# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_pipeline_security agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_pipeline_security.models import DataPipelineSecurityState
from shieldops.agents.data_pipeline_security.nodes import (
    assess_provenance,
    audit_data_flows,
    detect_poisoning,
    enforce_policies,
    generate_report,
    scan_rag_pipeline,
)
from shieldops.agents.data_pipeline_security.tools import DataPipelineSecurityToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataPipelineSecurityAgent(Agent):
    """Declarative spec for ``data_pipeline_security`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_pipeline_security"
    state_model = DataPipelineSecurityState
    toolkit_factory = DataPipelineSecurityToolkit

    nodes = {
        "scan_rag_pipeline": scan_rag_pipeline,
        "audit_data_flows": audit_data_flows,
        "detect_poisoning": detect_poisoning,
        "assess_provenance": assess_provenance,
        "enforce_policies": enforce_policies,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_rag_pipeline", "audit_data_flows"),
        edge("audit_data_flows", "detect_poisoning"),
        edge("detect_poisoning", "assess_provenance"),
        edge("enforce_policies", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "assess_provenance"
        #   routed by _has_findings() — wrap with cond(...)
    ]

    entry = "scan_rag_pipeline"
