# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the certificate_transparency_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.certificate_transparency_monitor.models import (
    CertificateTransparencyMonitorState,
)
from shieldops.agents.certificate_transparency_monitor.nodes import (
    check_ownership,
    detect_anomalies,
    generate_report,
    monitor_logs,
    parse_certificates,
    send_alerts,
)
from shieldops.agents.certificate_transparency_monitor.tools import (
    CertificateTransparencyMonitorToolkit,
)
from shieldops.agents.runtime import END, Agent, edge


class CertificateTransparencyMonitorAgent(Agent):
    """Declarative spec for ``certificate_transparency_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "certificate_transparency_monitor"
    state_model = CertificateTransparencyMonitorState
    toolkit_factory = CertificateTransparencyMonitorToolkit

    nodes = {
        "monitor_logs": monitor_logs,
        "parse_certificates": parse_certificates,
        "detect_anomalies": detect_anomalies,
        "check_ownership": check_ownership,
        "send_alerts": send_alerts,
        "generate_report": generate_report,
    }

    edges = [
        edge("monitor_logs", "parse_certificates"),
        edge("parse_certificates", "detect_anomalies"),
        edge("detect_anomalies", "check_ownership"),
        edge("send_alerts", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "check_ownership"
        #   routed by _should_alert() — wrap with cond(...)
    ]

    entry = "monitor_logs"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CertificateTransparencyMonitorRunner`` keep working via this alias; new code
# should use ``CertificateTransparencyMonitorAgent`` directly through AgentRuntime.
CertificateTransparencyMonitorRunner = CertificateTransparencyMonitorAgent
