# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the continuous_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.continuous_scanner.models import ContinuousScannerState
from shieldops.agents.continuous_scanner.nodes import (
    check_due_scans,
    collect_results,
    dispatch_scans,
    generate_report,
    load_schedule,
    monitor_progress,
)
from shieldops.agents.continuous_scanner.tools import ContinuousScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class ContinuousScannerAgent(Agent):
    """Declarative spec for ``continuous_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "continuous_scanner"
    state_model = ContinuousScannerState
    toolkit_factory = ContinuousScannerToolkit

    nodes = {
        "load_schedule": load_schedule,
        "check_due_scans": check_due_scans,
        "dispatch_scans": dispatch_scans,
        "monitor_progress": monitor_progress,
        "collect_results": collect_results,
        "generate_report": generate_report,
    }

    edges = [
        edge("load_schedule", "check_due_scans"),
        edge("dispatch_scans", "monitor_progress"),
        edge("monitor_progress", "collect_results"),
        edge("collect_results", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "check_due_scans"
        #   routed by _has_due_scans() — wrap with cond(...)
    ]

    entry = "load_schedule"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ContinuousScannerRunner`` keep working via this alias; new code
# should use ``ContinuousScannerAgent`` directly through AgentRuntime.
ContinuousScannerRunner = ContinuousScannerAgent
