# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the communication_auditor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.communication_auditor.models import CommunicationAuditorState
from shieldops.agents.communication_auditor.nodes import (
    check_compliance,
    classify,
    collect_messages,
    flag_violations,
    generate_report,
    report,
)
from shieldops.agents.communication_auditor.tools import CommunicationAuditorToolkit
from shieldops.agents.runtime import END, Agent, edge


class CommunicationAuditorAgent(Agent):
    """Declarative spec for ``communication_auditor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "communication_auditor"
    state_model = CommunicationAuditorState
    toolkit_factory = CommunicationAuditorToolkit

    nodes = {
        "collect_messages": collect_messages,
        "classify": classify,
        "check_compliance": check_compliance,
        "flag_violations": flag_violations,
        "generate_report": generate_report,
        "report": report,
    }

    edges = [
        edge("generate_report", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_messages" via _check_error()
        # TODO: cond(...) from "classify" via _check_error()
        # TODO: cond(...) from "check_compliance" via _check_error()
        # TODO: cond(...) from "flag_violations" via _check_error()
    ]

    entry = "collect_messages"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CommunicationAuditorRunner`` keep working via this alias; new code
# should use ``CommunicationAuditorAgent`` directly through AgentRuntime.
CommunicationAuditorRunner = CommunicationAuditorAgent
