# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_sovereignty_enforcer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_sovereignty_enforcer.models import DataSovereigntyEnforcerState
from shieldops.agents.data_sovereignty_enforcer.nodes import (
    check_residency,
    discover_data_flows,
    enforce_policies,
    map_jurisdictions,
    report,
    validate_transfers,
)
from shieldops.agents.data_sovereignty_enforcer.tools import DataSovereigntyEnforcerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataSovereigntyEnforcerAgent(Agent):
    """Declarative spec for ``data_sovereignty_enforcer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_sovereignty_enforcer"
    state_model = DataSovereigntyEnforcerState
    toolkit_factory = DataSovereigntyEnforcerToolkit

    nodes = {
        "discover_data_flows": discover_data_flows,
        "map_jurisdictions": map_jurisdictions,
        "check_residency": check_residency,
        "validate_transfers": validate_transfers,
        "enforce_policies": enforce_policies,
        "report": report,
    }

    edges = [
        edge("discover_data_flows", "map_jurisdictions"),
        edge("map_jurisdictions", "check_residency"),
        edge("check_residency", "validate_transfers"),
        edge("enforce_policies", "report"),
        edge("report", END),
        # TODO: conditional edge from "validate_transfers"
        #   routed by _has_violations() — wrap with cond(...)
    ]

    entry = "discover_data_flows"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DataSovereigntyEnforcerRunner`` keep working via this alias; new code
# should use ``DataSovereigntyEnforcerAgent`` directly through AgentRuntime.
DataSovereigntyEnforcerRunner = DataSovereigntyEnforcerAgent
