# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_control_mapper agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_control_mapper.models import SecurityControlMapperState
from shieldops.agents.security_control_mapper.nodes import (
    collect_controls,
    cross_reference,
    identify_gaps,
    map_frameworks,
    report,
    score,
)
from shieldops.agents.security_control_mapper.tools import SecurityControlMapperToolkit


class SecurityControlMapperAgent(Agent):
    """Declarative spec for ``security_control_mapper`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_control_mapper"
    state_model = SecurityControlMapperState
    toolkit_factory = SecurityControlMapperToolkit

    nodes = {
        "collect_controls": collect_controls,
        "map_frameworks": map_frameworks,
        "identify_gaps": identify_gaps,
        "cross_reference": cross_reference,
        "score": score,
        "report": report,
    }

    edges = [
        edge("score", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_controls" via _check_error()
        # TODO: cond(...) from "map_frameworks" via _check_error()
        # TODO: cond(...) from "identify_gaps" via _check_error()
        # TODO: cond(...) from "cross_reference" via _check_error()
    ]

    entry = "collect_controls"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityControlMapperRunner`` keep working via this alias; new code
# should use ``SecurityControlMapperAgent`` directly through AgentRuntime.
SecurityControlMapperRunner = SecurityControlMapperAgent
