# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the privileged_session_recorder agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.privileged_session_recorder.models import PrivilegedSessionRecorderState
from shieldops.agents.privileged_session_recorder.nodes import (
    archive,
    detect_anomalies,
    detect_session,
    monitor_commands,
    report,
    start_recording,
)
from shieldops.agents.privileged_session_recorder.tools import PrivilegedSessionRecorderToolkit
from shieldops.agents.runtime import END, Agent, edge


class PrivilegedSessionRecorderAgent(Agent):
    """Declarative spec for ``privileged_session_recorder`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "privileged_session_recorder"
    state_model = PrivilegedSessionRecorderState
    toolkit_factory = PrivilegedSessionRecorderToolkit

    nodes = {
        "detect_session": detect_session,
        "start_recording": start_recording,
        "monitor_commands": monitor_commands,
        "detect_anomalies": detect_anomalies,
        "archive": archive,
        "report": report,
    }

    edges = [
        edge("archive", "report"),
        edge("report", END),
        # TODO: cond(...) from "detect_session" via _check_error()
        # TODO: cond(...) from "start_recording" via _check_error()
        # TODO: cond(...) from "monitor_commands" via _check_error()
        # TODO: cond(...) from "detect_anomalies" via _check_error()
    ]

    entry = "detect_session"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``PrivilegedSessionRecorderRunner`` keep working via this alias; new code
# should use ``PrivilegedSessionRecorderAgent`` directly through AgentRuntime.
PrivilegedSessionRecorderRunner = PrivilegedSessionRecorderAgent
