# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_pipeline_protector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_pipeline_protector.models import DataPipelineProtectorState
from shieldops.agents.data_pipeline_protector.nodes import (
    detect_anomalies,
    discover_pipelines,
    enforce_access,
    generate_report,
    scan_inputs,
    validate_schemas,
)
from shieldops.agents.data_pipeline_protector.tools import DataPipelineProtectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataPipelineProtectorAgent(Agent):
    """Declarative spec for ``data_pipeline_protector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_pipeline_protector"
    state_model = DataPipelineProtectorState
    toolkit_factory = DataPipelineProtectorToolkit

    nodes = {
        "discover_pipelines": discover_pipelines,
        "scan_inputs": scan_inputs,
        "detect_anomalies": detect_anomalies,
        "validate_schemas": validate_schemas,
        "enforce_access": enforce_access,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_pipelines", "scan_inputs"),
        edge("scan_inputs", "detect_anomalies"),
        edge("detect_anomalies", "validate_schemas"),
        edge("enforce_access", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "validate_schemas"
        #   routed by _has_critical_findings() — wrap with cond(...)
    ]

    entry = "discover_pipelines"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DataPipelineProtectorRunner`` keep working via this alias; new code
# should use ``DataPipelineProtectorAgent`` directly through AgentRuntime.
DataPipelineProtectorRunner = DataPipelineProtectorAgent
