# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the multi_tenant_isolation_guard agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.multi_tenant_isolation_guard.models import MultiTenantIsolationGuardState
from shieldops.agents.multi_tenant_isolation_guard.nodes import (
    assess_isolation,
    detect_leakage,
    enforce_controls,
    generate_report,
    map_tenants,
    scan_boundaries,
)
from shieldops.agents.multi_tenant_isolation_guard.tools import MultiTenantIsolationGuardToolkit
from shieldops.agents.runtime import END, Agent, edge


class MultiTenantIsolationGuardAgent(Agent):
    """Declarative spec for ``multi_tenant_isolation_guard`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "multi_tenant_isolation_guard"
    state_model = MultiTenantIsolationGuardState
    toolkit_factory = MultiTenantIsolationGuardToolkit

    nodes = {
        "map_tenants": map_tenants,
        "scan_boundaries": scan_boundaries,
        "detect_leakage": detect_leakage,
        "assess_isolation": assess_isolation,
        "enforce_controls": enforce_controls,
        "generate_report": generate_report,
    }

    edges = [
        edge("map_tenants", "scan_boundaries"),
        edge("detect_leakage", "assess_isolation"),
        edge("enforce_controls", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "scan_boundaries" via _should_detect()
        # TODO: cond(...) from "assess_isolation" via _should_enforce()
    ]

    entry = "map_tenants"
