# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the compliance_evidence_collector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.compliance_evidence_collector.models import ComplianceEvidenceCollectorState
from shieldops.agents.compliance_evidence_collector.nodes import (
    collect_evidence,
    generate_compliance_report,
    generate_report,
    identify_controls,
    map_frameworks,
    validate_evidence,
)
from shieldops.agents.compliance_evidence_collector.tools import ComplianceEvidenceCollectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class ComplianceEvidenceCollectorAgent(Agent):
    """Declarative spec for ``compliance_evidence_collector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "compliance_evidence_collector"
    state_model = ComplianceEvidenceCollectorState
    toolkit_factory = ComplianceEvidenceCollectorToolkit

    nodes = {
        "identify_controls": identify_controls,
        "collect_evidence": collect_evidence,
        "validate_evidence": validate_evidence,
        "map_frameworks": map_frameworks,
        "generate_compliance_report": generate_compliance_report,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_evidence", "validate_evidence"),
        edge("validate_evidence", "map_frameworks"),
        edge("generate_compliance_report", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "identify_controls"
        #   routed by _should_collect() — wrap with cond(...)
        # TODO: conditional edge from "map_frameworks"
        #   routed by _should_generate_report() — wrap with cond(...)
    ]

    entry = "identify_controls"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ComplianceEvidenceCollectorRunner`` keep working via this alias; new code
# should use ``ComplianceEvidenceCollectorAgent`` directly through AgentRuntime.
ComplianceEvidenceCollectorRunner = ComplianceEvidenceCollectorAgent
