# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_intelligence_fusion agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_intelligence_fusion.models import ThreatIntelligenceFusionState
from shieldops.agents.threat_intelligence_fusion.nodes import (
    collect_feeds,
    correlate_indicators,
    enrich_context,
    generate_report,
    normalize_iocs,
    score_threats,
)
from shieldops.agents.threat_intelligence_fusion.tools import ThreatIntelligenceFusionToolkit


class ThreatIntelligenceFusionAgent(Agent):
    """Declarative spec for ``threat_intelligence_fusion`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_intelligence_fusion"
    state_model = ThreatIntelligenceFusionState
    toolkit_factory = ThreatIntelligenceFusionToolkit

    nodes = {
        "collect_feeds": collect_feeds,
        "normalize_iocs": normalize_iocs,
        "correlate_indicators": correlate_indicators,
        "enrich_context": enrich_context,
        "score_threats": score_threats,
        "generate_report": generate_report,
    }

    edges = [
        edge("normalize_iocs", "correlate_indicators"),
        edge("enrich_context", "score_threats"),
        edge("score_threats", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "collect_feeds"
        #   routed by _should_normalize() — wrap with cond(...)
        # TODO: conditional edge from "correlate_indicators"
        #   routed by _should_enrich() — wrap with cond(...)
    ]

    entry = "collect_feeds"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ThreatIntelligenceFusionRunner`` keep working via this alias; new code
# should use ``ThreatIntelligenceFusionAgent`` directly through AgentRuntime.
ThreatIntelligenceFusionRunner = ThreatIntelligenceFusionAgent
