# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the otel_semantic agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.otel_semantic.models import OTelSemanticState
from shieldops.agents.otel_semantic.nodes import (
    analyze_violations,
    generate_fixes,
    load_rules,
    scan_services,
)
from shieldops.agents.otel_semantic.tools import OTelSemanticToolkit
from shieldops.agents.runtime import END, Agent, edge


class OtelSemanticAgent(Agent):
    """Declarative spec for ``otel_semantic`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "otel_semantic"
    state_model = OTelSemanticState
    toolkit_factory = OTelSemanticToolkit

    nodes = {
        "load_rules": load_rules,
        "scan": scan_services,
        "analyze": analyze_violations,
        "generate_fixes": generate_fixes,
    }

    edges = [
        edge("load_rules", "scan"),
        edge("scan", "analyze"),
        edge("analyze", "generate_fixes"),
        edge("generate_fixes", END),
    ]

    entry = "load_rules"
