# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the war_room_automator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.war_room_automator.models import WarRoomAutomatorState
from shieldops.agents.war_room_automator.nodes import (
    assemble_team,
    coordinate_actions,
    create_room,
    detect_incident,
    report,
    share_context,
)
from shieldops.agents.war_room_automator.tools import WarRoomAutomatorToolkit


class WarRoomAutomatorAgent(Agent):
    """Declarative spec for ``war_room_automator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "war_room_automator"
    state_model = WarRoomAutomatorState
    toolkit_factory = WarRoomAutomatorToolkit

    nodes = {
        "detect_incident": detect_incident,
        "create_room": create_room,
        "assemble_team": assemble_team,
        "share_context": share_context,
        "coordinate_actions": coordinate_actions,
        "report": report,
    }

    edges = [
        edge("detect_incident", "create_room"),
        edge("create_room", "assemble_team"),
        edge("assemble_team", "share_context"),
        edge("share_context", "coordinate_actions"),
        edge("coordinate_actions", "report"),
        edge("report", END),
    ]

    entry = "detect_incident"
