# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_surface_minimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_surface_minimizer.models import ThreatSurfaceMinimizerState
from shieldops.agents.threat_surface_minimizer.nodes import (
    discover_surface,
    map_exposure,
    prioritize_risks,
    recommend_reduction,
    report,
    validate,
)
from shieldops.agents.threat_surface_minimizer.tools import ThreatSurfaceMinimizerToolkit


class ThreatSurfaceMinimizerAgent(Agent):
    """Declarative spec for ``threat_surface_minimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_surface_minimizer"
    state_model = ThreatSurfaceMinimizerState
    toolkit_factory = ThreatSurfaceMinimizerToolkit

    nodes = {
        "discover_surface": discover_surface,
        "map_exposure": map_exposure,
        "prioritize_risks": prioritize_risks,
        "recommend_reduction": recommend_reduction,
        "validate": validate,
        "report": report,
    }

    edges = [
        edge("validate", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_surface" via _check_error()
        # TODO: cond(...) from "map_exposure" via _check_error()
        # TODO: cond(...) from "prioritize_risks" via _check_error()
        # TODO: cond(...) from "recommend_reduction" via _check_error()
    ]

    entry = "discover_surface"
