# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the firewall_rule_auditor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.firewall_rule_auditor.models import FirewallAuditState
from shieldops.agents.firewall_rule_auditor.nodes import (
    check_compliance,
    classify_risks,
    collect_rules,
    detect_violations,
    generate_report,
    recommend_fixes,
)
from shieldops.agents.firewall_rule_auditor.tools import FirewallAuditToolkit
from shieldops.agents.runtime import END, Agent, edge


class FirewallRuleAuditorAgent(Agent):
    """Declarative spec for ``firewall_rule_auditor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "firewall_rule_auditor"
    state_model = FirewallAuditState
    toolkit_factory = FirewallAuditToolkit

    nodes = {
        "collect_rules": collect_rules,
        "detect_violations": detect_violations,
        "classify_risks": classify_risks,
        "check_compliance": check_compliance,
        "recommend_fixes": recommend_fixes,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_rules", "detect_violations"),
        edge("detect_violations", "classify_risks"),
        edge("classify_risks", "check_compliance"),
        edge("check_compliance", "recommend_fixes"),
        edge("recommend_fixes", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "collect_rules"
