# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the supply_chain_risk_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.supply_chain_risk_monitor.models import SupplyChainRiskMonitorState
from shieldops.agents.supply_chain_risk_monitor.nodes import (
    analyze_dependencies,
    assess_impact,
    detect_risks,
    generate_report,
    mitigate,
    scan_supply_chain,
)
from shieldops.agents.supply_chain_risk_monitor.tools import SupplyChainRiskMonitorToolkit


class SupplyChainRiskMonitorAgent(Agent):
    """Declarative spec for ``supply_chain_risk_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "supply_chain_risk_monitor"
    state_model = SupplyChainRiskMonitorState
    toolkit_factory = SupplyChainRiskMonitorToolkit

    nodes = {
        "scan_supply_chain": scan_supply_chain,
        "analyze_dependencies": analyze_dependencies,
        "detect_risks": detect_risks,
        "assess_impact": assess_impact,
        "mitigate": mitigate,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_supply_chain", "analyze_dependencies"),
        edge("analyze_dependencies", "detect_risks"),
        edge("detect_risks", "assess_impact"),
        edge("mitigate", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "assess_impact"
        #   routed by _should_mitigate() — wrap with cond(...)
    ]

    entry = "scan_supply_chain"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SupplyChainRiskMonitorRunner`` keep working via this alias; new code
# should use ``SupplyChainRiskMonitorAgent`` directly through AgentRuntime.
SupplyChainRiskMonitorRunner = SupplyChainRiskMonitorAgent
