# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the multi_agent_security agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.multi_agent_security.models import MultiAgentSecurityState
from shieldops.agents.multi_agent_security.nodes import (
    detect_anomalies,
    discover_interactions,
    enforce_policies,
    generate_report,
    map_trust_chains,
    verify_communications,
)
from shieldops.agents.multi_agent_security.tools import MultiAgentSecurityToolkit
from shieldops.agents.runtime import END, Agent, edge


class MultiAgentSecurityAgent(Agent):
    """Declarative spec for ``multi_agent_security`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "multi_agent_security"
    state_model = MultiAgentSecurityState
    toolkit_factory = MultiAgentSecurityToolkit

    nodes = {
        "discover_interactions": discover_interactions,
        "map_trust_chains": map_trust_chains,
        "verify_communications": verify_communications,
        "detect_anomalies": detect_anomalies,
        "enforce_policies": enforce_policies,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_interactions", "map_trust_chains"),
        edge("map_trust_chains", "verify_communications"),
        edge("verify_communications", "detect_anomalies"),
        edge("enforce_policies", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_anomalies"
        #   routed by _should_enforce() — wrap with cond(...)
    ]

    entry = "discover_interactions"
