# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the dast_runner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.dast_runner.models import DASTRunnerState
from shieldops.agents.dast_runner.nodes import (
    analyze_responses,
    crawl_application,
    discover_endpoints,
    fuzz_parameters,
    generate_report,
    test_authentication,
)
from shieldops.agents.dast_runner.tools import DASTRunnerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DastRunnerAgent(Agent):
    """Declarative spec for ``dast_runner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "dast_runner"
    state_model = DASTRunnerState
    toolkit_factory = DASTRunnerToolkit

    nodes = {
        "discover_endpoints": discover_endpoints,
        "crawl_application": crawl_application,
        "test_authentication": test_authentication,
        "fuzz_parameters": fuzz_parameters,
        "analyze_responses": analyze_responses,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_endpoints", "crawl_application"),
        edge("crawl_application", "test_authentication"),
        edge("test_authentication", "fuzz_parameters"),
        edge("fuzz_parameters", "analyze_responses"),
        edge("analyze_responses", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "discover_endpoints"
