# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the regulatory_change_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.regulatory_change_monitor.models import RegulatoryChangeMonitorState
from shieldops.agents.regulatory_change_monitor.nodes import (
    assess_impact,
    generate_actions,
    generate_report,
    map_controls,
    monitor_sources,
    parse_changes,
)
from shieldops.agents.regulatory_change_monitor.tools import RegulatoryChangeMonitorToolkit
from shieldops.agents.runtime import END, Agent, edge


class RegulatoryChangeMonitorAgent(Agent):
    """Declarative spec for ``regulatory_change_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "regulatory_change_monitor"
    state_model = RegulatoryChangeMonitorState
    toolkit_factory = RegulatoryChangeMonitorToolkit

    nodes = {
        "monitor_sources": monitor_sources,
        "parse_changes": parse_changes,
        "assess_impact": assess_impact,
        "map_controls": map_controls,
        "generate_actions": generate_actions,
        "generate_report": generate_report,
    }

    edges = [
        edge("monitor_sources", "parse_changes"),
        edge("parse_changes", "assess_impact"),
        edge("map_controls", "generate_actions"),
        edge("generate_actions", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "assess_impact"
        #   routed by _should_map_controls() — wrap with cond(...)
    ]

    entry = "monitor_sources"
