# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_app_builder agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_app_builder.models import SecurityAppBuilderState
from shieldops.agents.security_app_builder.nodes import (
    deploy_app,
    design_workflow,
    generate_code,
    parse_requirements,
    report,
    validate_security,
)
from shieldops.agents.security_app_builder.tools import SecurityAppBuilderToolkit


class SecurityAppBuilderAgent(Agent):
    """Declarative spec for ``security_app_builder`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_app_builder"
    state_model = SecurityAppBuilderState
    toolkit_factory = SecurityAppBuilderToolkit

    nodes = {
        "parse_requirements": parse_requirements,
        "design_workflow": design_workflow,
        "generate_code": generate_code,
        "validate_security": validate_security,
        "deploy_app": deploy_app,
        "report": report,
    }

    edges = [
        edge("parse_requirements", "design_workflow"),
        edge("design_workflow", "generate_code"),
        edge("generate_code", "validate_security"),
        edge("deploy_app", "report"),
        edge("report", END),
        # TODO: conditional edge from "validate_security"
        #   routed by _should_deploy() — wrap with cond(...)
    ]

    entry = "parse_requirements"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityAppBuilderRunner`` keep working via this alias; new code
# should use ``SecurityAppBuilderAgent`` directly through AgentRuntime.
SecurityAppBuilderRunner = SecurityAppBuilderAgent
