# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_ops_dashboard agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_ops_dashboard.models import SecurityOpsDashboardState
from shieldops.agents.security_ops_dashboard.nodes import (
    build_views,
    calculate_kpis,
    collect_metrics,
    detect_anomalies,
    generate_insights,
    generate_report,
)
from shieldops.agents.security_ops_dashboard.tools import SecurityOpsDashboardToolkit


class SecurityOpsDashboardAgent(Agent):
    """Declarative spec for ``security_ops_dashboard`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_ops_dashboard"
    state_model = SecurityOpsDashboardState
    toolkit_factory = SecurityOpsDashboardToolkit

    nodes = {
        "collect_metrics": collect_metrics,
        "calculate_kpis": calculate_kpis,
        "detect_anomalies": detect_anomalies,
        "generate_insights": generate_insights,
        "build_views": build_views,
        "report": generate_report,
    }

    edges = [
        edge("collect_metrics", "calculate_kpis"),
        edge("calculate_kpis", "detect_anomalies"),
        edge("detect_anomalies", "generate_insights"),
        edge("generate_insights", "build_views"),
        edge("build_views", "report"),
        edge("report", END),
    ]

    entry = "collect_metrics"
