# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ot_protocol_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ot_protocol_monitor.models import OTProtocolMonitorState
from shieldops.agents.ot_protocol_monitor.nodes import (
    classify_threats,
    detect_anomalies,
    discover_devices,
    generate_alerts,
    generate_report,
    monitor_protocols,
)
from shieldops.agents.ot_protocol_monitor.tools import OTProtocolMonitorToolkit
from shieldops.agents.runtime import END, Agent, edge


class OtProtocolMonitorAgent(Agent):
    """Declarative spec for ``ot_protocol_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ot_protocol_monitor"
    state_model = OTProtocolMonitorState
    toolkit_factory = OTProtocolMonitorToolkit

    nodes = {
        "discover_devices": discover_devices,
        "monitor_protocols": monitor_protocols,
        "detect_anomalies": detect_anomalies,
        "classify_threats": classify_threats,
        "alert": generate_alerts,
        "report": generate_report,
    }

    edges = [
        edge("discover_devices", "monitor_protocols"),
        edge("monitor_protocols", "detect_anomalies"),
        edge("detect_anomalies", "classify_threats"),
        edge("classify_threats", "alert"),
        edge("alert", "report"),
        edge("report", END),
    ]

    entry = "discover_devices"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``OTProtocolMonitorRunner`` keep working via this alias; new code
# should use ``OtProtocolMonitorAgent`` directly through AgentRuntime.
OTProtocolMonitorRunner = OtProtocolMonitorAgent
