# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ir_playbook_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ir_playbook_engine.models import IRPlaybookEngineState
from shieldops.agents.ir_playbook_engine.nodes import (
    adapt_response,
    classify_incident,
    execute_steps,
    report,
    select_playbook,
    validate_containment,
)
from shieldops.agents.ir_playbook_engine.tools import IRPlaybookEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class IrPlaybookEngineAgent(Agent):
    """Declarative spec for ``ir_playbook_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ir_playbook_engine"
    state_model = IRPlaybookEngineState
    toolkit_factory = IRPlaybookEngineToolkit

    nodes = {
        "classify_incident": classify_incident,
        "select_playbook": select_playbook,
        "execute_steps": execute_steps,
        "adapt_response": adapt_response,
        "validate_containment": validate_containment,
        "report": report,
    }

    edges = [
        edge("validate_containment", "report"),
        edge("report", END),
        # TODO: cond(...) from "classify_incident" via _route_after_classify()
        # TODO: cond(...) from "select_playbook" via _route_after_select()
        # TODO: cond(...) from "execute_steps" via _route_after_execute()
        # TODO: cond(...) from "adapt_response" via _route_after_adapt()
    ]

    entry = "classify_incident"
