# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_retention_enforcer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_retention_enforcer.models import DataRetentionEnforcerState
from shieldops.agents.data_retention_enforcer.nodes import (
    check_expiry,
    classify_retention,
    discover_data,
    enforce_deletion,
    report,
    verify_compliance,
)
from shieldops.agents.data_retention_enforcer.tools import DataRetentionEnforcerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataRetentionEnforcerAgent(Agent):
    """Declarative spec for ``data_retention_enforcer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_retention_enforcer"
    state_model = DataRetentionEnforcerState
    toolkit_factory = DataRetentionEnforcerToolkit

    nodes = {
        "discover_data": discover_data,
        "classify_retention": classify_retention,
        "check_expiry": check_expiry,
        "enforce_deletion": enforce_deletion,
        "verify_compliance": verify_compliance,
        "report": report,
    }

    edges = [
        edge("discover_data", "classify_retention"),
        edge("classify_retention", "check_expiry"),
        edge("check_expiry", "enforce_deletion"),
        edge("enforce_deletion", "verify_compliance"),
        edge("verify_compliance", "report"),
        edge("report", END),
    ]

    entry = "discover_data"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DataRetentionEnforcerRunner`` keep working via this alias; new code
# should use ``DataRetentionEnforcerAgent`` directly through AgentRuntime.
DataRetentionEnforcerRunner = DataRetentionEnforcerAgent
