# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the intelligence_fusion_center agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.intelligence_fusion_center.models import IntelligenceFusionCenterState
from shieldops.agents.intelligence_fusion_center.nodes import (
    assess_threats,
    collect_feeds,
    correlate_threats,
    fuse_intelligence,
    generate_assessment,
    generate_report,
)
from shieldops.agents.intelligence_fusion_center.tools import IntelligenceFusionCenterToolkit
from shieldops.agents.runtime import END, Agent, edge


class IntelligenceFusionCenterAgent(Agent):
    """Declarative spec for ``intelligence_fusion_center`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "intelligence_fusion_center"
    state_model = IntelligenceFusionCenterState
    toolkit_factory = IntelligenceFusionCenterToolkit

    nodes = {
        "collect_feeds": collect_feeds,
        "correlate_threats": correlate_threats,
        "fuse_intelligence": fuse_intelligence,
        "assess_threats": assess_threats,
        "generate_assessment": generate_assessment,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_feeds", "correlate_threats"),
        edge("correlate_threats", "fuse_intelligence"),
        edge("fuse_intelligence", "assess_threats"),
        edge("generate_assessment", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "assess_threats" via should_generate_assessment()
    ]

    entry = "collect_feeds"
