# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the artifact_integrity_checker agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.artifact_integrity_checker.models import ArtifactIntegrityCheckerState
from shieldops.agents.artifact_integrity_checker.nodes import (
    assess,
    check_checksums,
    collect_artifacts,
    report,
    validate_provenance,
    verify_signatures,
)
from shieldops.agents.artifact_integrity_checker.tools import ArtifactIntegrityCheckerToolkit
from shieldops.agents.runtime import END, Agent, edge


class ArtifactIntegrityCheckerAgent(Agent):
    """Declarative spec for ``artifact_integrity_checker`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "artifact_integrity_checker"
    state_model = ArtifactIntegrityCheckerState
    toolkit_factory = ArtifactIntegrityCheckerToolkit

    nodes = {
        "collect_artifacts": collect_artifacts,
        "verify_signatures": verify_signatures,
        "check_checksums": check_checksums,
        "validate_provenance": validate_provenance,
        "assess": assess,
        "report": report,
    }

    edges = [
        edge("assess", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_artifacts" via _check_error()
        # TODO: cond(...) from "verify_signatures" via _check_error()
        # TODO: cond(...) from "check_checksums" via _check_error()
        # TODO: cond(...) from "validate_provenance" via _check_error()
    ]

    entry = "collect_artifacts"
