# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the soc_analyst agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.soc_analyst.models import SOCAnalystState
from shieldops.agents.soc_analyst.nodes import (
    correlate_events,
    enrich_alert,
    execute_playbook,
    finalize,
    generate_narrative,
    map_attack_chain,
    recommend_containment,
    triage_alert,
)
from shieldops.agents.soc_analyst.tools import SOCAnalystToolkit


class SocAnalystAgent(Agent):
    """Declarative spec for ``soc_analyst`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "soc_analyst"
    state_model = SOCAnalystState
    toolkit_factory = SOCAnalystToolkit

    nodes = {
        "triage_alert": triage_alert,
        "enrich_alert": enrich_alert,
        "correlate_events": correlate_events,
        "map_attack_chain": map_attack_chain,
        "generate_narrative": generate_narrative,
        "recommend_containment": recommend_containment,
        "execute_playbook": execute_playbook,
        "finalize": finalize,
    }

    edges = [
        edge("enrich_alert", "correlate_events"),
        edge("map_attack_chain", "generate_narrative"),
        edge("generate_narrative", "recommend_containment"),
        edge("execute_playbook", "finalize"),
        edge("finalize", END),
        # TODO: conditional edge from "triage_alert"
        #   routed by should_suppress() — wrap with cond(...)
        # TODO: conditional edge from "correlate_events"
        #   routed by should_map_attack_chain() — wrap with cond(...)
        # TODO: conditional edge from "recommend_containment"
        #   routed by should_auto_execute() — wrap with cond(...)
    ]

    entry = "triage_alert"
