# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the event_stream_processor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.event_stream_processor.models import EventStreamProcessorState
from shieldops.agents.event_stream_processor.nodes import (
    connect_streams,
    correlate,
    enrich,
    generate_report,
    parse_events,
    route,
)
from shieldops.agents.event_stream_processor.tools import EventStreamProcessorToolkit
from shieldops.agents.runtime import END, Agent, edge


class EventStreamProcessorAgent(Agent):
    """Declarative spec for ``event_stream_processor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "event_stream_processor"
    state_model = EventStreamProcessorState
    toolkit_factory = EventStreamProcessorToolkit

    nodes = {
        "connect_streams": connect_streams,
        "parse_events": parse_events,
        "enrich": enrich,
        "correlate": correlate,
        "route": route,
        "report": generate_report,
    }

    edges = [
        edge("parse_events", "enrich"),
        edge("enrich", "correlate"),
        edge("route", "report"),
        edge("report", END),
        # TODO: conditional edge from "connect_streams"
        #   routed by _should_parse() — wrap with cond(...)
        # TODO: conditional edge from "correlate"
        #   routed by _should_route() — wrap with cond(...)
    ]

    entry = "connect_streams"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``EventStreamProcessorRunner`` keep working via this alias; new code
# should use ``EventStreamProcessorAgent`` directly through AgentRuntime.
EventStreamProcessorRunner = EventStreamProcessorAgent
