# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the secret_sprawl_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.secret_sprawl_detector.models import SecretSprawlDetectorState
from shieldops.agents.secret_sprawl_detector.nodes import (
    alert_owners,
    classify_risk,
    detect_secrets,
    generate_report,
    scan_config,
    scan_repos,
)
from shieldops.agents.secret_sprawl_detector.tools import SecretSprawlDetectorToolkit


class SecretSprawlDetectorAgent(Agent):
    """Declarative spec for ``secret_sprawl_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "secret_sprawl_detector"
    state_model = SecretSprawlDetectorState
    toolkit_factory = SecretSprawlDetectorToolkit

    nodes = {
        "scan_repos": scan_repos,
        "scan_config": scan_config,
        "detect_secrets": detect_secrets,
        "classify_risk": classify_risk,
        "alert_owners": alert_owners,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_repos", "scan_config"),
        edge("scan_config", "detect_secrets"),
        edge("detect_secrets", "classify_risk"),
        edge("alert_owners", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "classify_risk"
        #   routed by _should_alert() — wrap with cond(...)
    ]

    entry = "scan_repos"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecretSprawlDetectorRunner`` keep working via this alias; new code
# should use ``SecretSprawlDetectorAgent`` directly through AgentRuntime.
SecretSprawlDetectorRunner = SecretSprawlDetectorAgent
