# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_automation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_automation.models import ThreatAutomationState
from shieldops.agents.threat_automation.nodes import (
    analyze_behavior,
    automate_response,
    correlate_intelligence,
    detect_threats,
    finalize_hunt,
)
from shieldops.agents.threat_automation.tools import ThreatAutomationToolkit


class ThreatAutomationAgent(Agent):
    """Declarative spec for ``threat_automation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_automation"
    state_model = ThreatAutomationState
    toolkit_factory = ThreatAutomationToolkit

    nodes = {
        "detect_threats": detect_threats,
        "analyze_behavior": analyze_behavior,
        "correlate_intelligence": correlate_intelligence,
        "automate_response": automate_response,
        "finalize_hunt": finalize_hunt,
    }

    edges = [
        edge("analyze_behavior", "correlate_intelligence"),
        edge("automate_response", "finalize_hunt"),
        edge("finalize_hunt", END),
        # TODO: conditional edge from "detect_threats"
        #   routed by should_analyze() — wrap with cond(...)
        # TODO: conditional edge from "correlate_intelligence"
        #   routed by should_respond() — wrap with cond(...)
    ]

    entry = "detect_threats"
