# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_orchestration_hub agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_orchestration_hub.models import SecurityOrchestrationHubState
from shieldops.agents.security_orchestration_hub.nodes import (
    classify_severity,
    execute_actions,
    generate_report,
    ingest_event,
    route_playbook,
    validate_outcome,
)
from shieldops.agents.security_orchestration_hub.tools import SecurityOrchestrationHubToolkit


class SecurityOrchestrationHubAgent(Agent):
    """Declarative spec for ``security_orchestration_hub`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_orchestration_hub"
    state_model = SecurityOrchestrationHubState
    toolkit_factory = SecurityOrchestrationHubToolkit

    nodes = {
        "ingest_event": ingest_event,
        "classify_severity": classify_severity,
        "route_playbook": route_playbook,
        "execute_actions": execute_actions,
        "validate_outcome": validate_outcome,
        "generate_report": generate_report,
    }

    edges = [
        edge("ingest_event", "classify_severity"),
        edge("classify_severity", "route_playbook"),
        edge("route_playbook", "execute_actions"),
        edge("validate_outcome", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "execute_actions"
        #   routed by _should_validate() — wrap with cond(...)
    ]

    entry = "ingest_event"
