# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_snapshot_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_snapshot_analyzer.models import CloudSnapshotAnalyzerState
from shieldops.agents.cloud_snapshot_analyzer.nodes import (
    analyze_config,
    assess_risk,
    check_encryption,
    detect_exposure,
    discover_snapshots,
    generate_report,
)
from shieldops.agents.cloud_snapshot_analyzer.tools import CloudSnapshotAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudSnapshotAnalyzerAgent(Agent):
    """Declarative spec for ``cloud_snapshot_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_snapshot_analyzer"
    state_model = CloudSnapshotAnalyzerState
    toolkit_factory = CloudSnapshotAnalyzerToolkit

    nodes = {
        "discover_snapshots": discover_snapshots,
        "analyze_config": analyze_config,
        "check_encryption": check_encryption,
        "detect_exposure": detect_exposure,
        "assess_risk": assess_risk,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_snapshots", "analyze_config"),
        edge("analyze_config", "check_encryption"),
        edge("check_encryption", "detect_exposure"),
        edge("assess_risk", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_exposure"
        #   routed by _should_assess_risk() — wrap with cond(...)
    ]

    entry = "discover_snapshots"
