# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_iam_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_iam_analyzer.models import CloudIAMAnalyzerState
from shieldops.agents.cloud_iam_analyzer.nodes import (
    analyze_permissions,
    collect_policies,
    compare_clouds,
    detect_risks,
    generate_report,
    optimize,
)
from shieldops.agents.cloud_iam_analyzer.tools import CloudIAMAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudIamAnalyzerAgent(Agent):
    """Declarative spec for ``cloud_iam_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_iam_analyzer"
    state_model = CloudIAMAnalyzerState
    toolkit_factory = CloudIAMAnalyzerToolkit

    nodes = {
        "collect_policies": collect_policies,
        "analyze_permissions": analyze_permissions,
        "detect_risks": detect_risks,
        "compare_clouds": compare_clouds,
        "optimize": optimize,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_policies", "analyze_permissions"),
        edge("analyze_permissions", "detect_risks"),
        edge("detect_risks", "compare_clouds"),
        edge("optimize", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "compare_clouds"
        #   routed by _should_optimize() — wrap with cond(...)
    ]

    entry = "collect_policies"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CloudIAMAnalyzerRunner`` keep working via this alias; new code
# should use ``CloudIamAnalyzerAgent`` directly through AgentRuntime.
CloudIAMAnalyzerRunner = CloudIamAnalyzerAgent
