# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_asset_graph agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_asset_graph.models import SecurityAssetGraphState
from shieldops.agents.security_asset_graph.nodes import (
    analyze_impact,
    discover_assets,
    generate_report,
    identify_critical_paths,
    map_dependencies,
    score_risk,
)
from shieldops.agents.security_asset_graph.tools import SecurityAssetGraphToolkit


class SecurityAssetGraphAgent(Agent):
    """Declarative spec for ``security_asset_graph`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_asset_graph"
    state_model = SecurityAssetGraphState
    toolkit_factory = SecurityAssetGraphToolkit

    nodes = {
        "discover_assets": discover_assets,
        "map_dependencies": map_dependencies,
        "analyze_impact": analyze_impact,
        "identify_critical_paths": identify_critical_paths,
        "score_risk": score_risk,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_assets", "map_dependencies"),
        edge("map_dependencies", "analyze_impact"),
        edge("analyze_impact", "identify_critical_paths"),
        edge("score_risk", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "identify_critical_paths"
        #   routed by _should_score() — wrap with cond(...)
    ]

    entry = "discover_assets"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityAssetGraphRunner`` keep working via this alias; new code
# should use ``SecurityAssetGraphAgent`` directly through AgentRuntime.
SecurityAssetGraphRunner = SecurityAssetGraphAgent
