# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the nl_query agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.nl_query.models import NLQueryState
from shieldops.agents.nl_query.nodes import (
    execute,
    format_output,
    generate_sql,
    handle_error,
    parse_question,
    validate_sql_node,
)
from shieldops.agents.nl_query.tools import NLQueryToolkit
from shieldops.agents.runtime import END, Agent, edge


class NlQueryAgent(Agent):
    """Declarative spec for ``nl_query`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "nl_query"
    state_model = NLQueryState
    toolkit_factory = NLQueryToolkit

    nodes = {
        "parse_question": parse_question,
        "generate_sql": generate_sql,
        "validate_sql": validate_sql_node,
        "execute": execute,
        "format_output": format_output,
        "handle_error": handle_error,
    }

    edges = [
        edge("parse_question", "generate_sql"),
        edge("format_output", END),
        edge("handle_error", END),
        # TODO: conditional edge from "generate_sql"
        #   routed by _route_after_generate() — wrap with cond(...)
        # TODO: conditional edge from "validate_sql"
        #   routed by _route_after_validate() — wrap with cond(...)
        # TODO: conditional edge from "execute"
        #   routed by _route_after_execute() — wrap with cond(...)
    ]

    entry = "parse_question"
