# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the playbook_optimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.playbook_optimizer.models import PlaybookOptimizerState
from shieldops.agents.playbook_optimizer.nodes import (
    analyze_executions,
    identify_bottlenecks,
    report,
    simulate,
    suggest_improvements,
    validate,
)
from shieldops.agents.playbook_optimizer.tools import PlaybookOptimizerToolkit
from shieldops.agents.runtime import END, Agent, edge


class PlaybookOptimizerAgent(Agent):
    """Declarative spec for ``playbook_optimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "playbook_optimizer"
    state_model = PlaybookOptimizerState
    toolkit_factory = PlaybookOptimizerToolkit

    nodes = {
        "analyze_executions": analyze_executions,
        "identify_bottlenecks": identify_bottlenecks,
        "suggest_improvements": suggest_improvements,
        "simulate": simulate,
        "validate": validate,
        "report": report,
    }

    edges = [
        edge("validate", "report"),
        edge("report", END),
        # TODO: cond(...) from "analyze_executions" via _check_error()
        # TODO: cond(...) from "identify_bottlenecks" via _check_error()
        # TODO: cond(...) from "suggest_improvements" via _check_error()
        # TODO: cond(...) from "simulate" via _check_error()
    ]

    entry = "analyze_executions"
