# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the vendor_risk_assessor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.vendor_risk_assessor.models import VendorRiskAssessorState
from shieldops.agents.vendor_risk_assessor.nodes import (
    classify_vendor,
    collect_data,
    evaluate_controls,
    recommend,
    report,
    score_risk,
)
from shieldops.agents.vendor_risk_assessor.tools import VendorRiskAssessorToolkit


class VendorRiskAssessorAgent(Agent):
    """Declarative spec for ``vendor_risk_assessor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "vendor_risk_assessor"
    state_model = VendorRiskAssessorState
    toolkit_factory = VendorRiskAssessorToolkit

    nodes = {
        "collect_data": collect_data,
        "score_risk": score_risk,
        "evaluate_controls": evaluate_controls,
        "classify_vendor": classify_vendor,
        "recommend": recommend,
        "report": report,
    }

    edges = [
        edge("recommend", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_data" via _check_error()
        # TODO: cond(...) from "score_risk" via _check_error()
        # TODO: cond(...) from "evaluate_controls" via _check_error()
        # TODO: cond(...) from "classify_vendor" via _check_error()
    ]

    entry = "collect_data"
