# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the access_review agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.access_review.models import AccessReviewState
from shieldops.agents.access_review.nodes import (
    analyze_access,
    certify,
    collect_entitlements,
    generate_tasks,
    identify_violations,
    report,
)
from shieldops.agents.access_review.tools import AccessReviewToolkit
from shieldops.agents.runtime import END, Agent, edge


class AccessReviewAgent(Agent):
    """Declarative spec for ``access_review`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "access_review"
    state_model = AccessReviewState
    toolkit_factory = AccessReviewToolkit

    nodes = {
        "collect_entitlements": collect_entitlements,
        "analyze_access": analyze_access,
        "identify_violations": identify_violations,
        "generate_tasks": generate_tasks,
        "certify": certify,
        "report": report,
    }

    edges = [
        edge("collect_entitlements", "analyze_access"),
        edge("identify_violations", "generate_tasks"),
        edge("certify", "report"),
        edge("report", END),
        # TODO: conditional edge from "analyze_access"
        #   routed by has_violations() — wrap with cond(...)
        # TODO: conditional edge from "generate_tasks"
        #   routed by has_tasks() — wrap with cond(...)
    ]

    entry = "collect_entitlements"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AccessReviewRunner`` keep working via this alias; new code
# should use ``AccessReviewAgent`` directly through AgentRuntime.
AccessReviewRunner = AccessReviewAgent
