# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_hunter agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_hunter.models import ThreatHunterState
from shieldops.agents.threat_hunter.nodes import (
    analyze_behavior,
    assess_threat,
    check_mitre,
    collect_data,
    correlate_findings,
    define_scope,
    generate_hypothesis,
    recommend_response,
    sweep_iocs,
    track_effectiveness,
)
from shieldops.agents.threat_hunter.tools import ThreatHunterToolkit


class ThreatHunterAgent(Agent):
    """Declarative spec for ``threat_hunter`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_hunter"
    state_model = ThreatHunterState
    toolkit_factory = ThreatHunterToolkit

    nodes = {
        "generate_hypothesis": generate_hypothesis,
        "define_scope": define_scope,
        "collect_data": collect_data,
        "sweep_iocs": sweep_iocs,
        "analyze_behavior": analyze_behavior,
        "check_mitre": check_mitre,
        "correlate_findings": correlate_findings,
        "assess_threat": assess_threat,
        "recommend_response": recommend_response,
        "track_effectiveness": track_effectiveness,
    }

    edges = [
        edge("generate_hypothesis", "define_scope"),
        edge("define_scope", "collect_data"),
        edge("collect_data", "sweep_iocs"),
        edge("sweep_iocs", "analyze_behavior"),
        edge("analyze_behavior", "check_mitre"),
        edge("check_mitre", "correlate_findings"),
        edge("correlate_findings", "assess_threat"),
        edge("recommend_response", "track_effectiveness"),
        edge("track_effectiveness", END),
        # TODO: conditional edge from "assess_threat"
        #   routed by should_recommend_response() — wrap with cond(...)
    ]

    entry = "generate_hypothesis"
