# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the workflow_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.workflow_engine.models import WorkflowEngineState
from shieldops.agents.workflow_engine.nodes import (
    check_gates,
    execute_steps,
    finalize_workflow,
    load_workflow,
    report_workflow,
    validate_workflow,
)
from shieldops.agents.workflow_engine.tools import WorkflowEngineToolkit


class WorkflowEngineAgent(Agent):
    """Declarative spec for ``workflow_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "workflow_engine"
    state_model = WorkflowEngineState
    toolkit_factory = WorkflowEngineToolkit

    nodes = {
        "load_workflow": load_workflow,
        "validate_workflow": validate_workflow,
        "execute_steps": execute_steps,
        "check_gates": check_gates,
        "finalize_workflow": finalize_workflow,
        "report_workflow": report_workflow,
    }

    edges = [
        edge("execute_steps", "check_gates"),
        edge("check_gates", "finalize_workflow"),
        edge("finalize_workflow", "report_workflow"),
        edge("report_workflow", END),
        # TODO: cond(...) from "load_workflow" via should_continue_after_load()
        # TODO: cond(...) from "validate_workflow" via should_continue_after_validate()
    ]

    entry = "load_workflow"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``WorkflowEngineRunner`` keep working via this alias; new code
# should use ``WorkflowEngineAgent`` directly through AgentRuntime.
WorkflowEngineRunner = WorkflowEngineAgent
