# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the pci_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.pci_scanner.models import PCIScannerState
from shieldops.agents.pci_scanner.nodes import (
    check_requirements,
    complete_saq,
    generate_report,
    map_cde,
    run_asv_scan,
)
from shieldops.agents.pci_scanner.tools import PCIScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class PciScannerAgent(Agent):
    """Declarative spec for ``pci_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "pci_scanner"
    state_model = PCIScannerState
    toolkit_factory = PCIScannerToolkit

    nodes = {
        "map_cde": map_cde,
        "check_requirements": check_requirements,
        "asv_scan": run_asv_scan,
        "complete_saq": complete_saq,
        "generate_report": generate_report,
    }

    edges = [
        edge("check_requirements", "asv_scan"),
        edge("asv_scan", "complete_saq"),
        edge("complete_saq", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "map_cde"
        #   routed by _route_after_cde() — wrap with cond(...)
    ]

    entry = "map_cde"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``PCIScannerRunner`` keep working via this alias; new code
# should use ``PciScannerAgent`` directly through AgentRuntime.
PCIScannerRunner = PciScannerAgent
