# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_config_assessor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_config_assessor.models import SecurityConfigAssessorState
from shieldops.agents.security_config_assessor.nodes import (
    benchmark_check,
    detect_drift,
    generate_fixes,
    generate_report,
    inventory_systems,
    scan_configs,
)
from shieldops.agents.security_config_assessor.tools import SecurityConfigAssessorToolkit


class SecurityConfigAssessorAgent(Agent):
    """Declarative spec for ``security_config_assessor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_config_assessor"
    state_model = SecurityConfigAssessorState
    toolkit_factory = SecurityConfigAssessorToolkit

    nodes = {
        "inventory_systems": inventory_systems,
        "scan_configs": scan_configs,
        "benchmark_check": benchmark_check,
        "detect_drift": detect_drift,
        "generate_fixes": generate_fixes,
        "generate_report": generate_report,
    }

    edges = [
        edge("inventory_systems", "scan_configs"),
        edge("scan_configs", "benchmark_check"),
        edge("benchmark_check", "detect_drift"),
        edge("generate_fixes", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_drift"
        #   routed by _has_drifts() — wrap with cond(...)
    ]

    entry = "inventory_systems"
