# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cctv_analytics agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cctv_analytics.models import CCTVAnalyticsState
from shieldops.agents.cctv_analytics.nodes import (
    alert,
    analyze_behavior,
    classify_events,
    collect_feeds,
    detect_motion,
    report,
)
from shieldops.agents.cctv_analytics.tools import CCTVAnalyticsToolkit
from shieldops.agents.runtime import END, Agent, edge


class CctvAnalyticsAgent(Agent):
    """Declarative spec for ``cctv_analytics`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cctv_analytics"
    state_model = CCTVAnalyticsState
    toolkit_factory = CCTVAnalyticsToolkit

    nodes = {
        "collect_feeds": collect_feeds,
        "detect_motion": detect_motion,
        "analyze_behavior": analyze_behavior,
        "classify_events": classify_events,
        "alert": alert,
        "report": report,
    }

    edges = [
        edge("alert", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_feeds" via _check_error()
        # TODO: cond(...) from "detect_motion" via _check_error()
        # TODO: cond(...) from "analyze_behavior" via _check_error()
        # TODO: cond(...) from "classify_events" via _check_error()
    ]

    entry = "collect_feeds"
