# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ai_red_team agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ai_red_team.models import AIRedTeamState
from shieldops.agents.ai_red_team.nodes import (
    analyze_results,
    chain_exploits,
    execute_probes,
    generate_findings,
    generate_scenarios,
    select_techniques,
)
from shieldops.agents.ai_red_team.tools import AIRedTeamToolkit
from shieldops.agents.runtime import END, Agent, edge


class AiRedTeamAgent(Agent):
    """Declarative spec for ``ai_red_team`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ai_red_team"
    state_model = AIRedTeamState
    toolkit_factory = AIRedTeamToolkit

    nodes = {
        "generate_scenarios": generate_scenarios,
        "select_techniques": select_techniques,
        "execute_probes": execute_probes,
        "analyze_results": analyze_results,
        "chain_exploits": chain_exploits,
        "generate_findings": generate_findings,
    }

    edges = [
        edge("generate_scenarios", "select_techniques"),
        edge("select_techniques", "execute_probes"),
        edge("execute_probes", "analyze_results"),
        edge("chain_exploits", "generate_findings"),
        edge("generate_findings", END),
        # TODO: conditional edge from "analyze_results"
        #   routed by should_chain_exploits() — wrap with cond(...)
    ]

    entry = "generate_scenarios"
