# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the agent_trust_broker agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.agent_trust_broker.models import AgentTrustBrokerState
from shieldops.agents.agent_trust_broker.nodes import (
    establish_trust,
    generate_report,
    monitor_behavior,
    register_agents,
    revoke_compromised,
    validate_identity,
)
from shieldops.agents.agent_trust_broker.tools import AgentTrustBrokerToolkit
from shieldops.agents.runtime import END, Agent, edge


class AgentTrustBrokerAgent(Agent):
    """Declarative spec for ``agent_trust_broker`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "agent_trust_broker"
    state_model = AgentTrustBrokerState
    toolkit_factory = AgentTrustBrokerToolkit

    nodes = {
        "register_agents": register_agents,
        "validate_identity": validate_identity,
        "establish_trust": establish_trust,
        "monitor_behavior": monitor_behavior,
        "revoke_compromised": revoke_compromised,
        "generate_report": generate_report,
    }

    edges = [
        edge("register_agents", "validate_identity"),
        edge("establish_trust", "monitor_behavior"),
        edge("revoke_compromised", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "validate_identity" via _should_establish()
        # TODO: cond(...) from "monitor_behavior" via _should_revoke()
    ]

    entry = "register_agents"
