# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the network_traffic_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.network_traffic_analyzer.models import NetworkTrafficAnalyzerState
from shieldops.agents.network_traffic_analyzer.nodes import (
    analyze_patterns,
    capture_flows,
    classify_threats,
    detect_anomalies,
    enforce_policies,
    generate_report,
)
from shieldops.agents.network_traffic_analyzer.tools import NetworkTrafficAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class NetworkTrafficAnalyzerAgent(Agent):
    """Declarative spec for ``network_traffic_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "network_traffic_analyzer"
    state_model = NetworkTrafficAnalyzerState
    toolkit_factory = NetworkTrafficAnalyzerToolkit

    nodes = {
        "capture_flows": capture_flows,
        "analyze_patterns": analyze_patterns,
        "detect_anomalies": detect_anomalies,
        "classify_threats": classify_threats,
        "enforce_policies": enforce_policies,
        "generate_report": generate_report,
    }

    edges = [
        edge("capture_flows", "analyze_patterns"),
        edge("analyze_patterns", "detect_anomalies"),
        edge("detect_anomalies", "classify_threats"),
        edge("enforce_policies", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "classify_threats"
        #   routed by _has_anomalies() — wrap with cond(...)
    ]

    entry = "capture_flows"
