# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the log_anomaly_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.log_anomaly_detector.models import LogAnomalyDetectorState
from shieldops.agents.log_anomaly_detector.nodes import (
    correlate_events,
    detect_anomalies,
    generate_report,
    ingest_logs,
    parse_patterns,
    prioritize_alerts,
)
from shieldops.agents.log_anomaly_detector.tools import LogAnomalyDetectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class LogAnomalyDetectorAgent(Agent):
    """Declarative spec for ``log_anomaly_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "log_anomaly_detector"
    state_model = LogAnomalyDetectorState
    toolkit_factory = LogAnomalyDetectorToolkit

    nodes = {
        "ingest_logs": ingest_logs,
        "parse_patterns": parse_patterns,
        "detect_anomalies": detect_anomalies,
        "correlate_events": correlate_events,
        "prioritize_alerts": prioritize_alerts,
        "generate_report": generate_report,
    }

    edges = [
        edge("parse_patterns", "detect_anomalies"),
        edge("correlate_events", "prioritize_alerts"),
        edge("prioritize_alerts", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "ingest_logs"
        #   routed by _should_parse() — wrap with cond(...)
        # TODO: conditional edge from "detect_anomalies"
        #   routed by _should_correlate() — wrap with cond(...)
    ]

    entry = "ingest_logs"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``LogAnomalyDetectorRunner`` keep working via this alias; new code
# should use ``LogAnomalyDetectorAgent`` directly through AgentRuntime.
LogAnomalyDetectorRunner = LogAnomalyDetectorAgent
