# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the email_dlp_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.email_dlp_monitor.models import EmailDLPMonitorState
from shieldops.agents.email_dlp_monitor.nodes import (
    analyze_attachments,
    audit_log,
    detect_pii,
    enforce_policy,
    generate_report,
    scan_outbound,
)
from shieldops.agents.email_dlp_monitor.tools import EmailDLPMonitorToolkit
from shieldops.agents.runtime import END, Agent, edge


class EmailDlpMonitorAgent(Agent):
    """Declarative spec for ``email_dlp_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "email_dlp_monitor"
    state_model = EmailDLPMonitorState
    toolkit_factory = EmailDLPMonitorToolkit

    nodes = {
        "scan_outbound": scan_outbound,
        "detect_pii": detect_pii,
        "analyze_attachments": analyze_attachments,
        "enforce_policy": enforce_policy,
        "audit_log": audit_log,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_outbound", "detect_pii"),
        edge("detect_pii", "analyze_attachments"),
        edge("analyze_attachments", "enforce_policy"),
        edge("enforce_policy", "audit_log"),
        edge("audit_log", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "scan_outbound"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``EmailDLPMonitorRunner`` keep working via this alias; new code
# should use ``EmailDlpMonitorAgent`` directly through AgentRuntime.
EmailDLPMonitorRunner = EmailDlpMonitorAgent
