# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_security_posture agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_security_posture.models import DataSecurityPostureState
from shieldops.agents.data_security_posture.nodes import (
    apply_controls,
    assess_risks,
    classify_data,
    discover_data_stores,
    generate_report,
    validate_posture,
)
from shieldops.agents.data_security_posture.tools import DataSecurityPostureToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataSecurityPostureAgent(Agent):
    """Declarative spec for ``data_security_posture`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_security_posture"
    state_model = DataSecurityPostureState
    toolkit_factory = DataSecurityPostureToolkit

    nodes = {
        "discover_data_stores": discover_data_stores,
        "classify_data": classify_data,
        "assess_risks": assess_risks,
        "apply_controls": apply_controls,
        "validate_posture": validate_posture,
        "generate_report": generate_report,
    }

    edges = [
        edge("classify_data", "assess_risks"),
        edge("apply_controls", "validate_posture"),
        edge("validate_posture", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "discover_data_stores" via should_classify()
        # TODO: cond(...) from "assess_risks" via should_apply_controls()
    ]

    entry = "discover_data_stores"
