# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the dns_threat_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.dns_threat_analyzer.models import DNSThreatAnalyzerState
from shieldops.agents.dns_threat_analyzer.nodes import (
    analyze_patterns,
    classify_domains,
    collect_dns_logs,
    detect_threats,
    enforce_blocks,
    generate_report,
)
from shieldops.agents.dns_threat_analyzer.tools import DNSThreatAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DnsThreatAnalyzerAgent(Agent):
    """Declarative spec for ``dns_threat_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "dns_threat_analyzer"
    state_model = DNSThreatAnalyzerState
    toolkit_factory = DNSThreatAnalyzerToolkit

    nodes = {
        "collect_dns_logs": collect_dns_logs,
        "analyze_patterns": analyze_patterns,
        "detect_threats": detect_threats,
        "classify_domains": classify_domains,
        "enforce_blocks": enforce_blocks,
        "report": generate_report,
    }

    edges = [
        edge("collect_dns_logs", "analyze_patterns"),
        edge("analyze_patterns", "detect_threats"),
        edge("detect_threats", "classify_domains"),
        edge("classify_domains", "enforce_blocks"),
        edge("enforce_blocks", "report"),
        edge("report", END),
    ]

    entry = "collect_dns_logs"
