# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the session_hijack_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.session_hijack_detector.models import SessionHijackDetectorState
from shieldops.agents.session_hijack_detector.nodes import (
    analyze_anomalies,
    assess_risk,
    collect_sessions,
    correlate_indicators,
    report,
    respond,
)
from shieldops.agents.session_hijack_detector.tools import SessionHijackDetectorToolkit


class SessionHijackDetectorAgent(Agent):
    """Declarative spec for ``session_hijack_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "session_hijack_detector"
    state_model = SessionHijackDetectorState
    toolkit_factory = SessionHijackDetectorToolkit

    nodes = {
        "collect_sessions": collect_sessions,
        "analyze_anomalies": analyze_anomalies,
        "correlate_indicators": correlate_indicators,
        "assess_risk": assess_risk,
        "respond": respond,
        "report": report,
    }

    edges = [
        edge("collect_sessions", "analyze_anomalies"),
        edge("correlate_indicators", "assess_risk"),
        edge("respond", "report"),
        edge("report", END),
        # TODO: conditional edge from "analyze_anomalies"
        #   routed by should_correlate() — wrap with cond(...)
        # TODO: conditional edge from "assess_risk"
        #   routed by should_respond() — wrap with cond(...)
    ]

    entry = "collect_sessions"
