# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the detection_engineering agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.detection_engineering.models import DetectionEngineeringState
from shieldops.agents.detection_engineering.nodes import (
    assess_coverage,
    backtest_and_tune,
    create_rules,
    deploy_rules,
)
from shieldops.agents.detection_engineering.tools import DetectionEngineeringToolkit
from shieldops.agents.runtime import END, Agent, edge


class DetectionEngineeringAgent(Agent):
    """Declarative spec for ``detection_engineering`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "detection_engineering"
    state_model = DetectionEngineeringState
    toolkit_factory = DetectionEngineeringToolkit

    nodes = {
        "assess_coverage": assess_coverage,
        "create_rules": create_rules,
        "test_and_tune": backtest_and_tune,
        "deploy_rules": deploy_rules,
    }

    edges = [
        edge("assess_coverage", "create_rules"),
        edge("create_rules", "test_and_tune"),
        edge("deploy_rules", END),
        # TODO: conditional edge from "test_and_tune"
        #   routed by _should_deploy() — wrap with cond(...)
    ]

    entry = "assess_coverage"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DetectionEngineeringRunner`` keep working via this alias; new code
# should use ``DetectionEngineeringAgent`` directly through AgentRuntime.
DetectionEngineeringRunner = DetectionEngineeringAgent
