# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the zero_trust_validator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.zero_trust_validator.models import ZeroTrustValidatorState
from shieldops.agents.zero_trust_validator.nodes import (
    assess_posture,
    check_identity,
    inspect_traffic,
    inventory_assets,
    report,
    verify_access,
)
from shieldops.agents.zero_trust_validator.tools import ZeroTrustValidatorToolkit


class ZeroTrustValidatorAgent(Agent):
    """Declarative spec for ``zero_trust_validator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "zero_trust_validator"
    state_model = ZeroTrustValidatorState
    toolkit_factory = ZeroTrustValidatorToolkit

    nodes = {
        "inventory_assets": inventory_assets,
        "check_identity": check_identity,
        "verify_access": verify_access,
        "inspect_traffic": inspect_traffic,
        "assess_posture": assess_posture,
        "report": report,
    }

    edges = [
        edge("assess_posture", "report"),
        edge("report", END),
        # TODO: cond(...) from "inventory_assets" via _check_error()
        # TODO: cond(...) from "check_identity" via _check_error()
        # TODO: cond(...) from "verify_access" via _check_error()
        # TODO: cond(...) from "inspect_traffic" via _check_error()
    ]

    entry = "inventory_assets"
