# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the auto_remediation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.auto_remediation.models import AutoRemediationState
from shieldops.agents.auto_remediation.nodes import (
    assess_issue,
    execute_fix,
    finalize_remediation,
    plan_remediation,
    verify_resolution,
)
from shieldops.agents.auto_remediation.tools import AutoRemediationToolkit
from shieldops.agents.runtime import END, Agent, edge


class AutoRemediationAgent(Agent):
    """Declarative spec for ``auto_remediation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "auto_remediation"
    state_model = AutoRemediationState
    toolkit_factory = AutoRemediationToolkit

    nodes = {
        "assess_issue": assess_issue,
        "plan_remediation": plan_remediation,
        "execute_fix": execute_fix,
        "verify_resolution": verify_resolution,
        "finalize_remediation": finalize_remediation,
    }

    edges = [
        edge("plan_remediation", "execute_fix"),
        edge("execute_fix", "verify_resolution"),
        edge("verify_resolution", "finalize_remediation"),
        edge("finalize_remediation", END),
        # TODO: cond(...) from "assess_issue" via should_continue()
    ]

    entry = "assess_issue"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AutoRemediationRunner`` keep working via this alias; new code
# should use ``AutoRemediationAgent`` directly through AgentRuntime.
AutoRemediationRunner = AutoRemediationAgent
