# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the sox_auditor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.sox_auditor.models import SOXAuditorState
from shieldops.agents.sox_auditor.nodes import (
    document,
    evaluate_deficiencies,
    identify_controls,
    remediate,
    report,
    test_controls,
)
from shieldops.agents.sox_auditor.tools import SOXAuditorToolkit


class SoxAuditorAgent(Agent):
    """Declarative spec for ``sox_auditor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "sox_auditor"
    state_model = SOXAuditorState
    toolkit_factory = SOXAuditorToolkit

    nodes = {
        "identify_controls": identify_controls,
        "test_controls": test_controls,
        "evaluate_deficiencies": evaluate_deficiencies,
        "remediate": remediate,
        "document": document,
        "report": report,
    }

    edges = [
        edge("document", "report"),
        edge("report", END),
        # TODO: cond(...) from "identify_controls" via _check_error()
        # TODO: cond(...) from "test_controls" via _check_error()
        # TODO: cond(...) from "evaluate_deficiencies" via _check_error()
        # TODO: cond(...) from "remediate" via _check_error()
    ]

    entry = "identify_controls"
