# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_intel agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_intel.models import ThreatIntelState
from shieldops.agents.threat_intel.nodes import (
    assess_threats,
    collect_indicators,
    correlate_observations,
    distribute_intel,
)
from shieldops.agents.threat_intel.tools import ThreatIntelToolkit


class ThreatIntelAgent(Agent):
    """Declarative spec for ``threat_intel`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_intel"
    state_model = ThreatIntelState
    toolkit_factory = ThreatIntelToolkit

    nodes = {
        "collect_indicators": collect_indicators,
        "correlate_observations": correlate_observations,
        "assess_threats": assess_threats,
        "distribute_intel": distribute_intel,
    }

    edges = [
        edge("collect_indicators", "correlate_observations"),
        edge("correlate_observations", "assess_threats"),
        edge("distribute_intel", END),
        # TODO: cond(...) from "assess_threats" via should_distribute()
    ]

    entry = "collect_indicators"
