# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the soar_orchestration agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.soar_orchestration.models import SOAROrchestrationState
from shieldops.agents.soar_orchestration.nodes import (
    execute_actions,
    finalize_orchestration,
    select_playbook,
    triage_incident,
    validate_response,
)
from shieldops.agents.soar_orchestration.tools import SOAROrchestrationToolkit


class SoarOrchestrationAgent(Agent):
    """Declarative spec for ``soar_orchestration`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "soar_orchestration"
    state_model = SOAROrchestrationState
    toolkit_factory = SOAROrchestrationToolkit

    nodes = {
        "triage_incident": triage_incident,
        "select_playbook": select_playbook,
        "execute_actions": execute_actions,
        "validate_response": validate_response,
        "finalize_orchestration": finalize_orchestration,
    }

    edges = [
        edge("select_playbook", "execute_actions"),
        edge("execute_actions", "validate_response"),
        edge("validate_response", "finalize_orchestration"),
        edge("finalize_orchestration", END),
        # TODO: conditional edge from "triage_incident"
        #   routed by should_continue() — wrap with cond(...)
    ]

    entry = "triage_incident"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SOAROrchestrationRunner`` keep working via this alias; new code
# should use ``SoarOrchestrationAgent`` directly through AgentRuntime.
SOAROrchestrationRunner = SoarOrchestrationAgent
