# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ai_blue_team agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ai_blue_team.models import AIBlueTeamState
from shieldops.agents.ai_blue_team.nodes import (
    analyze_findings,
    apply_hardening,
    create_detection_rules,
    generate_hardening_plan,
    identify_gaps,
    validate,
)
from shieldops.agents.ai_blue_team.tools import AIBlueTeamToolkit
from shieldops.agents.runtime import END, Agent, edge


class AiBlueTeamAgent(Agent):
    """Declarative spec for ``ai_blue_team`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ai_blue_team"
    state_model = AIBlueTeamState
    toolkit_factory = AIBlueTeamToolkit

    nodes = {
        "analyze_findings": analyze_findings,
        "identify_gaps": identify_gaps,
        "generate_hardening_plan": generate_hardening_plan,
        "apply_hardening": apply_hardening,
        "create_detection_rules": create_detection_rules,
        "validate": validate,
    }

    edges = [
        edge("analyze_findings", "identify_gaps"),
        edge("identify_gaps", "generate_hardening_plan"),
        edge("generate_hardening_plan", "apply_hardening"),
        edge("apply_hardening", "create_detection_rules"),
        edge("create_detection_rules", "validate"),
        edge("validate", END),
    ]

    entry = "analyze_findings"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AIBlueTeamRunner`` keep working via this alias; new code
# should use ``AiBlueTeamAgent`` directly through AgentRuntime.
AIBlueTeamRunner = AiBlueTeamAgent
