# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the threat_actor_profiler agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.threat_actor_profiler.models import ThreatActorProfilerState
from shieldops.agents.threat_actor_profiler.nodes import (
    assess_targeting,
    build_profiles,
    cluster_activity,
    collect_indicators,
    generate_report,
    map_ttps,
)
from shieldops.agents.threat_actor_profiler.tools import ThreatActorProfilerToolkit


class ThreatActorProfilerAgent(Agent):
    """Declarative spec for ``threat_actor_profiler`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "threat_actor_profiler"
    state_model = ThreatActorProfilerState
    toolkit_factory = ThreatActorProfilerToolkit

    nodes = {
        "collect_indicators": collect_indicators,
        "cluster_activity": cluster_activity,
        "build_profiles": build_profiles,
        "map_ttps": map_ttps,
        "assess_targeting": assess_targeting,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_indicators", "cluster_activity"),
        edge("build_profiles", "map_ttps"),
        edge("assess_targeting", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "cluster_activity" via _should_build_profiles()
        # TODO: cond(...) from "map_ttps" via _should_assess()
    ]

    entry = "collect_indicators"
