# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the itdr agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.itdr.models import ITDRState
from shieldops.agents.itdr.nodes import (
    analyze_attack_paths,
    detect_threats,
    finalize_detection,
    respond_to_threats,
    scan_identities,
)
from shieldops.agents.itdr.tools import ITDRToolkit
from shieldops.agents.runtime import END, Agent, edge


class ItdrAgent(Agent):
    """Declarative spec for ``itdr`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "itdr"
    state_model = ITDRState
    toolkit_factory = ITDRToolkit

    nodes = {
        "scan_identities": scan_identities,
        "detect_threats": detect_threats,
        "analyze_attack_paths": analyze_attack_paths,
        "respond_to_threats": respond_to_threats,
        "finalize_detection": finalize_detection,
    }

    edges = [
        edge("detect_threats", "analyze_attack_paths"),
        edge("analyze_attack_paths", "respond_to_threats"),
        edge("respond_to_threats", "finalize_detection"),
        edge("finalize_detection", END),
        # TODO: conditional edge from "scan_identities"
        #   routed by should_continue() — wrap with cond(...)
    ]

    entry = "scan_identities"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ITDRRunner`` keep working via this alias; new code
# should use ``ItdrAgent`` directly through AgentRuntime.
ITDRRunner = ItdrAgent
