# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the alert_enrichment_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.alert_enrichment_engine.models import AlertEnrichmentEngineState
from shieldops.agents.alert_enrichment_engine.nodes import (
    correlate_intel,
    ingest_alert,
    lookup_context,
    report,
    route,
    score_priority,
)
from shieldops.agents.alert_enrichment_engine.tools import AlertEnrichmentEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class AlertEnrichmentEngineAgent(Agent):
    """Declarative spec for ``alert_enrichment_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "alert_enrichment_engine"
    state_model = AlertEnrichmentEngineState
    toolkit_factory = AlertEnrichmentEngineToolkit

    nodes = {
        "ingest_alert": ingest_alert,
        "lookup_context": lookup_context,
        "correlate_intel": correlate_intel,
        "score_priority": score_priority,
        "route": route,
        "report": report,
    }

    edges = [
        edge("route", "report"),
        edge("report", END),
        # TODO: cond(...) from "ingest_alert" via _check_error()
        # TODO: cond(...) from "lookup_context" via _check_error()
        # TODO: cond(...) from "correlate_intel" via _check_error()
        # TODO: cond(...) from "score_priority" via _check_error()
    ]

    entry = "ingest_alert"
