# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the industrial_protocol_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.industrial_protocol_analyzer.models import IndustrialProtocolAnalyzerState
from shieldops.agents.industrial_protocol_analyzer.nodes import (
    assess_risk,
    capture_traffic,
    decode_protocols,
    detect_anomalies,
    report,
    validate_commands,
)
from shieldops.agents.industrial_protocol_analyzer.tools import IndustrialProtocolAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class IndustrialProtocolAnalyzerAgent(Agent):
    """Declarative spec for ``industrial_protocol_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "industrial_protocol_analyzer"
    state_model = IndustrialProtocolAnalyzerState
    toolkit_factory = IndustrialProtocolAnalyzerToolkit

    nodes = {
        "capture_traffic": capture_traffic,
        "decode_protocols": decode_protocols,
        "validate_commands": validate_commands,
        "detect_anomalies": detect_anomalies,
        "assess_risk": assess_risk,
        "report": report,
    }

    edges = [
        edge("assess_risk", "report"),
        edge("report", END),
        # TODO: cond(...) from "capture_traffic" via _check_error()
        # TODO: cond(...) from "decode_protocols" via _check_error()
        # TODO: cond(...) from "validate_commands" via _check_error()
        # TODO: cond(...) from "detect_anomalies" via _check_error()
    ]

    entry = "capture_traffic"
