# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_signal_router agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_signal_router.models import SecuritySignalRouterState
from shieldops.agents.security_signal_router.nodes import (
    classify_signals,
    dispatch_signals,
    evaluate_routing,
    generate_report,
    ingest_signals,
    track_outcomes,
)
from shieldops.agents.security_signal_router.tools import SecuritySignalRouterToolkit


class SecuritySignalRouterAgent(Agent):
    """Declarative spec for ``security_signal_router`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_signal_router"
    state_model = SecuritySignalRouterState
    toolkit_factory = SecuritySignalRouterToolkit

    nodes = {
        "ingest_signals": ingest_signals,
        "classify_signals": classify_signals,
        "evaluate_routing": evaluate_routing,
        "dispatch_signals": dispatch_signals,
        "track_outcomes": track_outcomes,
        "generate_report": generate_report,
    }

    edges = [
        edge("ingest_signals", "classify_signals"),
        edge("classify_signals", "evaluate_routing"),
        edge("track_outcomes", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "evaluate_routing" via _should_dispatch()
        # TODO: cond(...) from "dispatch_signals" via _should_track()
    ]

    entry = "ingest_signals"
