# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the adversarial_validation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.adversarial_validation.models import AdversarialValidationState
from shieldops.agents.adversarial_validation.nodes import (
    assess_effectiveness,
    collect_findings,
    execute_validation,
    report,
    select_retests,
    update_patterns,
)
from shieldops.agents.adversarial_validation.tools import AdversarialValidationToolkit
from shieldops.agents.runtime import END, Agent, edge


class AdversarialValidationAgent(Agent):
    """Declarative spec for ``adversarial_validation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "adversarial_validation"
    state_model = AdversarialValidationState
    toolkit_factory = AdversarialValidationToolkit

    nodes = {
        "collect_findings": collect_findings,
        "select_retests": select_retests,
        "execute_validation": execute_validation,
        "assess_effectiveness": assess_effectiveness,
        "update_patterns": update_patterns,
        "report": report,
    }

    edges = [
        edge("collect_findings", "select_retests"),
        edge("select_retests", "execute_validation"),
        edge("execute_validation", "assess_effectiveness"),
        edge("update_patterns", "report"),
        edge("report", END),
        # TODO: conditional edge from "assess_effectiveness"
        #   routed by should_update_patterns() — wrap with cond(...)
    ]

    entry = "collect_findings"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AdversarialValidationRunner`` keep working via this alias; new code
# should use ``AdversarialValidationAgent`` directly through AgentRuntime.
AdversarialValidationRunner = AdversarialValidationAgent
