# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the disaster_recovery agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.disaster_recovery.models import DisasterRecoveryState
from shieldops.agents.disaster_recovery.nodes import (
    assess_plans,
    identify_gaps,
    measure_rto_rpo,
    remediate,
    report,
    test_failover,
)
from shieldops.agents.disaster_recovery.tools import DisasterRecoveryToolkit
from shieldops.agents.runtime import END, Agent, edge


class DisasterRecoveryAgent(Agent):
    """Declarative spec for ``disaster_recovery`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "disaster_recovery"
    state_model = DisasterRecoveryState
    toolkit_factory = DisasterRecoveryToolkit

    nodes = {
        "assess_plans": assess_plans,
        "test_failover": test_failover,
        "measure_rto_rpo": measure_rto_rpo,
        "identify_gaps": identify_gaps,
        "remediate": remediate,
        "report": report,
    }

    edges = [
        edge("assess_plans", "test_failover"),
        edge("test_failover", "measure_rto_rpo"),
        edge("measure_rto_rpo", "identify_gaps"),
        edge("remediate", "report"),
        edge("report", END),
        # TODO: conditional edge from "identify_gaps"
        #   routed by should_remediate() — wrap with cond(...)
    ]

    entry = "assess_plans"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DisasterRecoveryRunner`` keep working via this alias; new code
# should use ``DisasterRecoveryAgent`` directly through AgentRuntime.
DisasterRecoveryRunner = DisasterRecoveryAgent
