# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the service_account_guardian agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.service_account_guardian.models import ServiceAccountGuardianState
from shieldops.agents.service_account_guardian.nodes import (
    assess_risk,
    audit_permissions,
    detect_orphans,
    discover_accounts,
    generate_report,
    remediate,
)
from shieldops.agents.service_account_guardian.tools import ServiceAccountGuardianToolkit


class ServiceAccountGuardianAgent(Agent):
    """Declarative spec for ``service_account_guardian`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "service_account_guardian"
    state_model = ServiceAccountGuardianState
    toolkit_factory = ServiceAccountGuardianToolkit

    nodes = {
        "discover_accounts": discover_accounts,
        "audit_permissions": audit_permissions,
        "detect_orphans": detect_orphans,
        "assess_risk": assess_risk,
        "remediate": remediate,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_accounts", "audit_permissions"),
        edge("audit_permissions", "detect_orphans"),
        edge("detect_orphans", "assess_risk"),
        edge("remediate", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "assess_risk"
        #   routed by _should_remediate() — wrap with cond(...)
    ]

    entry = "discover_accounts"
