# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the compliance_drift_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.compliance_drift_monitor.models import ComplianceDriftMonitorState
from shieldops.agents.compliance_drift_monitor.nodes import (
    assess_impact,
    detect_drift,
    generate_report,
    load_baselines,
    plan_remediation,
    scan_current_state,
)
from shieldops.agents.compliance_drift_monitor.tools import ComplianceDriftMonitorToolkit
from shieldops.agents.runtime import END, Agent, edge


class ComplianceDriftMonitorAgent(Agent):
    """Declarative spec for ``compliance_drift_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "compliance_drift_monitor"
    state_model = ComplianceDriftMonitorState
    toolkit_factory = ComplianceDriftMonitorToolkit

    nodes = {
        "load_baselines": load_baselines,
        "scan_current_state": scan_current_state,
        "detect_drift": detect_drift,
        "assess_impact": assess_impact,
        "plan_remediation": plan_remediation,
        "generate_report": generate_report,
    }

    edges = [
        edge("load_baselines", "scan_current_state"),
        edge("scan_current_state", "detect_drift"),
        edge("plan_remediation", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "detect_drift" via _should_assess()
        # TODO: cond(...) from "assess_impact" via _should_remediate()
    ]

    entry = "load_baselines"
