# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the postmortem_generator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.postmortem_generator.models import PostmortemGeneratorState
from shieldops.agents.postmortem_generator.nodes import (
    analyze_root_cause,
    collect_timeline,
    draft_document,
    identify_actions,
    report,
    review_quality,
)
from shieldops.agents.postmortem_generator.tools import PostmortemGeneratorToolkit
from shieldops.agents.runtime import END, Agent, edge


class PostmortemGeneratorAgent(Agent):
    """Declarative spec for ``postmortem_generator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "postmortem_generator"
    state_model = PostmortemGeneratorState
    toolkit_factory = PostmortemGeneratorToolkit

    nodes = {
        "collect_timeline": collect_timeline,
        "analyze_root_cause": analyze_root_cause,
        "identify_actions": identify_actions,
        "draft_document": draft_document,
        "review_quality": review_quality,
        "report": report,
    }

    edges = [
        edge("collect_timeline", "analyze_root_cause"),
        edge("analyze_root_cause", "identify_actions"),
        edge("identify_actions", "draft_document"),
        edge("draft_document", "review_quality"),
        edge("review_quality", "report"),
        edge("report", END),
    ]

    entry = "collect_timeline"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``PostmortemGeneratorRunner`` keep working via this alias; new code
# should use ``PostmortemGeneratorAgent`` directly through AgentRuntime.
PostmortemGeneratorRunner = PostmortemGeneratorAgent
