# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the identity_protection agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.identity_protection.models import IdentityProtectionState
from shieldops.agents.identity_protection.nodes import (
    analyze_attack_patterns,
    collect_identity_signals,
    detect_threats,
    report,
    respond_to_threats,
    verify_containment,
)
from shieldops.agents.identity_protection.tools import IdentityProtectionToolkit
from shieldops.agents.runtime import END, Agent, edge


class IdentityProtectionAgent(Agent):
    """Declarative spec for ``identity_protection`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "identity_protection"
    state_model = IdentityProtectionState
    toolkit_factory = IdentityProtectionToolkit

    nodes = {
        "collect_identity_signals": collect_identity_signals,
        "detect_threats": detect_threats,
        "analyze_attack_patterns": analyze_attack_patterns,
        "respond_to_threats": respond_to_threats,
        "verify_containment": verify_containment,
        "report": report,
    }

    edges = [
        edge("collect_identity_signals", "detect_threats"),
        edge("detect_threats", "analyze_attack_patterns"),
        edge("respond_to_threats", "verify_containment"),
        edge("verify_containment", "report"),
        edge("report", END),
        # TODO: conditional edge from "analyze_attack_patterns"
        #   routed by has_active_threats() — wrap with cond(...)
    ]

    entry = "collect_identity_signals"
