# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the otel_collector_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.otel_collector_manager.models import OTelCollectorManagerState
from shieldops.agents.otel_collector_manager.nodes import (
    assess_requirements,
    deploy_and_verify,
    generate_config,
    monitor_health,
)
from shieldops.agents.otel_collector_manager.tools import OTelCollectorManagerToolkit
from shieldops.agents.runtime import END, Agent, edge


class OtelCollectorManagerAgent(Agent):
    """Declarative spec for ``otel_collector_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "otel_collector_manager"
    state_model = OTelCollectorManagerState
    toolkit_factory = OTelCollectorManagerToolkit

    nodes = {
        "assess": assess_requirements,
        "generate": generate_config,
        "deploy": deploy_and_verify,
        "monitor": monitor_health,
    }

    edges = [
        edge("assess", "generate"),
        edge("generate", "deploy"),
        edge("deploy", "monitor"),
        edge("monitor", END),
    ]

    entry = "assess"
