# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the apt_emulator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.apt_emulator.models import APTEmulatorState
from shieldops.agents.apt_emulator.nodes import (
    design_campaign,
    execute_recon,
    report,
    simulate_access,
    test_exfil,
    test_lateral,
    test_persistence,
)
from shieldops.agents.apt_emulator.tools import APTEmulatorToolkit
from shieldops.agents.runtime import END, Agent, edge


class AptEmulatorAgent(Agent):
    """Declarative spec for ``apt_emulator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "apt_emulator"
    state_model = APTEmulatorState
    toolkit_factory = APTEmulatorToolkit

    nodes = {
        "design_campaign": design_campaign,
        "execute_recon": execute_recon,
        "simulate_access": simulate_access,
        "test_persistence": test_persistence,
        "test_lateral": test_lateral,
        "test_exfil": test_exfil,
        "report": report,
    }

    edges = [
        edge("design_campaign", "execute_recon"),
        edge("execute_recon", "simulate_access"),
        edge("simulate_access", "test_persistence"),
        edge("test_persistence", "test_lateral"),
        edge("test_lateral", "test_exfil"),
        edge("test_exfil", "report"),
        edge("report", END),
    ]

    entry = "design_campaign"
