# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the consent_manager agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.consent_manager.models import ConsentManagerState
from shieldops.agents.consent_manager.nodes import (
    audit,
    check_expiry,
    collect_consents,
    enforce_preferences,
    report,
    validate_purposes,
)
from shieldops.agents.consent_manager.tools import ConsentManagerToolkit
from shieldops.agents.runtime import END, Agent, edge


class ConsentManagerAgent(Agent):
    """Declarative spec for ``consent_manager`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "consent_manager"
    state_model = ConsentManagerState
    toolkit_factory = ConsentManagerToolkit

    nodes = {
        "collect_consents": collect_consents,
        "validate_purposes": validate_purposes,
        "check_expiry": check_expiry,
        "enforce_preferences": enforce_preferences,
        "audit": audit,
        "report": report,
    }

    edges = [
        edge("audit", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_consents" via _check_error()
        # TODO: cond(...) from "validate_purposes" via _check_error()
        # TODO: cond(...) from "check_expiry" via _check_error()
        # TODO: cond(...) from "enforce_preferences" via _check_error()
    ]

    entry = "collect_consents"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ConsentManagerRunner`` keep working via this alias; new code
# should use ``ConsentManagerAgent`` directly through AgentRuntime.
ConsentManagerRunner = ConsentManagerAgent
