# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_roi_calculator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_roi_calculator.models import SecurityROICalculatorState
from shieldops.agents.security_roi_calculator.nodes import (
    calculate_roi,
    collect_investments,
    compare_benchmarks,
    forecast_value,
    generate_report,
    measure_outcomes,
)
from shieldops.agents.security_roi_calculator.tools import SecurityROICalculatorToolkit


class SecurityRoiCalculatorAgent(Agent):
    """Declarative spec for ``security_roi_calculator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_roi_calculator"
    state_model = SecurityROICalculatorState
    toolkit_factory = SecurityROICalculatorToolkit

    nodes = {
        "collect_investments": collect_investments,
        "measure_outcomes": measure_outcomes,
        "calculate_roi": calculate_roi,
        "compare_benchmarks": compare_benchmarks,
        "forecast": forecast_value,
        "report": generate_report,
    }

    edges = [
        edge("collect_investments", "measure_outcomes"),
        edge("measure_outcomes", "calculate_roi"),
        edge("calculate_roi", "compare_benchmarks"),
        edge("compare_benchmarks", "forecast"),
        edge("forecast", "report"),
        edge("report", END),
    ]

    entry = "collect_investments"
