# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the llm_prompt_firewall agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.llm_prompt_firewall.models import LLMPromptFirewallState
from shieldops.agents.llm_prompt_firewall.nodes import (
    analyze_intent,
    classify_risk,
    detect_injection,
    enforce_policy,
    generate_report,
    intercept_prompt,
)
from shieldops.agents.llm_prompt_firewall.tools import LLMPromptFirewallToolkit
from shieldops.agents.runtime import END, Agent, edge


class LlmPromptFirewallAgent(Agent):
    """Declarative spec for ``llm_prompt_firewall`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "llm_prompt_firewall"
    state_model = LLMPromptFirewallState
    toolkit_factory = LLMPromptFirewallToolkit

    nodes = {
        "intercept_prompt": intercept_prompt,
        "analyze_intent": analyze_intent,
        "detect_injection": detect_injection,
        "classify_risk": classify_risk,
        "enforce_policy": enforce_policy,
        "generate_report": generate_report,
    }

    edges = [
        edge("intercept_prompt", "analyze_intent"),
        edge("analyze_intent", "detect_injection"),
        edge("detect_injection", "classify_risk"),
        edge("enforce_policy", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "classify_risk"
        #   routed by _should_enforce() — wrap with cond(...)
    ]

    entry = "intercept_prompt"
