# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_telemetry_optimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_telemetry_optimizer.models import SecurityTelemetryOptimizerState
from shieldops.agents.security_telemetry_optimizer.nodes import (
    analyze_volume,
    detect_waste,
    generate_report,
    inventory_sources,
    optimize_routing,
    validate_quality,
)
from shieldops.agents.security_telemetry_optimizer.tools import SecurityTelemetryOptimizerToolkit


class SecurityTelemetryOptimizerAgent(Agent):
    """Declarative spec for ``security_telemetry_optimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_telemetry_optimizer"
    state_model = SecurityTelemetryOptimizerState
    toolkit_factory = SecurityTelemetryOptimizerToolkit

    nodes = {
        "inventory_sources": inventory_sources,
        "analyze_volume": analyze_volume,
        "detect_waste": detect_waste,
        "optimize_routing": optimize_routing,
        "validate_quality": validate_quality,
        "generate_report": generate_report,
    }

    edges = [
        edge("inventory_sources", "analyze_volume"),
        edge("analyze_volume", "detect_waste"),
        edge("detect_waste", "optimize_routing"),
        edge("validate_quality", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "optimize_routing"
        #   routed by _should_validate() — wrap with cond(...)
    ]

    entry = "inventory_sources"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityTelemetryOptimizerRunner`` keep working via this alias; new code
# should use ``SecurityTelemetryOptimizerAgent`` directly through AgentRuntime.
SecurityTelemetryOptimizerRunner = SecurityTelemetryOptimizerAgent
