# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the alert_correlation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.alert_correlation.models import AlertCorrelationState
from shieldops.agents.alert_correlation.nodes import (
    build_kill_chains,
    collect_alerts,
    correlate_alerts,
    generate_report,
    normalize_alerts,
    prioritize_incidents,
)
from shieldops.agents.alert_correlation.tools import AlertCorrelationToolkit
from shieldops.agents.runtime import END, Agent, edge


class AlertCorrelationAgent(Agent):
    """Declarative spec for ``alert_correlation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "alert_correlation"
    state_model = AlertCorrelationState
    toolkit_factory = AlertCorrelationToolkit

    nodes = {
        "collect_alerts": collect_alerts,
        "normalize_alerts": normalize_alerts,
        "correlate_alerts": correlate_alerts,
        "build_kill_chains": build_kill_chains,
        "prioritize_incidents": prioritize_incidents,
        "generate_report": generate_report,
    }

    edges = [
        edge("normalize_alerts", "correlate_alerts"),
        edge("build_kill_chains", "prioritize_incidents"),
        edge("prioritize_incidents", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "collect_alerts"
        #   routed by has_alerts() — wrap with cond(...)
        # TODO: conditional edge from "correlate_alerts"
        #   routed by has_clusters() — wrap with cond(...)
    ]

    entry = "collect_alerts"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AlertCorrelationRunner`` keep working via this alias; new code
# should use ``AlertCorrelationAgent`` directly through AgentRuntime.
AlertCorrelationRunner = AlertCorrelationAgent
