# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the agentless_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.agentless_scanner.models import AgentlessScannerState
from shieldops.agents.agentless_scanner.nodes import (
    analyze_exposure,
    check_vulns,
    discover_assets,
    generate_report,
    prioritize,
    scan_config,
)
from shieldops.agents.agentless_scanner.tools import AgentlessScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class AgentlessScannerAgent(Agent):
    """Declarative spec for ``agentless_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "agentless_scanner"
    state_model = AgentlessScannerState
    toolkit_factory = AgentlessScannerToolkit

    nodes = {
        "discover_assets": discover_assets,
        "scan_config": scan_config,
        "check_vulns": check_vulns,
        "analyze_exposure": analyze_exposure,
        "prioritize": prioritize,
        "generate_report": generate_report,
    }

    edges = [
        edge("discover_assets", "scan_config"),
        edge("scan_config", "check_vulns"),
        edge("check_vulns", "analyze_exposure"),
        edge("prioritize", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "analyze_exposure"
        #   routed by _should_prioritize() — wrap with cond(...)
    ]

    entry = "discover_assets"
