# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the unified_risk_dashboard agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.unified_risk_dashboard.models import UnifiedRiskDashboardState
from shieldops.agents.unified_risk_dashboard.nodes import (
    aggregate_risks,
    calculate_posture,
    collect_risk_signals,
    generate_report,
    normalize_scores,
    prioritize_actions,
)
from shieldops.agents.unified_risk_dashboard.tools import UnifiedRiskDashboardToolkit


class UnifiedRiskDashboardAgent(Agent):
    """Declarative spec for ``unified_risk_dashboard`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "unified_risk_dashboard"
    state_model = UnifiedRiskDashboardState
    toolkit_factory = UnifiedRiskDashboardToolkit

    nodes = {
        "collect_risk_signals": collect_risk_signals,
        "normalize_scores": normalize_scores,
        "aggregate_risks": aggregate_risks,
        "calculate_posture": calculate_posture,
        "prioritize_actions": prioritize_actions,
        "generate_report": generate_report,
    }

    edges = [
        edge("prioritize_actions", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "collect_risk_signals" via _check_error()
        # TODO: cond(...) from "normalize_scores" via _check_error()
        # TODO: cond(...) from "aggregate_risks" via _check_error()
        # TODO: cond(...) from "calculate_posture" via _check_error()
    ]

    entry = "collect_risk_signals"
