# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cost agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cost.models import CostAnalysisState
from shieldops.agents.cost.nodes import (
    detect_anomalies,
    gather_costs,
    recommend_optimizations,
    synthesize_savings,
)
from shieldops.agents.cost.tools import CostToolkit
from shieldops.agents.runtime import END, Agent, edge


class CostAgent(Agent):
    """Declarative spec for ``cost`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cost"
    state_model = CostAnalysisState
    toolkit_factory = CostToolkit

    nodes = {
        "gather_costs": gather_costs,
        "detect_anomalies": detect_anomalies,
        "recommend_optimizations": recommend_optimizations,
        "synthesize_savings": synthesize_savings,
    }

    edges = [
        edge("recommend_optimizations", "synthesize_savings"),
        edge("synthesize_savings", END),
        # TODO: conditional edge from "gather_costs"
        #   routed by should_detect_anomalies() — wrap with cond(...)
        # TODO: conditional edge from "detect_anomalies"
        #   routed by should_recommend_optimizations() — wrap with cond(...)
    ]

    entry = "gather_costs"
