# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_identity_federation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_identity_federation.models import CloudIdentityFederationState
from shieldops.agents.cloud_identity_federation.nodes import (
    analyze_trust,
    assess_risk,
    detect_misconfigs,
    discover_identities,
    map_federations,
)
from shieldops.agents.cloud_identity_federation.tools import CloudIdentityFederationToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudIdentityFederationAgent(Agent):
    """Declarative spec for ``cloud_identity_federation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_identity_federation"
    state_model = CloudIdentityFederationState
    toolkit_factory = CloudIdentityFederationToolkit

    nodes = {
        "discover_identities": discover_identities,
        "map_federations": map_federations,
        "detect_misconfigs": detect_misconfigs,
        "analyze_trust": analyze_trust,
        "assess_risk": assess_risk,
    }

    edges = [
        edge("map_federations", "detect_misconfigs"),
        edge("detect_misconfigs", "analyze_trust"),
        edge("analyze_trust", "assess_risk"),
        edge("assess_risk", END),
        # TODO: conditional edge from "discover_identities"
        #   routed by _has_error() — wrap with cond(...)
    ]

    entry = "discover_identities"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CloudIdentityFederationRunner`` keep working via this alias; new code
# should use ``CloudIdentityFederationAgent`` directly through AgentRuntime.
CloudIdentityFederationRunner = CloudIdentityFederationAgent
