# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_budget_optimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_budget_optimizer.models import SecurityBudgetOptimizerState
from shieldops.agents.security_budget_optimizer.nodes import (
    analyze_overlap,
    forecast_roi,
    generate_report,
    inventory_tools,
    measure_effectiveness,
    optimize_budget,
)
from shieldops.agents.security_budget_optimizer.tools import SecurityBudgetOptimizerToolkit


class SecurityBudgetOptimizerAgent(Agent):
    """Declarative spec for ``security_budget_optimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_budget_optimizer"
    state_model = SecurityBudgetOptimizerState
    toolkit_factory = SecurityBudgetOptimizerToolkit

    nodes = {
        "inventory_tools": inventory_tools,
        "measure_effectiveness": measure_effectiveness,
        "analyze_overlap": analyze_overlap,
        "optimize_budget": optimize_budget,
        "forecast_roi": forecast_roi,
        "generate_report": generate_report,
    }

    edges = [
        edge("measure_effectiveness", "analyze_overlap"),
        edge("analyze_overlap", "optimize_budget"),
        edge("forecast_roi", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "inventory_tools"
        #   routed by _should_measure() — wrap with cond(...)
        # TODO: conditional edge from "optimize_budget"
        #   routed by _should_forecast() — wrap with cond(...)
    ]

    entry = "inventory_tools"
