# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the deployment_guardian agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.deployment_guardian.models import DeploymentGuardianState
from shieldops.agents.deployment_guardian.nodes import (
    analyze_changes,
    approve_deployment,
    monitor_rollout,
    report,
    run_preflight,
    validate_security,
)
from shieldops.agents.deployment_guardian.tools import DeploymentGuardianToolkit
from shieldops.agents.runtime import END, Agent, edge


class DeploymentGuardianAgent(Agent):
    """Declarative spec for ``deployment_guardian`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "deployment_guardian"
    state_model = DeploymentGuardianState
    toolkit_factory = DeploymentGuardianToolkit

    nodes = {
        "analyze_changes": analyze_changes,
        "run_preflight": run_preflight,
        "validate_security": validate_security,
        "approve_deployment": approve_deployment,
        "monitor_rollout": monitor_rollout,
        "report": report,
    }

    edges = [
        edge("monitor_rollout", "report"),
        edge("report", END),
        # TODO: cond(...) from "analyze_changes" via _check_error()
        # TODO: cond(...) from "run_preflight" via _check_error()
        # TODO: cond(...) from "validate_security" via _check_error()
        # TODO: cond(...) from "approve_deployment" via _check_error()
    ]

    entry = "analyze_changes"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DeploymentGuardianRunner`` keep working via this alias; new code
# should use ``DeploymentGuardianAgent`` directly through AgentRuntime.
DeploymentGuardianRunner = DeploymentGuardianAgent
