# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the saas_security_posture agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.saas_security_posture.models import SaaSSecurityPostureState
from shieldops.agents.saas_security_posture.nodes import (
    assess_risk,
    audit_config,
    check_sharing,
    discover_apps,
    generate_report,
    remediate,
)
from shieldops.agents.saas_security_posture.tools import SaaSSecurityPostureToolkit


class SaasSecurityPostureAgent(Agent):
    """Declarative spec for ``saas_security_posture`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "saas_security_posture"
    state_model = SaaSSecurityPostureState
    toolkit_factory = SaaSSecurityPostureToolkit

    nodes = {
        "discover_apps": discover_apps,
        "audit_config": audit_config,
        "check_sharing": check_sharing,
        "assess_risk": assess_risk,
        "remediate": remediate,
        "report": generate_report,
    }

    edges = [
        edge("discover_apps", "audit_config"),
        edge("audit_config", "check_sharing"),
        edge("check_sharing", "assess_risk"),
        edge("assess_risk", "remediate"),
        edge("remediate", "report"),
        edge("report", END),
    ]

    entry = "discover_apps"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SaaSSecurityPostureRunner`` keep working via this alias; new code
# should use ``SaasSecurityPostureAgent`` directly through AgentRuntime.
SaaSSecurityPostureRunner = SaasSecurityPostureAgent
