# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the evidence_collector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.evidence_collector.models import EvidenceCollectorState
from shieldops.agents.evidence_collector.nodes import (
    chain_of_custody,
    collect_artifacts,
    hash_verify,
    identify_sources,
    package_evidence,
    report,
)
from shieldops.agents.evidence_collector.tools import EvidenceCollectorToolkit
from shieldops.agents.runtime import END, Agent, edge


class EvidenceCollectorAgent(Agent):
    """Declarative spec for ``evidence_collector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "evidence_collector"
    state_model = EvidenceCollectorState
    toolkit_factory = EvidenceCollectorToolkit

    nodes = {
        "identify_sources": identify_sources,
        "collect_artifacts": collect_artifacts,
        "hash_verify": hash_verify,
        "chain_of_custody": chain_of_custody,
        "package_evidence": package_evidence,
        "report": report,
    }

    edges = [
        edge("report", END),
        # TODO: cond(...) from "identify_sources" via _should_continue()
        # TODO: cond(...) from "collect_artifacts" via _should_continue()
        # TODO: cond(...) from "hash_verify" via _should_continue()
        # TODO: cond(...) from "chain_of_custody" via _should_continue()
        # TODO: cond(...) from "package_evidence" via _should_continue()
    ]

    entry = "identify_sources"
