# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the change_risk_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.change_risk_analyzer.models import ChangeRiskAnalyzerState
from shieldops.agents.change_risk_analyzer.nodes import (
    analyze_diff,
    assess_risk,
    collect_change,
    generate_report,
    predict_blast_radius,
    recommend,
)
from shieldops.agents.change_risk_analyzer.tools import ChangeRiskAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class ChangeRiskAnalyzerAgent(Agent):
    """Declarative spec for ``change_risk_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "change_risk_analyzer"
    state_model = ChangeRiskAnalyzerState
    toolkit_factory = ChangeRiskAnalyzerToolkit

    nodes = {
        "collect_change": collect_change,
        "analyze_diff": analyze_diff,
        "assess_risk": assess_risk,
        "predict_blast_radius": predict_blast_radius,
        "recommend": recommend,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_change", "analyze_diff"),
        edge("analyze_diff", "assess_risk"),
        edge("assess_risk", "predict_blast_radius"),
        edge("predict_blast_radius", "recommend"),
        edge("recommend", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "collect_change"
