# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the performance_profiler agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.performance_profiler.models import PerformanceProfilerState
from shieldops.agents.performance_profiler.nodes import (
    analyze_latency,
    collect_traces,
    detect_bottlenecks,
    generate_report,
    identify_contention,
    recommend,
)
from shieldops.agents.performance_profiler.tools import PerformanceProfilerToolkit
from shieldops.agents.runtime import END, Agent, edge


class PerformanceProfilerAgent(Agent):
    """Declarative spec for ``performance_profiler`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "performance_profiler"
    state_model = PerformanceProfilerState
    toolkit_factory = PerformanceProfilerToolkit

    nodes = {
        "collect_traces": collect_traces,
        "analyze_latency": analyze_latency,
        "detect_bottlenecks": detect_bottlenecks,
        "identify_contention": identify_contention,
        "recommend": recommend,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_traces", "analyze_latency"),
        edge("analyze_latency", "detect_bottlenecks"),
        edge("identify_contention", "recommend"),
        edge("recommend", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_bottlenecks"
        #   routed by _should_recommend() — wrap with cond(...)
    ]

    entry = "collect_traces"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``PerformanceProfilerRunner`` keep working via this alias; new code
# should use ``PerformanceProfilerAgent`` directly through AgentRuntime.
PerformanceProfilerRunner = PerformanceProfilerAgent
