# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_entitlement_optimizer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_entitlement_optimizer.models import CloudEntitlementOptimizerState
from shieldops.agents.cloud_entitlement_optimizer.nodes import (
    analyze_usage,
    calculate_risk,
    generate_report,
    identify_excess,
    inventory_entitlements,
    recommend_changes,
)
from shieldops.agents.cloud_entitlement_optimizer.tools import CloudEntitlementOptimizerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudEntitlementOptimizerAgent(Agent):
    """Declarative spec for ``cloud_entitlement_optimizer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_entitlement_optimizer"
    state_model = CloudEntitlementOptimizerState
    toolkit_factory = CloudEntitlementOptimizerToolkit

    nodes = {
        "inventory_entitlements": inventory_entitlements,
        "analyze_usage": analyze_usage,
        "identify_excess": identify_excess,
        "calculate_risk": calculate_risk,
        "recommend_changes": recommend_changes,
        "generate_report": generate_report,
    }

    edges = [
        edge("inventory_entitlements", "analyze_usage"),
        edge("identify_excess", "calculate_risk"),
        edge("recommend_changes", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "analyze_usage" via _should_identify()
        # TODO: cond(...) from "calculate_risk" via _should_recommend()
    ]

    entry = "inventory_entitlements"
