# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the incident_replay_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.incident_replay_analyzer.models import IncidentReplayAnalyzerState
from shieldops.agents.incident_replay_analyzer.nodes import (
    analyze_decisions,
    generate_playbooks,
    generate_report,
    identify_improvements,
    reconstruct_timeline,
    select_incidents,
)
from shieldops.agents.incident_replay_analyzer.tools import IncidentReplayAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class IncidentReplayAnalyzerAgent(Agent):
    """Declarative spec for ``incident_replay_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "incident_replay_analyzer"
    state_model = IncidentReplayAnalyzerState
    toolkit_factory = IncidentReplayAnalyzerToolkit

    nodes = {
        "select_incidents": select_incidents,
        "reconstruct_timeline": reconstruct_timeline,
        "analyze_decisions": analyze_decisions,
        "identify_improvements": identify_improvements,
        "generate_playbooks": generate_playbooks,
        "generate_report": generate_report,
    }

    edges = [
        edge("select_incidents", "reconstruct_timeline"),
        edge("analyze_decisions", "identify_improvements"),
        edge("generate_playbooks", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "reconstruct_timeline" via _should_analyze()
        # TODO: cond(...) from "identify_improvements" via _should_generate_playbooks()
    ]

    entry = "select_incidents"
