# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the sensitive_data_monitor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.sensitive_data_monitor.models import SensitiveDataMonitorState
from shieldops.agents.sensitive_data_monitor.nodes import (
    assess_exposure,
    classify_data,
    discover_data_sources,
    enforce_controls,
    report,
    scan_for_sensitive,
)
from shieldops.agents.sensitive_data_monitor.tools import SensitiveDataMonitorToolkit


class SensitiveDataMonitorAgent(Agent):
    """Declarative spec for ``sensitive_data_monitor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "sensitive_data_monitor"
    state_model = SensitiveDataMonitorState
    toolkit_factory = SensitiveDataMonitorToolkit

    nodes = {
        "discover_data_sources": discover_data_sources,
        "scan_for_sensitive": scan_for_sensitive,
        "classify_data": classify_data,
        "assess_exposure": assess_exposure,
        "enforce_controls": enforce_controls,
        "report": report,
    }

    edges = [
        edge("discover_data_sources", "scan_for_sensitive"),
        edge("scan_for_sensitive", "classify_data"),
        edge("classify_data", "assess_exposure"),
        edge("enforce_controls", "report"),
        edge("report", END),
        # TODO: conditional edge from "assess_exposure"
        #   routed by _has_exposures() — wrap with cond(...)
    ]

    entry = "discover_data_sources"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SensitiveDataMonitorRunner`` keep working via this alias; new code
# should use ``SensitiveDataMonitorAgent`` directly through AgentRuntime.
SensitiveDataMonitorRunner = SensitiveDataMonitorAgent
