# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the access_certification_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.access_certification_engine.models import AccessCertificationEngineState
from shieldops.agents.access_certification_engine.nodes import (
    analyze_usage,
    collect_entitlements,
    generate_report,
    generate_reviews,
    identify_excess,
    process_decisions,
)
from shieldops.agents.access_certification_engine.tools import AccessCertificationEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class AccessCertificationEngineAgent(Agent):
    """Declarative spec for ``access_certification_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "access_certification_engine"
    state_model = AccessCertificationEngineState
    toolkit_factory = AccessCertificationEngineToolkit

    nodes = {
        "collect_entitlements": collect_entitlements,
        "analyze_usage": analyze_usage,
        "identify_excess": identify_excess,
        "generate_reviews": generate_reviews,
        "process_decisions": process_decisions,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_entitlements", "analyze_usage"),
        edge("analyze_usage", "identify_excess"),
        edge("generate_reviews", "process_decisions"),
        edge("process_decisions", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "identify_excess"
        #   routed by _should_review() — wrap with cond(...)
    ]

    entry = "collect_entitlements"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AccessCertificationEngineRunner`` keep working via this alias; new code
# should use ``AccessCertificationEngineAgent`` directly through AgentRuntime.
AccessCertificationEngineRunner = AccessCertificationEngineAgent
