# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_intelligence agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_intelligence.models import DataIntelligenceState
from shieldops.agents.data_intelligence.nodes import (
    assess_data_risk,
    classify_with_ai,
    discover_data,
    map_data_lineage,
    recommend_protection,
    report,
)
from shieldops.agents.data_intelligence.tools import DataIntelligenceToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataIntelligenceAgent(Agent):
    """Declarative spec for ``data_intelligence`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_intelligence"
    state_model = DataIntelligenceState
    toolkit_factory = DataIntelligenceToolkit

    nodes = {
        "discover_data": discover_data,
        "classify_with_ai": classify_with_ai,
        "map_data_lineage": map_data_lineage,
        "assess_data_risk": assess_data_risk,
        "recommend_protection": recommend_protection,
        "report": report,
    }

    edges = [
        edge("discover_data", "classify_with_ai"),
        edge("classify_with_ai", "map_data_lineage"),
        edge("map_data_lineage", "assess_data_risk"),
        edge("assess_data_risk", "recommend_protection"),
        edge("recommend_protection", "report"),
        edge("report", END),
    ]

    entry = "discover_data"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``DataIntelligenceRunner`` keep working via this alias; new code
# should use ``DataIntelligenceAgent`` directly through AgentRuntime.
DataIntelligenceRunner = DataIntelligenceAgent
