# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_posture agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_posture.models import SecurityPostureState
from shieldops.agents.security_posture.nodes import (
    assess_domains,
    generate_report,
    identify_gaps,
    prioritize_remediation,
)
from shieldops.agents.security_posture.tools import SecurityPostureToolkit


class SecurityPostureAgent(Agent):
    """Declarative spec for ``security_posture`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_posture"
    state_model = SecurityPostureState
    toolkit_factory = SecurityPostureToolkit

    nodes = {
        "assess_domains": assess_domains,
        "identify_gaps": identify_gaps,
        "prioritize_remediation": prioritize_remediation,
        "generate_report": generate_report,
    }

    edges = [
        edge("assess_domains", "identify_gaps"),
        edge("identify_gaps", "prioritize_remediation"),
        edge("prioritize_remediation", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "assess_domains"
