# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the auto_learning agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.auto_learning.models import AutoLearningState
from shieldops.agents.auto_learning.nodes import (
    assess_baseline,
    evaluate_and_decide,
    generate_proposals,
    run_experiments,
)
from shieldops.agents.auto_learning.tools import AutoLearningToolkit
from shieldops.agents.runtime import Agent, edge


class AutoLearningAgent(Agent):
    """Declarative spec for ``auto_learning`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "auto_learning"
    state_model = AutoLearningState
    toolkit_factory = AutoLearningToolkit

    nodes = {
        "assess": assess_baseline,
        "propose": generate_proposals,
        "experiment": run_experiments,
        "evaluate": evaluate_and_decide,
    }

    edges = [
        edge("assess", "propose"),
        edge("propose", "experiment"),
        edge("experiment", "evaluate"),
        # TODO: conditional edge from "evaluate"
        #   routed by should_continue() — wrap with cond(...)
    ]

    entry = "assess"
