# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the attack_narrative_builder agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.attack_narrative_builder.models import AttackNarrativeBuilderState
from shieldops.agents.attack_narrative_builder.nodes import (
    build_timeline,
    cluster_events,
    collect_events,
    generate_narrative,
    generate_report,
    map_mitre,
)
from shieldops.agents.attack_narrative_builder.tools import AttackNarrativeBuilderToolkit
from shieldops.agents.runtime import END, Agent, edge


class AttackNarrativeBuilderAgent(Agent):
    """Declarative spec for ``attack_narrative_builder`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "attack_narrative_builder"
    state_model = AttackNarrativeBuilderState
    toolkit_factory = AttackNarrativeBuilderToolkit

    nodes = {
        "collect_events": collect_events,
        "cluster_events": cluster_events,
        "build_timeline": build_timeline,
        "generate_narrative": generate_narrative,
        "map_mitre": map_mitre,
        "generate_report": generate_report,
    }

    edges = [
        edge("collect_events", "cluster_events"),
        edge("cluster_events", "build_timeline"),
        edge("generate_narrative", "map_mitre"),
        edge("map_mitre", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "build_timeline" via _should_narrate()
    ]

    entry = "collect_events"
