# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the data_privacy_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.data_privacy_scanner.models import DataPrivacyScannerState
from shieldops.agents.data_privacy_scanner.nodes import (
    assess_compliance,
    classify_data,
    detect_pii,
    generate_report,
    map_flows,
    scan_datastores,
)
from shieldops.agents.data_privacy_scanner.tools import DataPrivacyScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class DataPrivacyScannerAgent(Agent):
    """Declarative spec for ``data_privacy_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "data_privacy_scanner"
    state_model = DataPrivacyScannerState
    toolkit_factory = DataPrivacyScannerToolkit

    nodes = {
        "scan_datastores": scan_datastores,
        "classify_data": classify_data,
        "detect_pii": detect_pii,
        "map_flows": map_flows,
        "assess_compliance": assess_compliance,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_datastores", "classify_data"),
        edge("classify_data", "detect_pii"),
        edge("map_flows", "assess_compliance"),
        edge("assess_compliance", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "detect_pii"
        #   routed by _should_map_flows() — wrap with cond(...)
    ]

    entry = "scan_datastores"
