# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_automation_pipeline agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_automation_pipeline.models import SecurityAutomationPipelineState
from shieldops.agents.security_automation_pipeline.nodes import (
    enforce_gates,
    evaluate_results,
    generate_report,
    inject_gates,
    run_checks,
    scan_pipeline,
)
from shieldops.agents.security_automation_pipeline.tools import SecurityAutomationPipelineToolkit


class SecurityAutomationPipelineAgent(Agent):
    """Declarative spec for ``security_automation_pipeline`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_automation_pipeline"
    state_model = SecurityAutomationPipelineState
    toolkit_factory = SecurityAutomationPipelineToolkit

    nodes = {
        "scan_pipeline": scan_pipeline,
        "inject_gates": inject_gates,
        "run_checks": run_checks,
        "evaluate_results": evaluate_results,
        "enforce_gates": enforce_gates,
        "generate_report": generate_report,
    }

    edges = [
        edge("inject_gates", "run_checks"),
        edge("run_checks", "evaluate_results"),
        edge("enforce_gates", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "scan_pipeline" via _should_inject()
        # TODO: cond(...) from "evaluate_results" via _should_enforce()
    ]

    entry = "scan_pipeline"
