# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_copilot agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_copilot.models import SecurityCopilotState
from shieldops.agents.security_copilot.nodes import (
    analyze_data,
    generate_response,
    parse_query,
    report,
    search_context,
    validate_accuracy,
)
from shieldops.agents.security_copilot.tools import SecurityCopilotToolkit


class SecurityCopilotAgent(Agent):
    """Declarative spec for ``security_copilot`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_copilot"
    state_model = SecurityCopilotState
    toolkit_factory = SecurityCopilotToolkit

    nodes = {
        "parse_query": parse_query,
        "search_context": search_context,
        "analyze_data": analyze_data,
        "generate_response": generate_response,
        "validate_accuracy": validate_accuracy,
        "report": report,
    }

    edges = [
        edge("validate_accuracy", "report"),
        edge("report", END),
        # TODO: cond(...) from "parse_query" via _check_error()
        # TODO: cond(...) from "search_context" via _check_error()
        # TODO: cond(...) from "analyze_data" via _check_error()
        # TODO: cond(...) from "generate_response" via _check_error()
    ]

    entry = "parse_query"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityCopilotRunner`` keep working via this alias; new code
# should use ``SecurityCopilotAgent`` directly through AgentRuntime.
SecurityCopilotRunner = SecurityCopilotAgent
