# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the forensics agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.forensics.models import ForensicsState
from shieldops.agents.forensics.nodes import (
    analyze_disk,
    analyze_memory,
    analyze_network,
    collect_artifacts,
    extract_iocs,
    generate_report,
    preserve_evidence,
    reconstruct_timeline,
    synthesize,
    verify_integrity,
)
from shieldops.agents.forensics.tools import ForensicsToolkit
from shieldops.agents.runtime import END, Agent, edge


class ForensicsAgent(Agent):
    """Declarative spec for ``forensics`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "forensics"
    state_model = ForensicsState
    toolkit_factory = ForensicsToolkit

    nodes = {
        "preserve_evidence": preserve_evidence,
        "verify_integrity": verify_integrity,
        "collect_artifacts": collect_artifacts,
        "analyze_memory": analyze_memory,
        "analyze_disk": analyze_disk,
        "analyze_network": analyze_network,
        "reconstruct_timeline": reconstruct_timeline,
        "extract_iocs": extract_iocs,
        "synthesize": synthesize,
        "generate_report": generate_report,
    }

    edges = [
        edge("preserve_evidence", "verify_integrity"),
        edge("collect_artifacts", "analyze_memory"),
        edge("analyze_memory", "analyze_disk"),
        edge("analyze_disk", "analyze_network"),
        edge("analyze_network", "reconstruct_timeline"),
        edge("reconstruct_timeline", "extract_iocs"),
        edge("extract_iocs", "synthesize"),
        edge("synthesize", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "verify_integrity"
        #   routed by should_continue_after_integrity() — wrap with cond(...)
    ]

    entry = "preserve_evidence"
