# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the intelligent_soar agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.intelligent_soar.models import IntelligentSOARState
from shieldops.agents.intelligent_soar.nodes import (
    adapt_dynamically,
    execute_steps,
    receive_trigger,
    report,
    select_playbook,
    validate_outcome,
)
from shieldops.agents.intelligent_soar.tools import IntelligentSOARToolkit
from shieldops.agents.runtime import END, Agent, edge


class IntelligentSoarAgent(Agent):
    """Declarative spec for ``intelligent_soar`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "intelligent_soar"
    state_model = IntelligentSOARState
    toolkit_factory = IntelligentSOARToolkit

    nodes = {
        "receive_trigger": receive_trigger,
        "select_playbook": select_playbook,
        "execute_steps": execute_steps,
        "adapt_dynamically": adapt_dynamically,
        "validate_outcome": validate_outcome,
        "report": report,
    }

    edges = [
        edge("select_playbook", "execute_steps"),
        edge("adapt_dynamically", "validate_outcome"),
        edge("validate_outcome", "report"),
        edge("report", END),
        # TODO: conditional edge from "receive_trigger"
        #   routed by should_continue() — wrap with cond(...)
        # TODO: conditional edge from "execute_steps"
        #   routed by should_adapt() — wrap with cond(...)
    ]

    entry = "receive_trigger"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``IntelligentSOARRunner`` keep working via this alias; new code
# should use ``IntelligentSoarAgent`` directly through AgentRuntime.
IntelligentSOARRunner = IntelligentSoarAgent
