# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the vendor_compliance_assessor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.vendor_compliance_assessor.models import VendorComplianceAssessorState
from shieldops.agents.vendor_compliance_assessor.nodes import (
    assess_risk,
    collect_questionnaires,
    generate_report,
    inventory_vendors,
    report,
    score_compliance,
)
from shieldops.agents.vendor_compliance_assessor.tools import VendorComplianceAssessorToolkit


class VendorComplianceAssessorAgent(Agent):
    """Declarative spec for ``vendor_compliance_assessor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "vendor_compliance_assessor"
    state_model = VendorComplianceAssessorState
    toolkit_factory = VendorComplianceAssessorToolkit

    nodes = {
        "inventory_vendors": inventory_vendors,
        "collect_questionnaires": collect_questionnaires,
        "assess_risk": assess_risk,
        "score_compliance": score_compliance,
        "generate_report": generate_report,
        "report": report,
    }

    edges = [
        edge("inventory_vendors", "collect_questionnaires"),
        edge("collect_questionnaires", "assess_risk"),
        edge("assess_risk", "score_compliance"),
        edge("score_compliance", "generate_report"),
        edge("generate_report", "report"),
        edge("report", END),
    ]

    entry = "inventory_vendors"
