# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ai_model_governance agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ai_model_governance.models import AIModelGovernanceState
from shieldops.agents.ai_model_governance.nodes import (
    assess_risk,
    check_bias,
    enforce_policy,
    generate_report,
    inventory_models,
    validate_compliance,
)
from shieldops.agents.ai_model_governance.tools import AIModelGovernanceToolkit
from shieldops.agents.runtime import END, Agent, edge


class AiModelGovernanceAgent(Agent):
    """Declarative spec for ``ai_model_governance`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ai_model_governance"
    state_model = AIModelGovernanceState
    toolkit_factory = AIModelGovernanceToolkit

    nodes = {
        "inventory_models": inventory_models,
        "assess_risk": assess_risk,
        "check_bias": check_bias,
        "validate_compliance": validate_compliance,
        "enforce_policy": enforce_policy,
        "generate_report": generate_report,
    }

    edges = [
        edge("assess_risk", "check_bias"),
        edge("check_bias", "validate_compliance"),
        edge("enforce_policy", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "inventory_models" via _should_assess()
        # TODO: cond(...) from "validate_compliance" via _should_enforce()
    ]

    entry = "inventory_models"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AIModelGovernanceRunner`` keep working via this alias; new code
# should use ``AiModelGovernanceAgent`` directly through AgentRuntime.
AIModelGovernanceRunner = AiModelGovernanceAgent
