# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the micro_segmentation_planner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.micro_segmentation_planner.models import MicroSegmentationPlannerState
from shieldops.agents.micro_segmentation_planner.nodes import (
    define_policies,
    identify_segments,
    map_traffic,
    report,
    simulate,
    validate,
)
from shieldops.agents.micro_segmentation_planner.tools import MicroSegmentationPlannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class MicroSegmentationPlannerAgent(Agent):
    """Declarative spec for ``micro_segmentation_planner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "micro_segmentation_planner"
    state_model = MicroSegmentationPlannerState
    toolkit_factory = MicroSegmentationPlannerToolkit

    nodes = {
        "map_traffic": map_traffic,
        "identify_segments": identify_segments,
        "define_policies": define_policies,
        "simulate": simulate,
        "validate": validate,
        "report": report,
    }

    edges = [
        edge("validate", "report"),
        edge("report", END),
        # TODO: cond(...) from "map_traffic" via _check_error()
        # TODO: cond(...) from "identify_segments" via _check_error()
        # TODO: cond(...) from "define_policies" via _check_error()
        # TODO: cond(...) from "simulate" via _check_error()
    ]

    entry = "map_traffic"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``MicroSegmentationPlannerRunner`` keep working via this alias; new code
# should use ``MicroSegmentationPlannerAgent`` directly through AgentRuntime.
MicroSegmentationPlannerRunner = MicroSegmentationPlannerAgent
