# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the access_remediation agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.access_remediation.models import AccessRemediationState
from shieldops.agents.access_remediation.nodes import (
    audit_access,
    execute_changes,
    generate_report,
    identify_excess,
    plan_remediation,
    verify_access,
)
from shieldops.agents.access_remediation.tools import AccessRemediationToolkit
from shieldops.agents.runtime import END, Agent, edge


class AccessRemediationAgent(Agent):
    """Declarative spec for ``access_remediation`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "access_remediation"
    state_model = AccessRemediationState
    toolkit_factory = AccessRemediationToolkit

    nodes = {
        "audit_access": audit_access,
        "identify_excess": identify_excess,
        "plan_remediation": plan_remediation,
        "execute_changes": execute_changes,
        "verify_access": verify_access,
        "generate_report": generate_report,
    }

    edges = [
        edge("audit_access", "identify_excess"),
        edge("identify_excess", "plan_remediation"),
        edge("plan_remediation", "execute_changes"),
        edge("execute_changes", "verify_access"),
        edge("verify_access", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "audit_access"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AccessRemediationRunner`` keep working via this alias; new code
# should use ``AccessRemediationAgent`` directly through AgentRuntime.
AccessRemediationRunner = AccessRemediationAgent
