# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the fleet_coordination_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.fleet_coordination_engine.models import FleetCoordinationEngineState
from shieldops.agents.fleet_coordination_engine.nodes import (
    assess_health,
    discover_agents,
    dispatch_work,
    generate_report,
    monitor_progress,
    plan_routing,
)
from shieldops.agents.fleet_coordination_engine.tools import FleetCoordinationEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class FleetCoordinationEngineAgent(Agent):
    """Declarative spec for ``fleet_coordination_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "fleet_coordination_engine"
    state_model = FleetCoordinationEngineState
    toolkit_factory = FleetCoordinationEngineToolkit

    nodes = {
        "discover_agents": discover_agents,
        "assess_health": assess_health,
        "plan_routing": plan_routing,
        "dispatch_work": dispatch_work,
        "monitor_progress": monitor_progress,
        "generate_report": generate_report,
    }

    edges = [
        edge("assess_health", "plan_routing"),
        edge("dispatch_work", "monitor_progress"),
        edge("monitor_progress", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "discover_agents" via should_assess()
        # TODO: cond(...) from "plan_routing" via should_dispatch()
    ]

    entry = "discover_agents"
