# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the supply_chain_security agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.supply_chain_security.models import SupplyChainSecurityState
from shieldops.agents.supply_chain_security.nodes import (
    assess_risk,
    audit_cicd,
    generate_report,
    generate_sbom,
    scan_dependencies,
    verify_signatures,
)
from shieldops.agents.supply_chain_security.tools import SupplyChainSecurityToolkit


class SupplyChainSecurityAgent(Agent):
    """Declarative spec for ``supply_chain_security`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "supply_chain_security"
    state_model = SupplyChainSecurityState
    toolkit_factory = SupplyChainSecurityToolkit

    nodes = {
        "generate_sbom": generate_sbom,
        "scan_dependencies": scan_dependencies,
        "audit_cicd": audit_cicd,
        "verify_signatures": verify_signatures,
        "assess_risk": assess_risk,
        "generate_report": generate_report,
    }

    edges = [
        edge("generate_sbom", "scan_dependencies"),
        edge("scan_dependencies", "audit_cicd"),
        edge("audit_cicd", "verify_signatures"),
        edge("verify_signatures", "assess_risk"),
        edge("assess_risk", "generate_report"),
        edge("generate_report", END),
    ]

    entry = "generate_sbom"
