# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the otel_logs_pipeline agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.otel_logs_pipeline.models import OTelLogsPipelineState
from shieldops.agents.otel_logs_pipeline.nodes import (
    configure_pipeline,
    discover_sources,
    test_parsing,
    validate_correlation,
)
from shieldops.agents.otel_logs_pipeline.tools import OTelLogsPipelineToolkit
from shieldops.agents.runtime import END, Agent, edge


class OtelLogsPipelineAgent(Agent):
    """Declarative spec for ``otel_logs_pipeline`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "otel_logs_pipeline"
    state_model = OTelLogsPipelineState
    toolkit_factory = OTelLogsPipelineToolkit

    nodes = {
        "discover": discover_sources,
        "configure": configure_pipeline,
        "test_parsing": test_parsing,
        "validate": validate_correlation,
    }

    edges = [
        edge("discover", "configure"),
        edge("configure", "test_parsing"),
        edge("test_parsing", "validate"),
        edge("validate", END),
    ]

    entry = "discover"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``OTelLogsPipelineRunner`` keep working via this alias; new code
# should use ``OtelLogsPipelineAgent`` directly through AgentRuntime.
OTelLogsPipelineRunner = OtelLogsPipelineAgent
