# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the patch_orchestrator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.patch_orchestrator.models import PatchOrchestratorState
from shieldops.agents.patch_orchestrator.nodes import (
    assess_patches,
    deploy_patches,
    generate_report,
    inventory_systems,
    prioritize_deployment,
    verify_success,
)
from shieldops.agents.patch_orchestrator.tools import PatchOrchestratorToolkit
from shieldops.agents.runtime import END, Agent, edge


class PatchOrchestratorAgent(Agent):
    """Declarative spec for ``patch_orchestrator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "patch_orchestrator"
    state_model = PatchOrchestratorState
    toolkit_factory = PatchOrchestratorToolkit

    nodes = {
        "inventory_systems": inventory_systems,
        "assess_patches": assess_patches,
        "prioritize_deployment": prioritize_deployment,
        "deploy_patches": deploy_patches,
        "verify_success": verify_success,
        "generate_report": generate_report,
    }

    edges = [
        edge("inventory_systems", "assess_patches"),
        edge("assess_patches", "prioritize_deployment"),
        edge("prioritize_deployment", "deploy_patches"),
        edge("verify_success", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "deploy_patches"
        #   routed by route_after_deploy() — wrap with cond(...)
    ]

    entry = "inventory_systems"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``PatchOrchestratorRunner`` keep working via this alias; new code
# should use ``PatchOrchestratorAgent`` directly through AgentRuntime.
PatchOrchestratorRunner = PatchOrchestratorAgent
