# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the regulatory_change_tracker agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.regulatory_change_tracker.models import RegulatoryChangeTrackerState
from shieldops.agents.regulatory_change_tracker.nodes import (
    assess_impact,
    map_controls,
    notify_stakeholders,
    parse_updates,
    report,
    scan_sources,
)
from shieldops.agents.regulatory_change_tracker.tools import RegulatoryChangeTrackerToolkit
from shieldops.agents.runtime import END, Agent, edge


class RegulatoryChangeTrackerAgent(Agent):
    """Declarative spec for ``regulatory_change_tracker`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "regulatory_change_tracker"
    state_model = RegulatoryChangeTrackerState
    toolkit_factory = RegulatoryChangeTrackerToolkit

    nodes = {
        "scan_sources": scan_sources,
        "parse_updates": parse_updates,
        "assess_impact": assess_impact,
        "map_controls": map_controls,
        "notify_stakeholders": notify_stakeholders,
        "report": report,
    }

    edges = [
        edge("scan_sources", "parse_updates"),
        edge("parse_updates", "assess_impact"),
        edge("assess_impact", "map_controls"),
        edge("map_controls", "notify_stakeholders"),
        edge("notify_stakeholders", "report"),
        edge("report", END),
    ]

    entry = "scan_sources"
