# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the privilege_escalation_detector agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.privilege_escalation_detector.models import PrivilegeEscalationDetectorState
from shieldops.agents.privilege_escalation_detector.nodes import (
    assess_risk,
    classify_escalations,
    collect_events,
    correlate_identities,
    generate_report,
    respond,
)
from shieldops.agents.privilege_escalation_detector.tools import PrivilegeEscalationToolkit
from shieldops.agents.runtime import END, Agent, edge


class PrivilegeEscalationDetectorAgent(Agent):
    """Declarative spec for ``privilege_escalation_detector`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "privilege_escalation_detector"
    state_model = PrivilegeEscalationDetectorState
    toolkit_factory = PrivilegeEscalationToolkit

    nodes = {
        "collect_events": collect_events,
        "classify_escalations": classify_escalations,
        "correlate_identities": correlate_identities,
        "assess_risk": assess_risk,
        "respond": respond,
        "report": generate_report,
    }

    edges = [
        edge("collect_events", "classify_escalations"),
        edge("classify_escalations", "correlate_identities"),
        edge("correlate_identities", "assess_risk"),
        edge("respond", "report"),
        edge("report", END),
        # TODO: conditional edge from "assess_risk"
        #   routed by _has_findings() — wrap with cond(...)
    ]

    entry = "collect_events"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``PrivilegeEscalationDetectorRunner`` keep working via this alias; new code
# should use ``PrivilegeEscalationDetectorAgent`` directly through AgentRuntime.
PrivilegeEscalationDetectorRunner = PrivilegeEscalationDetectorAgent
