# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the soar_workflow agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.soar_workflow.models import SOARWorkflowState
from shieldops.agents.soar_workflow.nodes import (
    enrich_context,
    execute_containment,
    execute_eradication,
    intake_and_classify,
    recover_and_report,
)
from shieldops.agents.soar_workflow.tools import SOARWorkflowToolkit


class SoarWorkflowAgent(Agent):
    """Declarative spec for ``soar_workflow`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "soar_workflow"
    state_model = SOARWorkflowState
    toolkit_factory = SOARWorkflowToolkit

    nodes = {
        "intake_and_classify": intake_and_classify,
        "enrich_context": enrich_context,
        "execute_containment": execute_containment,
        "execute_eradication": execute_eradication,
        "recover_and_report": recover_and_report,
    }

    edges = [
        edge("intake_and_classify", "enrich_context"),
        edge("enrich_context", "execute_containment"),
        edge("execute_containment", "execute_eradication"),
        edge("execute_eradication", "recover_and_report"),
        edge("recover_and_report", END),
    ]

    entry = "intake_and_classify"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SOARWorkflowRunner`` keep working via this alias; new code
# should use ``SoarWorkflowAgent`` directly through AgentRuntime.
SOARWorkflowRunner = SoarWorkflowAgent
