# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the credential_exposure_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.credential_exposure_scanner.models import CredentialExposureScannerState
from shieldops.agents.credential_exposure_scanner.nodes import (
    assess_exposure,
    classify_type,
    detect_credentials,
    generate_report,
    scan_sources,
    trigger_rotation,
)
from shieldops.agents.credential_exposure_scanner.tools import CredentialExposureScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class CredentialExposureScannerAgent(Agent):
    """Declarative spec for ``credential_exposure_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "credential_exposure_scanner"
    state_model = CredentialExposureScannerState
    toolkit_factory = CredentialExposureScannerToolkit

    nodes = {
        "scan_sources": scan_sources,
        "detect_credentials": detect_credentials,
        "classify_type": classify_type,
        "assess_exposure": assess_exposure,
        "trigger_rotation": trigger_rotation,
        "report": generate_report,
    }

    edges = [
        edge("scan_sources", "detect_credentials"),
        edge("detect_credentials", "classify_type"),
        edge("classify_type", "assess_exposure"),
        edge("assess_exposure", "trigger_rotation"),
        edge("trigger_rotation", "report"),
        edge("report", END),
    ]

    entry = "scan_sources"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CredentialExposureScannerRunner`` keep working via this alias; new code
# should use ``CredentialExposureScannerAgent`` directly through AgentRuntime.
CredentialExposureScannerRunner = CredentialExposureScannerAgent
