"""Event types for the WebSocket Hub core.

All types here are pure data — plain dataclasses + Pydantic models, no
behavior. The Hub core in :mod:`shieldops.api.ws.core.hub` reads and
writes these; adapters translate them at the boundary.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass(frozen=True)
class Principal:
    """Authenticated subject for a WebSocket connection."""

    tenant_id: str
    user_id: str = ""


@dataclass(frozen=True)
class Event:
    """Event published by a producer via :meth:`Hub.publish`."""

    kind: str
    data: dict[str, Any]


@dataclass(frozen=True)
class BufferedEvent:
    """Event as stored in the Buffer port and delivered to subscribers.

    ``id`` is a monotonic string generated by the Hub (``evt-000000001``).
    ``payload`` is the already-encoded JSON bytes — buffered in its wire
    format so replays are free of serialization work.
    """

    id: str
    kind: str
    payload: bytes
    ts: float
    channel: str


@dataclass
class Subscription:
    """One attached WebSocket connection's per-session state."""

    conn_id: str
    channel: str
    principal: Principal
    queue: asyncio.Queue
    drain_task: asyncio.Task | None = None


@dataclass(frozen=True)
class HubConfig:
    """Tunable knobs for the Hub core."""

    queue_max: int = 256
    drop_policy: Literal["oldest", "newest", "disconnect"] = "oldest"
    heartbeat_s: float = 20.0
    replay_max_age_s: float = 300.0
    replay_max_events: int = 1000


@dataclass
class SentEvent:
    """Record of an event sent to a connection — used by InMemoryTransport.

    The Hub does not use this type; it exists here so adapters can return
    structured information to tests without inventing their own shapes.
    """

    conn_id: str
    event_id: str
    data: dict[str, Any] = field(default_factory=dict)
