# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the federated_learning_security agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.federated_learning_security.models import FederatedLearningSecurityState
from shieldops.agents.federated_learning_security.nodes import (
    assess_risk,
    detect_poisoning,
    inspect_gradients,
    report,
    score_participants,
    verify_aggregation,
)
from shieldops.agents.federated_learning_security.tools import FederatedLearningSecurityToolkit
from shieldops.agents.runtime import END, Agent, edge


class FederatedLearningSecurityAgent(Agent):
    """Declarative spec for ``federated_learning_security`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "federated_learning_security"
    state_model = FederatedLearningSecurityState
    toolkit_factory = FederatedLearningSecurityToolkit

    nodes = {
        "inspect_gradients": inspect_gradients,
        "detect_poisoning": detect_poisoning,
        "score_participants": score_participants,
        "verify_aggregation": verify_aggregation,
        "assess_risk": assess_risk,
        "report": report,
    }

    edges = [
        edge("assess_risk", "report"),
        edge("report", END),
        # TODO: cond(...) from "inspect_gradients" via _check_error()
        # TODO: cond(...) from "detect_poisoning" via _check_error()
        # TODO: cond(...) from "score_participants" via _check_error()
        # TODO: cond(...) from "verify_aggregation" via _check_error()
    ]

    entry = "inspect_gradients"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``FederatedLearningSecurityRunner`` keep working via this alias; new code
# should use ``FederatedLearningSecurityAgent`` directly through AgentRuntime.
FederatedLearningSecurityRunner = FederatedLearningSecurityAgent
