# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the incident_commander agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.incident_commander.models import IncidentCommanderState
from shieldops.agents.incident_commander.nodes import (
    close_incident,
    coordinate_agents,
    monitor_and_decide,
    triage,
)
from shieldops.agents.incident_commander.tools import IncidentCommanderToolkit
from shieldops.agents.runtime import END, Agent, edge


class IncidentCommanderAgent(Agent):
    """Declarative spec for ``incident_commander`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "incident_commander"
    state_model = IncidentCommanderState
    toolkit_factory = IncidentCommanderToolkit

    nodes = {
        "triage": triage,
        "coordinate_agents": coordinate_agents,
        "monitor_and_decide": monitor_and_decide,
        "close_incident": close_incident,
    }

    edges = [
        edge("triage", "coordinate_agents"),
        edge("coordinate_agents", "monitor_and_decide"),
        edge("close_incident", END),
        # TODO: cond(...) from "monitor_and_decide" via route_after_monitor()
    ]

    entry = "triage"
