# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the model_explainability_auditor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.model_explainability_auditor.models import ModelExplainabilityAuditorState
from shieldops.agents.model_explainability_auditor.nodes import (
    analyze_shap,
    check_fairness,
    collect_predictions,
    compute_importance,
    generate_report,
    report,
)
from shieldops.agents.model_explainability_auditor.tools import ModelExplainabilityAuditorToolkit
from shieldops.agents.runtime import END, Agent, edge


class ModelExplainabilityAuditorAgent(Agent):
    """Declarative spec for ``model_explainability_auditor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "model_explainability_auditor"
    state_model = ModelExplainabilityAuditorState
    toolkit_factory = ModelExplainabilityAuditorToolkit

    nodes = {
        "collect_predictions": collect_predictions,
        "compute_importance": compute_importance,
        "analyze_shap": analyze_shap,
        "check_fairness": check_fairness,
        "generate_report": generate_report,
        "report": report,
    }

    edges = [
        edge("generate_report", "report"),
        edge("report", END),
        # TODO: cond(...) from "collect_predictions" via _check_error()
        # TODO: cond(...) from "compute_importance" via _check_error()
        # TODO: cond(...) from "analyze_shap" via _check_error()
        # TODO: cond(...) from "check_fairness" via _check_error()
    ]

    entry = "collect_predictions"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``ModelExplainabilityAuditorRunner`` keep working via this alias; new code
# should use ``ModelExplainabilityAuditorAgent`` directly through AgentRuntime.
ModelExplainabilityAuditorRunner = ModelExplainabilityAuditorAgent
