# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the mitre_coverage_analyzer agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.mitre_coverage_analyzer.models import MITRECoverageAnalyzerState
from shieldops.agents.mitre_coverage_analyzer.nodes import (
    calculate_coverage,
    generate_report,
    identify_gaps,
    inventory_detections,
    map_to_mitre,
    recommend_rules,
)
from shieldops.agents.mitre_coverage_analyzer.tools import MITRECoverageAnalyzerToolkit
from shieldops.agents.runtime import END, Agent, edge


class MitreCoverageAnalyzerAgent(Agent):
    """Declarative spec for ``mitre_coverage_analyzer`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "mitre_coverage_analyzer"
    state_model = MITRECoverageAnalyzerState
    toolkit_factory = MITRECoverageAnalyzerToolkit

    nodes = {
        "inventory_detections": inventory_detections,
        "map_to_mitre": map_to_mitre,
        "calculate_coverage": calculate_coverage,
        "identify_gaps": identify_gaps,
        "recommend_rules": recommend_rules,
        "generate_report": generate_report,
    }

    edges = [
        edge("map_to_mitre", "calculate_coverage"),
        edge("calculate_coverage", "identify_gaps"),
        edge("identify_gaps", "recommend_rules"),
        edge("recommend_rules", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "inventory_detections"
        #   routed by _has_detections() — wrap with cond(...)
    ]

    entry = "inventory_detections"
