# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the defense_in_depth_auditor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.defense_in_depth_auditor.models import DefenseInDepthAuditorState
from shieldops.agents.defense_in_depth_auditor.nodes import (
    assess_controls,
    identify_gaps,
    map_layers,
    recommend,
    report,
    test_resilience,
)
from shieldops.agents.defense_in_depth_auditor.tools import DefenseInDepthAuditorToolkit
from shieldops.agents.runtime import END, Agent, edge


class DefenseInDepthAuditorAgent(Agent):
    """Declarative spec for ``defense_in_depth_auditor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "defense_in_depth_auditor"
    state_model = DefenseInDepthAuditorState
    toolkit_factory = DefenseInDepthAuditorToolkit

    nodes = {
        "map_layers": map_layers,
        "assess_controls": assess_controls,
        "identify_gaps": identify_gaps,
        "test_resilience": test_resilience,
        "recommend": recommend,
        "report": report,
    }

    edges = [
        edge("recommend", "report"),
        edge("report", END),
        # TODO: cond(...) from "map_layers" via _check_error()
        # TODO: cond(...) from "assess_controls" via _check_error()
        # TODO: cond(...) from "identify_gaps" via _check_error()
        # TODO: cond(...) from "test_resilience" via _check_error()
    ]

    entry = "map_layers"
