# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the ai_runtime_defense agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.ai_runtime_defense.models import AIRuntimeDefenseState
from shieldops.agents.ai_runtime_defense.nodes import (
    detect_exfiltration,
    detect_model_abuse,
    execute_response,
    generate_policies,
    generate_report,
    scan_prompts,
    scan_supply_chain,
)
from shieldops.agents.ai_runtime_defense.tools import AIRuntimeDefenseToolkit
from shieldops.agents.runtime import END, Agent, edge


class AiRuntimeDefenseAgent(Agent):
    """Declarative spec for ``ai_runtime_defense`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "ai_runtime_defense"
    state_model = AIRuntimeDefenseState
    toolkit_factory = AIRuntimeDefenseToolkit

    nodes = {
        "scan_prompts": scan_prompts,
        "detect_exfiltration": detect_exfiltration,
        "detect_model_abuse": detect_model_abuse,
        "scan_supply_chain": scan_supply_chain,
        "generate_policies": generate_policies,
        "execute_response": execute_response,
        "generate_report": generate_report,
    }

    edges = [
        edge("scan_prompts", "detect_exfiltration"),
        edge("detect_exfiltration", "detect_model_abuse"),
        edge("detect_model_abuse", "scan_supply_chain"),
        edge("generate_policies", "execute_response"),
        edge("execute_response", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "scan_supply_chain"
        #   routed by _has_findings() — wrap with cond(...)
    ]

    entry = "scan_prompts"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AIRuntimeDefenseRunner`` keep working via this alias; new code
# should use ``AiRuntimeDefenseAgent`` directly through AgentRuntime.
AIRuntimeDefenseRunner = AiRuntimeDefenseAgent
