# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the identity_intelligence_hub agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.identity_intelligence_hub.models import IdentityIntelligenceHubState
from shieldops.agents.identity_intelligence_hub.nodes import (
    assess_risk,
    collect_identity_signals,
    correlate_identities,
    detect_threats,
    generate_report,
    recommend_actions,
)
from shieldops.agents.identity_intelligence_hub.tools import IdentityIntelligenceHubToolkit
from shieldops.agents.runtime import END, Agent, edge


class IdentityIntelligenceHubAgent(Agent):
    """Declarative spec for ``identity_intelligence_hub`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "identity_intelligence_hub"
    state_model = IdentityIntelligenceHubState
    toolkit_factory = IdentityIntelligenceHubToolkit

    nodes = {
        "collect_identity_signals": collect_identity_signals,
        "correlate_identities": correlate_identities,
        "detect_threats": detect_threats,
        "assess_risk": assess_risk,
        "recommend_actions": recommend_actions,
        "generate_report": generate_report,
    }

    edges = [
        edge("correlate_identities", "detect_threats"),
        edge("detect_threats", "assess_risk"),
        edge("recommend_actions", "generate_report"),
        edge("generate_report", END),
        # TODO: cond(...) from "collect_identity_signals" via should_correlate()
        # TODO: cond(...) from "assess_risk" via should_recommend()
    ]

    entry = "collect_identity_signals"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``IdentityIntelligenceHubRunner`` keep working via this alias; new code
# should use ``IdentityIntelligenceHubAgent`` directly through AgentRuntime.
IdentityIntelligenceHubRunner = IdentityIntelligenceHubAgent
