# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the autonomous_defense agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.autonomous_defense.models import AutonomousDefenseState
from shieldops.agents.autonomous_defense.nodes import (
    assess_threats,
    deploy_countermeasures,
    finalize_defense,
    select_defenses,
    validate_protection,
)
from shieldops.agents.autonomous_defense.tools import AutonomousDefenseToolkit
from shieldops.agents.runtime import END, Agent, edge


class AutonomousDefenseAgent(Agent):
    """Declarative spec for ``autonomous_defense`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "autonomous_defense"
    state_model = AutonomousDefenseState
    toolkit_factory = AutonomousDefenseToolkit

    nodes = {
        "assess_threats": assess_threats,
        "select_defenses": select_defenses,
        "deploy_countermeasures": deploy_countermeasures,
        "validate_protection": validate_protection,
        "finalize_defense": finalize_defense,
    }

    edges = [
        edge("select_defenses", "deploy_countermeasures"),
        edge("deploy_countermeasures", "validate_protection"),
        edge("validate_protection", "finalize_defense"),
        edge("finalize_defense", END),
        # TODO: conditional edge from "assess_threats"
        #   routed by should_continue() — wrap with cond(...)
    ]

    entry = "assess_threats"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AutonomousDefenseRunner`` keep working via this alias; new code
# should use ``AutonomousDefenseAgent`` directly through AgentRuntime.
AutonomousDefenseRunner = AutonomousDefenseAgent
