# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the security_alert_router agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.runtime import END, Agent, edge
from shieldops.agents.security_alert_router.models import SecurityAlertRouterState
from shieldops.agents.security_alert_router.nodes import (
    classify_alerts,
    determine_owner,
    generate_report,
    receive_alerts,
    route_to_team,
    track_acknowledgment,
)
from shieldops.agents.security_alert_router.tools import SecurityAlertRouterToolkit


class SecurityAlertRouterAgent(Agent):
    """Declarative spec for ``security_alert_router`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "security_alert_router"
    state_model = SecurityAlertRouterState
    toolkit_factory = SecurityAlertRouterToolkit

    nodes = {
        "receive_alerts": receive_alerts,
        "classify_alerts": classify_alerts,
        "determine_owner": determine_owner,
        "route_to_team": route_to_team,
        "track_acknowledgment": track_acknowledgment,
        "generate_report": generate_report,
    }

    edges = [
        edge("receive_alerts", "classify_alerts"),
        edge("classify_alerts", "determine_owner"),
        edge("determine_owner", "route_to_team"),
        edge("track_acknowledgment", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "route_to_team"
        #   routed by _should_track() — wrap with cond(...)
    ]

    entry = "receive_alerts"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``SecurityAlertRouterRunner`` keep working via this alias; new code
# should use ``SecurityAlertRouterAgent`` directly through AgentRuntime.
SecurityAlertRouterRunner = SecurityAlertRouterAgent
