# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the digital_forensics_lab agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.digital_forensics_lab.models import DigitalForensicsLabState
from shieldops.agents.digital_forensics_lab.nodes import (
    acquire_evidence,
    analyze_artifacts,
    build_timeline,
    extract_iocs,
    generate_forensic_report,
)
from shieldops.agents.digital_forensics_lab.tools import DigitalForensicsLabToolkit
from shieldops.agents.runtime import END, Agent, edge


class DigitalForensicsLabAgent(Agent):
    """Declarative spec for ``digital_forensics_lab`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "digital_forensics_lab"
    state_model = DigitalForensicsLabState
    toolkit_factory = DigitalForensicsLabToolkit

    nodes = {
        "acquire_evidence": acquire_evidence,
        "analyze_artifacts": analyze_artifacts,
        "extract_iocs": extract_iocs,
        "build_timeline": build_timeline,
        "generate_forensic_report": generate_forensic_report,
    }

    edges = [
        edge("acquire_evidence", "analyze_artifacts"),
        edge("analyze_artifacts", "extract_iocs"),
        edge("build_timeline", "generate_forensic_report"),
        edge("generate_forensic_report", END),
        # TODO: conditional edge from "extract_iocs"
        #   routed by _should_build_timeline() — wrap with cond(...)
    ]

    entry = "acquire_evidence"
