# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the open_source_license_scanner agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.open_source_license_scanner.models import OpenSourceLicenseScannerState
from shieldops.agents.open_source_license_scanner.nodes import (
    check_compatibility,
    discover_deps,
    flag_violations,
    identify_licenses,
    recommend,
    report,
)
from shieldops.agents.open_source_license_scanner.tools import OpenSourceLicenseScannerToolkit
from shieldops.agents.runtime import END, Agent, edge


class OpenSourceLicenseScannerAgent(Agent):
    """Declarative spec for ``open_source_license_scanner`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "open_source_license_scanner"
    state_model = OpenSourceLicenseScannerState
    toolkit_factory = OpenSourceLicenseScannerToolkit

    nodes = {
        "discover_deps": discover_deps,
        "identify_licenses": identify_licenses,
        "check_compatibility": check_compatibility,
        "flag_violations": flag_violations,
        "recommend": recommend,
        "report": report,
    }

    edges = [
        edge("recommend", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_deps" via _check_error()
        # TODO: cond(...) from "identify_licenses" via _check_error()
        # TODO: cond(...) from "check_compatibility" via _check_error()
        # TODO: cond(...) from "flag_violations" via _check_error()
    ]

    entry = "discover_deps"
