# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the autonomous_xdr agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.autonomous_xdr.models import AutonomousXDRState
from shieldops.agents.autonomous_xdr.nodes import (
    auto_investigate,
    collect_telemetry,
    correlate_cross_domain,
    detect_campaigns,
    normalize_signals,
    report,
    respond,
)
from shieldops.agents.autonomous_xdr.tools import AutonomousXDRToolkit
from shieldops.agents.runtime import END, Agent, edge


class AutonomousXdrAgent(Agent):
    """Declarative spec for ``autonomous_xdr`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "autonomous_xdr"
    state_model = AutonomousXDRState
    toolkit_factory = AutonomousXDRToolkit

    nodes = {
        "collect_telemetry": collect_telemetry,
        "normalize_signals": normalize_signals,
        "correlate_cross_domain": correlate_cross_domain,
        "detect_campaigns": detect_campaigns,
        "auto_investigate": auto_investigate,
        "respond": respond,
        "report": report,
    }

    edges = [
        edge("normalize_signals", "correlate_cross_domain"),
        edge("correlate_cross_domain", "detect_campaigns"),
        edge("auto_investigate", "respond"),
        edge("respond", "report"),
        edge("report", END),
        # TODO: conditional edge from "collect_telemetry"
        #   routed by _should_continue() — wrap with cond(...)
        # TODO: conditional edge from "detect_campaigns"
        #   routed by _should_investigate() — wrap with cond(...)
    ]

    entry = "collect_telemetry"
