# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the cloud_drift_remediator agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.cloud_drift_remediator.models import CloudDriftRemediatorState
from shieldops.agents.cloud_drift_remediator.nodes import (
    classify_risk,
    detect_drift,
    execute_fix,
    generate_report,
    plan_remediation,
    scan_baseline,
)
from shieldops.agents.cloud_drift_remediator.tools import CloudDriftRemediatorToolkit
from shieldops.agents.runtime import END, Agent, edge


class CloudDriftRemediatorAgent(Agent):
    """Declarative spec for ``cloud_drift_remediator`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "cloud_drift_remediator"
    state_model = CloudDriftRemediatorState
    toolkit_factory = CloudDriftRemediatorToolkit

    nodes = {
        "scan_baseline": scan_baseline,
        "detect_drift": detect_drift,
        "classify_risk": classify_risk,
        "plan_remediation": plan_remediation,
        "execute_fix": execute_fix,
        "generate_report": generate_report,
    }

    edges = [
        edge("detect_drift", "classify_risk"),
        edge("classify_risk", "plan_remediation"),
        edge("execute_fix", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "scan_baseline"
        #   routed by _should_detect() — wrap with cond(...)
        # TODO: conditional edge from "plan_remediation"
        #   routed by _should_execute() — wrap with cond(...)
    ]

    entry = "scan_baseline"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``CloudDriftRemediatorRunner`` keep working via this alias; new code
# should use ``CloudDriftRemediatorAgent`` directly through AgentRuntime.
CloudDriftRemediatorRunner = CloudDriftRemediatorAgent
