# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the autonomous_response_engine agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.autonomous_response_engine.models import AutonomousResponseEngineState
from shieldops.agents.autonomous_response_engine.nodes import (
    classify_severity,
    detect_incident,
    execute_response,
    generate_report,
    select_playbook,
    validate_outcome,
)
from shieldops.agents.autonomous_response_engine.tools import AutonomousResponseEngineToolkit
from shieldops.agents.runtime import END, Agent, edge


class AutonomousResponseEngineAgent(Agent):
    """Declarative spec for ``autonomous_response_engine`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "autonomous_response_engine"
    state_model = AutonomousResponseEngineState
    toolkit_factory = AutonomousResponseEngineToolkit

    nodes = {
        "detect_incident": detect_incident,
        "classify_severity": classify_severity,
        "select_playbook": select_playbook,
        "execute_response": execute_response,
        "validate_outcome": validate_outcome,
        "generate_report": generate_report,
    }

    edges = [
        edge("detect_incident", "classify_severity"),
        edge("classify_severity", "select_playbook"),
        edge("execute_response", "validate_outcome"),
        edge("validate_outcome", "generate_report"),
        edge("generate_report", END),
        # TODO: conditional edge from "select_playbook"
        #   routed by _should_execute() — wrap with cond(...)
    ]

    entry = "detect_incident"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``AutonomousResponseEngineRunner`` keep working via this alias; new code
# should use ``AutonomousResponseEngineAgent`` directly through AgentRuntime.
AutonomousResponseEngineRunner = AutonomousResponseEngineAgent
