# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the iso27001_assessor agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.iso27001_assessor.models import ISO27001AssessorState
from shieldops.agents.iso27001_assessor.nodes import (
    assess_controls,
    identify_gaps,
    report,
    risk_treatment,
    scope_isms,
    soa,
)
from shieldops.agents.iso27001_assessor.tools import ISO27001AssessorToolkit
from shieldops.agents.runtime import END, Agent, edge


class Iso27001AssessorAgent(Agent):
    """Declarative spec for ``iso27001_assessor`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "iso27001_assessor"
    state_model = ISO27001AssessorState
    toolkit_factory = ISO27001AssessorToolkit

    nodes = {
        "scope_isms": scope_isms,
        "assess_controls": assess_controls,
        "identify_gaps": identify_gaps,
        "risk_treatment": risk_treatment,
        "soa": soa,
        "report": report,
    }

    edges = [
        edge("soa", "report"),
        edge("report", END),
        # TODO: cond(...) from "scope_isms" via _check_error()
        # TODO: cond(...) from "assess_controls" via _check_error()
        # TODO: cond(...) from "identify_gaps" via _check_error()
        # TODO: cond(...) from "risk_treatment" via _check_error()
    ]

    entry = "scope_isms"
