# RFC #247: agent.py replaces runner.py + graph.py (generated by scripts/codemods/agent_runtime.py)
"""Declarative ``Agent`` spec for the building_management_security agent.

Generated by ``scripts/codemods/agent_runtime.py`` from the legacy
``runner.py`` + ``graph.py`` pair. See RFC #247.
"""

from __future__ import annotations

from shieldops.agents.building_management_security.models import BuildingManagementSecurityState
from shieldops.agents.building_management_security.nodes import (
    assess_risk,
    audit_configs,
    check_access,
    detect_anomalies,
    discover_systems,
    report,
)
from shieldops.agents.building_management_security.tools import BuildingManagementSecurityToolkit
from shieldops.agents.runtime import END, Agent, edge


class BuildingManagementSecurityAgent(Agent):
    """Declarative spec for ``building_management_security`` — mounted by AgentRuntime."""

    _shieldops_runtime_migrated = True

    name = "building_management_security"
    state_model = BuildingManagementSecurityState
    toolkit_factory = BuildingManagementSecurityToolkit

    nodes = {
        "discover_systems": discover_systems,
        "audit_configs": audit_configs,
        "check_access": check_access,
        "detect_anomalies": detect_anomalies,
        "assess_risk": assess_risk,
        "report": report,
    }

    edges = [
        edge("assess_risk", "report"),
        edge("report", END),
        # TODO: cond(...) from "discover_systems" via _check_error()
        # TODO: cond(...) from "audit_configs" via _check_error()
        # TODO: cond(...) from "check_access" via _check_error()
        # TODO: cond(...) from "detect_anomalies" via _check_error()
    ]

    entry = "discover_systems"


# RFC #247 PR-6 legacy alias — runner.py was deleted. Existing callers that
# imported ``BuildingManagementSecurityRunner`` keep working via this alias; new code
# should use ``BuildingManagementSecurityAgent`` directly through AgentRuntime.
BuildingManagementSecurityRunner = BuildingManagementSecurityAgent
